### ISSUE TITLE
When `od` doesn't have a "-A", bash fails to start.

### ISSUE THREAD

**Issue by Reichenbachian** [seanmonstar/warp#1001]
**Version**
I don't compile my own Warp, but the release version is `v0.2022.10.18.08.10.stable_01`

**Platform**
```
Darwin {Hostname} 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
```

**Description**
When I ssh into a computer running a yocto build (basically a light linux), the warp shell fails to start. The exact output is
```
ssh root@{computer name}
od: invalid option -- 'A'
BusyBox v1.31.1 () multi-call binary.

Usage: od [-aBbcDdeFfHhIiLlOovXx] [FILE]

Print FILE (or stdin) unambiguously, as octal bytes by default
sh-5.0#
```
I suspect warp is attempting to instantiate a shell, but failing to do so. If this is the case, I would hope that it falls back into `bash` rather than `sh` if `bash` is present.

Expectation: Goes into `bash` (what my default terminal does)
Current Implementation: Goes into `sh`

**Comment by seanmonstar** [comment]
This repository is about a web server framework, you probably want https://github.com/warpdotdev/Warp

**Comment by Reichenbachian** [comment]
Ope. My bad. Thanks.
