### ISSUE TITLE
ssh: exec request failed on channel 1

### ISSUE THREAD

**Issue by jiangtao** [seanmonstar/warp#1006]
**Version**
v0.2022.11.08.08.07.stable_02

`cargo install cargo-tree`
(see install here: https://github.com/sfackler/cargo-tree)

Then:

`cargo tree | grep warp`

**Platform**
Darwin MacBook-Pro-3.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

**Description**
When I use ssh to connect the remote ip, the wrap terminal request an message `exec request failed on channel 1`.
It worked fine in the iterm2 or mac terminal.

**Comment by seanmonstar** [comment]
This repo is for a Rust web server framework, not the terminal program.

**Comment by jiangtao** [comment]
Sorry.. I miss the road

**Comment by jiangtao** [comment]
Sorry. I lost the way.
