### ISSUE TITLE
I could not find file upload example 

### ISSUE THREAD

**Issue by krishnaTORQUE** [seanmonstar/warp#1008]
**Is your feature request related to a problem? Please describe.**
How to upload file?

**Describe the solution you'd like**
Upload file, Multipart Formdata

**Comment by seanmonstar** [comment]
There doesn't appear to be an example. A fine place to add a small example could be on the `warp::multipart` docs: https://docs.rs/warp/latest/warp/filters/multipart/index.html

**Comment by krishnaTORQUE** [comment]
An example would be really helpful 😊

**Comment by krishnaTORQUE** [comment]
for future if anyone looking for example
https://github.com/zupzup/warp-upload-download-example/blob/main/src/main.rs
