### ISSUE TITLE
support for unix domain sockets?

### ISSUE THREAD

**Issue by glelk** [seanmonstar/warp#101]
I'd like to use unix domain socket as a server connection, but Server accepts only SocketAddr. I am aware of [tokio-uds](https://github.com/tokio-rs/tokio-uds) (which is btw archived) but could not find out how to use it in warp Server. There is also [hyperlocal](https://github.com/softprops/hyperlocal), but it provides its own server.

In general, wouldtn't the whole rust-net/web framework be more composable if servers (and clients) used a trait for connection instead of a concrete type? E.g. like Conn interface in go?

**Comment by seanmonstar** [comment]
> In general, wouldtn't the whole rust-net/web framework be more composable if servers (and clients) used a trait for connection instead of a concrete type?

Yep! It's supported via hyper's `Server::builder(incoming)` API (and client) by being generic over `T: AsyncRead + AsyncWrite`.

In warp, it purposefully hasn't been exposed yet, as I had questions around exposing this generic interface. It's also somewhat related TLS (#83).

**Comment by glelk** [comment]
It is working as advertised, thanks!
