### ISSUE TITLE
warp::generic::Tuple warnings after updating Rust to 1.66

### ISSUE THREAD

**Issue by rsalmei** [seanmonstar/warp#1012]
**Version**
```
└── warp v0.3.3
```

**Platform**
```
Darwin macbook.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
```

**Description**
Hi, I've updated Rust today to 1.66, and suddenly some warp code of mine started emitting several warnings:
```
warning: opaque type `impl warp::Filter + Clone + warp::filter::FilterBase<Extract = impl Reply, Error = Rejection>` does not satisfy its associated type bounds
   --> src/api/mod.rs:139:18
    |
139 | ) -> impl Filter<Extract = impl Reply, Error = warp::Rejection> + Clone {
    |                  ^^^^^^^^^^^^^^^^^^^^
    |
   ::: /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.3/src/filter/mod.rs:40:19
    |
40  |     type Extract: Tuple; // + Send;
    |                   ----- this associated type bound is unsatisfied for `impl Reply`
    |
help: add this bound
    |
139 | ) -> impl Filter<Extract = impl Reply + warp::generic::Tuple, Error = warp::Rejection> + Clone {
    |                                       ++++++++++++++++++++++

warning: 5 warnings emitted
```

The suggestion is bogus since `warp::generic::Tuple` is private...
I've tried updating, but there isn't any warp update for this yet.

The methods are ones that mount routes, something like this for websockets:
```rust
fn events_ws() -> impl Filter<Extract = impl Reply, Error = warp::Rejection> + Clone {
    warp::path!("v2" / "ws-events" / String)
        .and(warp::ws())
        .and(warp::path::end())
        .map(move |token, ws: warp::ws::Ws| {
            ws.on_upgrade(move |socket| ws_events(socket, token))
        })
}
```
Which I later call in the main method:
```rust
    let api = warp::path("api").and(
        events_ws()
            .or(...)
            .or(...)
            .or(...)
    );
    let api = api.with(warp::log("api"));
    warp::serve(api).run(bind).await;
```

What is this, and how could I fix it please?

**Comment by seanmonstar** [comment]
I believe the way to fix this in your code is to change your extract types to be `(impl Reply,)` instead of just `impl Reply`. That way, they fulfill the `Tuple` trait bounds.

**Comment by rsalmei** [comment]
Awesome, it works!!
Thank you for the fast response! 👍 

But I'm curious, why does it complain only on the latest 1.66 Rust?
I use this code for about three months now...

**Comment by seanmonstar** [comment]
I believe a new lint was added, that was stabilized in Rust 1.66. It's complaining that `impl Reply` doesn't itself mean that the type is `impl Tuple`, which the `trait Filter { type Extract: Tuple; }` requires. This is because the type returned also _was` `(Something, )`, which satisfies the bounds, but `(impl Reply,)` can be called `impl Reply`. There was likely some leakage in the type system, is my guess.
