### ISSUE TITLE
`todos` in example won't compile

### ISSUE THREAD

**Issue by AndyJado** [seanmonstar/warp#1015]
**Version**
git hash: 4e9c4fd
commit msg: v0.3.3

**Platform**
macos13.1

**Description**
todos won't compile, others are fine

**Comment by balrogboogie** [comment]
We're seeing this issue in our application too, it seems that you can no longer return an `impl Filter<Extract = impl warp::Reply, _>` like you used to, since `Filter::Extract` now needs to implement `warp::generic::Tuple` but that isn't exported:

```
error: opaque type `impl warp::Filter + Clone + warp::filter::FilterBase<Extract = impl Reply, Error = Rejection>` does not satisfy its associated type bounds
  --> examples/todos.rs:73:22
   |
73 |     ) -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
  ::: /Users/pwoolcock/Code/warp/src/filter/mod.rs:40:19
   |
40 |     type Extract: Tuple; // + Send;
   |                   ----- this associated type bound is unsatisfied for `impl Reply`
   |
help: add this bound
   |
73 |     ) -> impl Filter<Extract = impl warp::Reply + warp::generic::Tuple, Error = warp::Rejection> + Clone {
   |                                                 ++++++++++++++++++++++
```

**Comment by jxs** [comment]
Hi! Sorry I missed this, and replied directly on https://github.com/seanmonstar/warp/pull/1020, can you try https://github.com/seanmonstar/warp/pull/1020#issuecomment-1419535610 and see if it works?
