### ISSUE TITLE
image type heic isnt recognised

### ISSUE THREAD

**Issue by country-bumpkin-software** [seanmonstar/warp#1018]
**Version**
warp = "0.3.2"
tokio = { version = "1.2", features = ["full"] }

`cargo install cargo-tree`
(see install here: https://github.com/sfackler/cargo-tree)

Then:

`cargo tree | grep warp`

**Platform**
m1 mac

**Description**
I set up a static file server which contains a heic image. When this is requested it has the content-type=application/octet-stream instead of image/heic

I tried this code:

    let assets = warp::path("images")
        .and(warp::fs::dir("images"));

I expected to see this happen: heic files to be image/heic content type

Instead, this happened: application/octet-stream

Is there any way i can specify if the file is .heic return a different content-type?

**Comment by country-bumpkin-software** [comment]
I tried this but it doesnt seem top work or even print:

let assets = warp::path("images")
        .and(warp::fs::dir("images")).map(|reply: warp::filters::fs::File| {
            print!("{:?}", reply);
            if reply.path().ends_with("HEIC_GOOD.heic") {
                println!("1{:?}", reply);
                warp::reply::with_header(reply, "Content-Type", "image/heic").into_response()
            } else {
                reply.into_response()
            }
        });
 That is from the documentation, but it doesnt seem to work?

**Comment by seanmonstar** [comment]
Warp uses the `mime_guess` crate to determine what content-type to send. You could check with that.

**Comment by country-bumpkin-software** [comment]
Thanks sean, no probs, we can close this issue
