### ISSUE TITLE
Remove "multipart" dependency

### ISSUE THREAD

**Issue by willclevine** [seanmonstar/warp#1023]
**Is your feature request related to a problem? Please describe.**
Warp 0.3.3's dependency on `multipart` v0.18.0 now causes a vulnerability advisory error during `cargo deny check`:
```
error[vulnerability]: Race Condition Enabling Link Following and Time-of-check Time-of-use (TOCTOU)
...
    = Announcement: https://github.com/XAMPPRocky/remove_dir_all/commit/7247a8b6ee59fc99bbb69ca6b3ca4bfd8c809ead
    = Solution: Upgrade to >=0.8.0
    = remove_dir_all v0.5.3
      └── tempfile v3.3.0
          └── multipart v0.18.0
              └── warp v0.3.3
```
I'd like `multipart` to be removed as a dependency for Warp.  It appears to not be maintained anymore either: https://github.com/abonander/multipart

**Describe the solution you'd like**
This PR appears to fix the issue.  I'd like someone to approve it, merge it, and release v0.3.4: https://github.com/seanmonstar/warp/pull/846

**Describe alternatives you've considered**
I can try to patch `remove_dir_all` to v0.8.0 in my TOML, but this will remain an issue for other projects using this version of Warp.

**Comment by seanmonstar** [comment]
In most cases, simply running `cargo update -p tempfile` in your project should work.

**Comment by willclevine** [comment]
I could do it with this, but I wouldn't recommend it since I would have had to use "master" instead of a version.  Unfortunately the version of tempfile that gets rid of `remove_dir_all` isn't tagged (3.4.0) https://github.com/Stebalien/tempfile/tags

```
[patch.crates-io]
tempfile = {git = "https://github.com/Stebalien/tempfile", branch = "master"}
```

**Comment by seanmonstar** [comment]
Looks like they just forgot to push the tag to GitHub. The version on https://crates.io/crates/tempfile is 3.4.0.

**Comment by horacimacias** [comment]
thanks! running `cargo update -p tempfile` as suggested worked for me.

**Comment by LegendL3n** [comment]
@willclevine You can instead add this: `tempfile = "3.4.0"` to your dependencies block.

**Comment by letbt** [comment]
`multipart` is incompatible in future。

```
warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4, multipart v0.18.0
note: 
To solve this problem, you can try the following approaches:


- If the issue is not solved by updating the dependencies, a fix has to be
implemented by those dependencies. You can help with that by notifying the
maintainers of this problem (e.g. by creating a bug report) or by proposing a
fix to the maintainers (e.g. by creating a pull request):

  - buf_redux@0.8.4
  - Repository: https://github.com/abonander/buf_redux
  - Detailed warning command: `cargo report future-incompatibilities --id 6 --package buf_redux@0.8.4`

  - multipart@0.18.0
  - Repository: http://github.com/abonander/multipart
  - Detailed warning command: `cargo report future-incompatibilities --id 6 --package multipart@0.18.0`
```

**Comment by Frankonly** [comment]
multipart is archived without future maintenance

**Comment by willclevine** [comment]
@rsalmei Sorry for not posting sooner, but both @LegendL3n and @horacimacias solutions worked for me.  Either worked, you don't need to do both.

**Comment by willclevine** [comment]
@rsalmei you are right! I was overzealous haha.  Reopened
