### ISSUE TITLE
RESTful routes are not correctly handled 

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [seanmonstar/warp#1025]
**Version**
0.3.3

**Platform**
Darwin 21.2.0 arm64

**Description**
I wanna to provide the API like:
```
GET /api/resources // list all resources
POST /api/resources // create a resource
GET /api/resources/:id // retrieve a resource by it's ID
```

I tried this code:

```rust
let show_resource = warp::path!(String)
  .and(warp::get())
  .map(move |id: String| {
    resources::show(id)
  });

let list_resources = warp::get()
  .and(warp::path::end())
  .map(move |_: Value| resources::list()));

let create_resource = warp::post()
  .and(warp::body::content_length_limit(32 * 1024))
  .and(warp::body::json())
  .map(
    move |resource: Resource| {
      resources::create(resource)
    },
  );

warp::path!("api" / "resources").and(show_resource.or(list_resources).or(create_resource))
```

I expected to see this happen: 
the `show_resource` has to match and call `resource::show`.

Instead, this happened:
Warp returns a 404, the `show_resource` is not detected.

Alternative (that works but it's not very clean):

```rust
let show_resource = warp::path!("api" / "resources" / String)
  .and(warp::get())
  .map(move |id: String| {
    resources::show(id)
  });

let list_resources = warp::get()
  .and(warp::path::end())
  .map(move |_: Value| resources::list()));

let create_resource = warp::post()
  .and(warp::body::content_length_limit(32 * 1024))
  .and(warp::body::json())
  .map(
    move |resource: Resource| {
      resources::create(resource)
    },
  );

show_resource.or(warp::path!("api" / "resources").and(list_resources.or(create_resource))
```

**Comment by apiraino** [comment]
If I remember correctly, this is an old issue of the route handling in Warp. I had the same problem and the only workaround is arranging the sequence of routes so that they not "interfere" (just like you suggest), which can get really tricky, especially with many routes.

**Comment by MarcAntoine-Arnaud** [comment]
@apiraino  thank you for your feedback, but it means warp cannot generate compatible RESTful APIs ? ...

**Comment by kaj** [comment]
I think your problem is that the `path!(...)` macro includes an `end()` call.  So another workaround should be to use the path function twice instead of the path macro:

```rs
path("api").and(path("resources").and(show_resource.or(list_resources).or(create_resource))
```

**Comment by MarcAntoine-Arnaud** [comment]
Thanks you, it works !
So I close the issue
