### ISSUE TITLE
Request support for wss

### ISSUE THREAD

**Issue by shijunti19** [seanmonstar/warp#1041]
Is your feature request related to a problem? Please describe.
Yes, we are currently having issues with our webstock functionality due to the lack of support for wss with tsl. We need to be able to secure our webstock connections in order to ensure the safety of our users.

Describe the solution you'd like
We would like to request support for wss with tsl for our webstock functionality. This would allow us to securely connect to our servers and provide a safe experience for our users.

Describe alternatives you've considered
We have considered using other protocols or frameworks that support wss with tsl, but we have determined that it would be too much work to change our current implementation. We believe that adding support for this feature would be the most efficient and effective solution.

**Comment by serprex** [comment]
websockets are supported, are you enabling the feature in `Cargo.toml`?
