### ISSUE TITLE
[feature request] [low prio] Non-Metal fallback option

### ISSUE THREAD

**Issue by stradicat** [seanmonstar/warp#1068]
Hello guys,

would a non-Metal fallback mode be feasible without reworking the whole app?

**Comment by seanmonstar** [comment]
I'm not sure what you mean by metal. Just in case, this is a server framework, there is another project that is a terminal program. Is that what you're looking for?

**Comment by stradicat** [comment]
My mistake. Wrong project, I'm sorry.
