### ISSUE TITLE
Navigation between panes using vim commands

### ISSUE THREAD

**Issue by basola21** [seanmonstar/warp#1084]
I'm always frustrated when I have two panes open side by side and I want to switch between them quickly without needing to use the mouse to click on the pane I want. 

I want there to be a shortcut for example using iterm + tmux + neovim you can customize it to be that when you have multiple tmux windows open you can easily navigate between them using vim navigation as if you are still inside neovim

**Describe alternatives you've considered**
Any kind of of keyboard bindings to move through the open panes

here is what I want as a video 

https://github.com/seanmonstar/warp/assets/63477635/623b52c2-2aa2-44ed-9478-e5f3a5719dc8

here is what is happening in the warp editor

https://github.com/seanmonstar/warp/assets/63477635/899a57d5-29ea-4780-ad80-c8aff6b4de59

I just wanted to point out that I needed to click on pane with the mouse in warp while in iterm I was using the vim navigation this is done through tmux plugin that enables neovim and tmux communicate called christoomey/vim-tmux-navigator

**Comment by seanmonstar** [comment]
I think you're looking for https://www.warp.dev/, the terminal. This repo is for a web server framework.
