### ISSUE TITLE
Chinese input method following error in notebook

### ISSUE THREAD

**Issue by Free-Aaron-Li** [seanmonstar/warp#1096]
**Version**
v0.2024.04.02.08.02.stable_01

**Platform**
Linux aaron-PC 6.6.21-amd64-desktop-hwe #23.01.00.23 SMP PREEMPT_DYNAMIC Mon Mar 18 09:58:09 CST 2024 x86_64 GNU/Linux

**Description**

If I don't choose to enter a title, the following problem occurs.

- Correct follow:

![image](https://github.com/seanmonstar/warp/assets/95997167/fea17093-594c-4d53-8493-08d5e234ef94)

Able to follow correctly from the command line

- Misfollow

![image](https://github.com/seanmonstar/warp/assets/95997167/369533e5-2757-4770-897a-d68d7fcff6ca)

When I choose to write a document in the notebook, the input method still follows the command line

If I'm not clear, I posted a video at the end.

https://github.com/seanmonstar/warp/assets/95997167/cf2e157c-1d49-4488-9b6b-6a55e85390f4

**Comment by Free-Aaron-Li** [comment]
I carefully tested the notebook's input method following, and found that in fact.
In addition to the notebook input title, the text content did not do input method following operations. That's why these problems arise

**Comment by seanmonstar** [comment]
This repo is for a web server framework. Seems you're reporting about the terminal project.
