### ISSUE TITLE
Sending a JSON post with a string or bytes that contain the words <meta> causes a 403

### ISSUE THREAD

**Issue by j-mendez** [seanmonstar/warp#1101]
**Version**

0.3.7

Linux arm64

**Description**

If you create a service with `make_service_fn` and `service_fn` when sending a POST request to the service with a JSON value that contains the string `<meta>` the request fails. No code is ran inside service_fn and is rejected above.

A 403 is returned for the rejection.

Example body:

```json
{
    "return_format": "markdown",
    "data": [
        {
            "html": "<meta>",
            "url": ""
        }
    ]
}
```

Example service:

```rs
    let make_service = make_service_fn(move |socket: &AddrStream| {
        let cache = cache.clone();
        let shared_state = shared_state.clone();

        async move {
            let svc_fn = service_fn(move |request| {
                let cache = cache.clone();
                let shared_state = shared_state.clone();

                async move { 
                   // ... code should fire here but, never does
                }
            });
            Result::<_, Infallible>::Ok(svc_fn)
        }
    });

```

**Comment by seanmonstar** [comment]
Could you include more details? A minimum `fn main()` that triggers this? Because of what you've described so far, I see no reason it should fail. Likely there's more to it.

**Comment by j-mendez** [comment]
> Could you include more details? A minimum `fn main()` that triggers this? Because of what you've described so far, I see no reason it should fail. Likely there's more to it. I realized I posted this in the wrong project and not the hyper github. Feel free to transfer the issue.

```rs
use tokio;
use hyper::{
    server::conn::AddrStream,
    service::{make_service_fn, service_fn},
    Body, Response, Server,
};

  #[tokio::main]
   fn main() {
       let addr = ([0, 0, 0, 0], 3031).into();

    let make_service = make_service_fn(move |socket: &AddrStream| {
        async move {
            let svc_fn = service_fn(move |request| {
                async move { 
                  // private code routes here
                }
            });
            Result::<_, Infallible>::Ok(svc_fn)
        }
    });

    let srv = async {
        let server = Server::bind(&addr).serve(make_service);

        println!("Server started on 127.0.0.1:{port}");
    };
   }
```

The code I have ommited returns `Result<Response<Body>, Infallible> `. It never runs so hiding it from the response.

**Comment by j-mendez** [comment]
> > Could you include more details? A minimum `fn main()` that triggers this? Because of what you've described so far, I see no reason it should fail. Likely there's more to it.
> 
> I realized I posted this in the wrong project and not the hyper github. Feel free to transfer the issue.
> 
> ```rust
> use hyper::{
>     server::conn::AddrStream,
>     service::{make_service_fn, service_fn},
>     Body, Response, Server,
> };
> use tokio;
> 
> #[tokio::main]
> fn main() {
>     let addr = ([0, 0, 0, 0], 3031).into();
> 
>     let make_service = make_service_fn(move |socket: &AddrStream| {
>         async move {
>             let svc_fn = service_fn(move |request| {
>                 async move {
>                     // private code routes here
>                     println!("test");
>                 }
>             });
>             Result::<_, Infallible>::Ok(svc_fn)
>         }
>     });
> 
>     let server = Server::bind(&addr).serve(make_service);
> 
>     println!("Server started on 0.0.0.0:{port}");
>     server.await;
> }
> ```
> 
> The code I have omitted returns `Result<Response<Body>, Infallible> `. It never runs so hiding it from the example. It works locally on my mac. When I deploy to AWS on a linux arm machine it does not work, if I remove the `<meta>` from the body request string the `service_fn` can process correctly.

![example request success](https://github.com/seanmonstar/warp/assets/8095978/55c31591-bad7-4a15-b4c9-1ca08297bcfb)
![example request failure](https://github.com/seanmonstar/warp/assets/8095978/4399a316-9af6-4b9e-b8fb-6bbeb03fcfaf)

I spent a good amount of time re-visiting the logic on my end and could not find anything, eventually put logs out and saw the `service_fn` never gets called. I can try to make a clone repo with a min example of the issue if needed.

**Comment by seanmonstar** [comment]
> When I deploy to AWS

It seems something in your configuration there is the problem. Note that hyper _never_ returns 403 automatically.

**Comment by j-mendez** [comment]
> > When I deploy to AWS
> 
> It seems something in your configuration there is the problem. Note that hyper _never_ returns 403 automatically.

Issue was with WAF - it treats <meta> as a XSS by default. Noticed the request are being blocked. Thanks again for the help!
