### ISSUE TITLE
Websocket example returns 400 bad request

### ISSUE THREAD

**Issue by kennethjeremyau** [seanmonstar/warp#116]
I was able to connect to it when warp was first released, but came back to it recently, updated all my dependencies, and now I get a 400 error on a clean example build.
```
$ wscat -c "ws://127.0.0.1:3030/echo"
error: Unexpected server response: 400
```
Using warp v0.1.6

**Comment by OneSadCookie** [comment]
I'm also experiencing this.

**Comment by osmarks** [comment]
I'm experiencing this too.

**Comment by seanmonstar** [comment]
A bug was introduced with the upgrade to internal typed headers which isn't checking the `Connection` header in a case-insensitive way. The typed headers have been fixed, I'm just looking into adding some tests for this in warp and then will have a release soon after.

**Comment by seanmonstar** [comment]
The [v0.1.7](https://github.com/seanmonstar/warp/releases/tag/v0.1.7) release has this fixed.

**Comment by OneSadCookie** [comment]
thanks for the quick turnaround!
