### ISSUE TITLE
[Beginner question]: How to execute a filter conditionally?

### ISSUE THREAD

**Issue by robertohuertasm** [seanmonstar/warp#121]
Sorry for the noob question but I'm trying to find some information in the docs without much success.

What I'm willing to get is some sort of filter that is executed conditionally depending on an external variable.

I have this piece of code, but I would like to only execute `spa` filter in case the `bool` `is_spa` is true.

```rust
let files = warp::fs::dir(final_path);
let spa = warp::fs::file(spa_index_path);

let routes = files.or(spa);

let address = ([0, 0, 0, 0], final_port);
warp::serve(routes.map(|x| {
      println!("{:?}", x);
      x
}))
.run(address);
```

I've tried many combinations of filters without luck so any help would be really appreciated 😉

**Comment by seanmonstar** [comment]
Does `is_spa` depend on something from a request, or something when you start up the server?

**Comment by robertohuertasm** [comment]
It's just a value set when I start the server.

**Comment by xoac** [comment]
You can create `is_spa` as `Arc<Mutex<bool>>`  and move it cloned to spa filter then in spa filter check if is_spa is `true` or `false` using MutexGuard. 

`Mutex` is general but in your situation [AtomicBool](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicBool.html) can be used.

**Comment by robertohuertasm** [comment]
My problem is that I cannot manage to make work the second part of the problem, the checking of true or false. Once I got this, how can I avoid the spa filter at all? Or send a not found error?

**Comment by robertohuertasm** [comment]
I mean, I've used a map and then depending on `is_spa` value I've tried to return `not found` or the original value but the compiler keeps complaining. Is there a code example explaining something similar? Thanks for your patience 😜

**Comment by robertohuertasm** [comment]
It’s a value set when I start the server.

**Comment by seanmonstar** [comment]
I think part of the inconvenience is related to #3. You can't really do any validation in an `and_then` and return "nothing", which is annoying.

```rust
let is_spa = warp::any(move || is_spa)
    .and_then(|is_spa| {
        if is_spa {
            Ok(IsSpa)
        } else {
            Err(warp::reject::not_found())
        }
    });

let route = is_spa
    .and(warp::fs::file(spa_index_path))
    // map away the worthless value we had to return from and_then
    .map(|IsSpa, file| {
        file
    })
```

**Comment by robertohuertasm** [comment]
Hi @seanmonstar, I tried to take a look at your code but I can't seem to pass any arguments to `any` filter. Maybe you wanted to put this in the `and_then` filter?  On top of that, what is `IsSpa` in your example? Thanks again for your help!

**Comment by robertohuertasm** [comment]
I made it work with a `map` after the `any`. I guess that one was a typo.

So finally:

```rust
let files = warp::fs::dir(final_path);
let spa = warp::any()
    .map(move || is_spa)
    .and_then(|is_spa| {
        if is_spa {
            Ok(is_spa)
        } else {
            Err(warp::reject::not_found())
        }
    })
    .and(warp::fs::file(spa_index_path))
    .map(|_, file| file);

    let routes = files.or(spa);

    let address = ([0, 0, 0, 0], final_port);
    warp::serve(routes.map(|file| {
        println!("{:?}", file);
        file
    }))
    .run(address);
```

A million thanks @seanmonstar for your help!

**Comment by robertohuertasm** [comment]
Just for the sake of completeness in case anyone else is looking for the same information. Indeed, we don't need the `map` after the `any` filter. Just moving the closure will allow us to capture `is_spa`:

```rust
let files = warp::fs::dir(final_path);
let spa = warp::any()
    .and_then(move || {
        if is_spa {
            Ok(is_spa)
        } else {
            Err(warp::reject::not_found())
        }
    })
    .and(warp::fs::file(spa_index_path))
    .map(|_, file| file);

    let routes = files.or(spa);

    let address = ([0, 0, 0, 0], final_port);
    warp::serve(routes.map(|file| {
        println!("{:?}", file);
        file
    }))
    .run(address);
```
