### ISSUE TITLE
Restrictions on custom filters and route-guards

### ISSUE THREAD

**Issue by cynecx** [seanmonstar/warp#122]
I am currently trying to implement a simple route guard which restricts a specific path based on a header value. But I am not sure if this is possible right now with the restrictions around the api (Filter/FilterBase/unit?).

What I am basically trying to implement is a more dynamic version of `warp::filters::header::exact` since both params have static lifetime.

```rust
let hostname = warp::header::header::<String>("Host")
        .and_then(move |hostname| {
            if hostname == ctx_cln.hostname {
                Ok(())
            } else {
                Err(warp::reject())
            }
        })
        .and(docs);
```

But then we have the issue that the `Extract` type is something like `((), std::string::String)` and therefore does not implement `ReplySealed`.

However, it seems that the workaround for that is the `unit` method, which is not public currently (And since `FilterBase` is also private, I see no way to actually achieve this at the current state).

https://github.com/seanmonstar/warp/blob/8f5213e3f17758d873cdf865107eca241da8156a/src/filters/body.rs#L50-L65

**Comment by seanmonstar** [comment]
Yea, this same issue was just mentioned in #121. The annoying part is #3. I have not yet thought of a nice way to fix it, the `unit()` method feels like a bad band-aid, hence why it's not public.

You could map away the extra unit, for now:

```rust
warp::header::header::<String>("Host")
        .and_then(move |hostname| {
            if hostname == ctx_cln.hostname {
                Ok(())
            } else {
                Err(warp::reject())
            }
        })
        .and(docs)
        .map(|_, reply| reply);
```

**Comment by cynecx** [comment]
@seanmonstar Oh yes, I haven't thought of that :D. I guess that should do as a temporary solution. Thank you!
