### ISSUE TITLE
Some APIs should have been public

### ISSUE THREAD

**Issue by katyo** [seanmonstar/warp#124]
I would like to write generic `bind` method (which accepts both tcp and unix socket address) so I need `IntoWarpService`, `WarpService` and `Reject` to be public.
I trying to implement something like so:

```rust
impl ListenAddr {
    pub fn bind<S>(&self, server: Server<S>) -> impl Future<Item = (), Error = ()> + 'static
        where
            S: IntoWarpService + 'static,
    <<S::Service as WarpService>::Reply as Future>::Item: Reply + Send,
    <<S::Service as WarpService>::Reply as Future>::Error: Reject + Send, 
...
```

**Comment by otavio** [comment]
It would be great, indeed. I'd be a user of the unix socket binding if it exists :-)

**Comment by seanmonstar** [comment]
The `IntoWarpService` and `WarpService` traits are going away, and `Filter`s will just be able to be converted into a `tower::Service`. See #56.
