### ISSUE TITLE
How to unroll tuple into arguments

### ISSUE THREAD

**Issue by katyo** [seanmonstar/warp#125]
Say I have a filter which returns tuple:

```rust
Filter<Extract = ((SessionData, UserData), ), Error = Rejection>
```

I don't know how I can convert it into something like so:

```rust
Filter<Extract = (SessionData, UserData), Error = Rejection>
```

May be this issue related to #3

**Comment by seanmonstar** [comment]
Yep, seems like the same issue. So far, I've assumed that custom filters would return named structs instead of tuples.

Possibly a more general solution to #3 is to provide some method to "unroll" or "flatten" one layer, if `Extract=(T,)` where `T: Tuple`...
