### ISSUE TITLE
Docs touch-up for Rejections

### ISSUE THREAD

**Issue by seanmonstar** [seanmonstar/warp#126]
With the changes to the Rejection system (#115), the docs could use some improvements.

- The docs for `warp::reject::custom` should link to `Filter::recover`.
- The docs for `warp::Rejection` should link to the `warp::reject` module documentation.
- The `warp::reject` module docs should expand on how to recover from rejections.

**Comment by boxdot** [comment]
Looks like this was already done in the commit b262f934bf1c263ea1c42219f2b8e3121715748d.

**Comment by jxs** [comment]
hum, after docs for `warp::reject::custom` link to `Filter::recover`,
and docs for `warp::Rejection` link to `warp::reject` module documentation, 
but `warp::reject` module docs doesn't yet refer to `Filter::recover` or the errors example, should this be addressed @seanmonstar ?

**Comment by calvinbrown085** [comment]
I can grab 
> The warp::reject module docs should expand on how to recover from rejections.

**Comment by calvinbrown085** [comment]
Is there a specific example on what kind of rejection you'd want to recover from?

**Comment by jxs** [comment]
fixed with #876
