### ISSUE TITLE
Example to add filters conditionally

### ISSUE THREAD

**Issue by D4nte** [seanmonstar/warp#131]
I have been trying to add filters conditionally but did not find a clean way to do so.

Let's say my application support 2 kinds of routes: `/A` and `/B`.
When starting the application, depending on the configuration I may want to:
* register both routes
* register one route and let other return 404.

As I am using `or` to compose the routes I have not find a way to conditionally compose the routes.

Let me know if you need more details.

**Comment by seanmonstar** [comment]
See #121 for another discussion on this, but basically, you could insert an `and_then` step before the actual filter, which can reject if configured to do so. For example:

```rust
fn enable(is_enabled: bool) -> impl Filter<Extract = (), Error = Rejection> + Copy {
    warp::any()
        .and_then(move || {
            if is_enabled {
                Ok(())
            } else {
                // or warp::reject::custom if something besides 404
                Err(warp::reject::not_found())
            }
        })
        // this weirdo deals with the Ok(())
        .untuple_one()
}
```

And then, for any configurable routes:

```rust
let foo = enabled(config.is_foo)
    .and(foo());
let bar = enabled(config.is_bar)
    .and(bar());

let routes = foo.or(bar);
```

**Comment by Oliboy50** [comment]
@seanmonstar your last code example does not seem to work with `warp = "0.3.1"`

```shell
.and(
^^^ the trait `warp::generic::Tuple` is not implemented for `impl Reply`
```
