### ISSUE TITLE
Support of Server-Sent Events (SSE)

### ISSUE THREAD

**Issue by katyo** [seanmonstar/warp#137]
On a par with Web-Sockets the [Server-Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) (SSE) is a essential part of web-stack. It is simplex (server-to-client) channel which doesn't require to changing protocol and works on HTTP(S).
But SSE reply support yet missing in warp. I have some ideas how to implement it, so I would like try to do it at near time.

**Comment by seanmonstar** [comment]
I believe SSE can be handled already, simply send the correct `content-type`, and then use a streaming body to send events as they are ready.

**Comment by seanmonstar** [comment]
This was merged in #138 🎉
