### ISSUE TITLE
CORS not responding to OPTION request

### ISSUE THREAD

**Issue by theduke** [seanmonstar/warp#151]
Just tried out the new cors filter with `0.1.10`:

```rust
...
...

    let cors = warp::cors()
        .allow_origin("https://hyper.rs")
        .allow_methods(vec!["GET", "POST", "DELETE"]);

some_route
  .or(other_route)
  .with(log)
  .with(cors)
```

OPTION requests do not contain the `access-control-allow-*` headers for me.

**Comment by theduke** [comment]
I'll post a full repo later tonight or tomorrow.

I do have an `any` catchall route in the mix, maybe that prevents the cors filter from applying?

**Comment by bluetech** [comment]
Just making sure, you tried `OPTIONS`, not `OPTION` as in the description?

**Comment by seanmonstar** [comment]
Closing as inactive. If you have more details, we can re-open!
