### ISSUE TITLE
Auth middleware

### ISSUE THREAD

**Issue by droundy** [seanmonstar/warp#154]
Is there any plan or design for implementing a filter to handle authentication in any manner? Or even a recommendation for how to achieve authentication?

**Comment by algermissen** [comment]
I am working on an auth filter, but keep being distracted.

See 
https://github.com/seanmonstar/warp/issues/62

So I think you can close this and take any input / requests you have to issues 62.

**Comment by seanmonstar** [comment]
I'd love to add auth filters, take a look at #62. Closing as a duplicate.
