### ISSUE TITLE
Fix ws socket to thread

### ISSUE THREAD

**Issue by rainhead** [seanmonstar/warp#155]
Hi, and thanks for making this library. So far, it offers the right abstractions for me, and nothing more.

`warp::ws::Ws2::on_upgrade` expects its argument to return a Future that is Send. I was hoping for my handler to own its own database connection. Since websockets are long lived, and often implemented to improve responsiveness, I imagine other users of warp want to do something similar. I can use a connection pool, but I'd prefer to avoid it.

Is there any way to run warp on a single thread, or at least to ensure that a given websocket is always handled on the same thread? Can I spawn a thread `on_upgrade` and steal the socket?

In any case, the documentation could give a sentence or two about warp's threading model.

**Comment by jxs** [comment]
with warp `0.2.x` this is possible using warp's `Server` method's that return a `Future` and running them on `tokio`'s [`basic_scheduler`](https://docs.rs/tokio/0.2.21/tokio/runtime/index.html#basic-scheduler)
