### ISSUE TITLE
headers-ext → headers

### ISSUE THREAD

**Issue by ignatenkobrain** [seanmonstar/warp#160]
I think headers-ext is old and been replaced by headers.

I'm now packaging warp for Fedora and would be great if it could be ported to that. Thank you!

**Comment by hgzimmerman** [comment]
https://github.com/seanmonstar/warp/commit/8d892ddbd19518f59a396eb7c43ca33045b056aa

**Comment by seanmonstar** [comment]
Yup, done in master!
