### ISSUE TITLE
byte index 1 is out of bounds of ``

### ISSUE THREAD

**Issue by Kerollmops** [seanmonstar/warp#161]
Hi! I was using warp 0.1.10 and a panic appeared that does not seems to by on my side, so here is the backtrace:

[c01daaf278c04bcf8384f3bde99d35b8-symbolicated.txt](https://github.com/seanmonstar/warp/files/2800132/c01daaf278c04bcf8384f3bde99d35b8-symbolicated.txt)

For some context the server is ping on the "/" route and always respond with a `405` every 10-20 secondes or so.

```
x.x.x.x:yyyy "GET / HTTP/1.1" 405 "-" "-" 20.3µs
```

**Comment by seanmonstar** [comment]
Yep, looks like a bug in warp! Do you happen to have any more details about what `warp::path` filters are used?

**Comment by Kerollmops** [comment]
Yes, nothing really interresting:
![capture d ecran 2019-01-28 a 21 04 20](https://user-images.githubusercontent.com/3610253/51863066-5dcb6280-2340-11e9-9309-6c5b4bc6f28e.png)

**Comment by seanmonstar** [comment]
This is seeming fairly strange... Is it possible the request is a `CONNECT host:port`?

**Comment by seanmonstar** [comment]
That's the only way I could trigger that panic. I've patched that on master, if you want to see if that fixes your problem.

**Comment by Kerollmops** [comment]
I am not able to reproduce the crash by triggering it using the `CONNECT` http method on the warp non-patched version. It is possible due to a `CONNECT` request, our server is under a load-balancer that we can not control.

**Comment by seanmonstar** [comment]
Well, I've published v0.1.12 with said fix. That said, it shouldn't affect *only* `CONNECT` requests, but any instance where the path doesn't start with `/`.

**Comment by seanmonstar** [comment]
I'm going to close as hopefully fixed. If it still occurs after upgrading, we can re-open!
