### ISSUE TITLE
get outside of filter (or allow +=ing into ext)

### ISSUE THREAD

**Issue by remexre** [seanmonstar/warp#165]
I'm trying to accumulate into a request extension; it'd be convenient to have either a non-filter way to get the current value of a request extension, or a way to "add into" request extensions that are... `AddAssign`? `Extend`? `frunk::Semigroup`?

**Comment by seanmonstar** [comment]
I don't quite follow, mind expanding?

**Comment by remexre** [comment]
Basically, either of:

```rust
fn get2<T: 'static + Clone + Send + Sync>() -> Option<T> {
    ::route::with(|route| route.extensions_mut().get(val).cloned())
}

// or

fn semigroup_append<T: 'static + Semigroup + Send + Sync>(t: T) {
    ::route::with(move |route| {
        let mut exts = route.extensions_mut();
        let val = exts.get::<T>()
            .map(|prev| prev.combine(&t))
            .unwrap_or(t);
        exts.insert(val);
    });
}
```

**Comment by jxs** [comment]
this is now achievable with the [`Filter` to `Service` conversion](https://docs.rs/warp/0.2/warp/fn.service.html#example).
Also see https://github.com/seanmonstar/warp/issues/16#issuecomment-573959674
