### ISSUE TITLE
Support forms with multipart/form-data

### ISSUE THREAD

**Issue by droundy** [seanmonstar/warp#172]
It would be ideal for `body` to support `multipart/form-data` encoded data, but at least to have done way to access this data seems important. I don't know any other way to handle HTML file input, is it seems ridiculous to URL encode an entire file.

**Comment by seanmonstar** [comment]
Yea, I don't recommend urlencoding the file. See #40 for the issue tracking adding multipart filters. If you have some ideas of a nice API to allow for collecting parts safely (gotta be careful we don't try to buffer an absurdly large upload), I'd love to hear your thoughts in that issue.

-----

If you'd like to accept file uploads *right now* before we figure out an API, here's what I've done: in a case where I controlled the upload client as well, I had the client send the binary data as-is directly to the endpoint. On the server, you could use `warp::body` filters to get the raw stream.

**Comment by droundy** [comment]
I'm not sure that I'll be much help with the API, as I'm almost entirely unfamiliar with `multipart/form-data`, and have never used it.

I know this is off-topic, but I'm struggling to figure out how to take your advice.  On the rust/warp side of things it's pretty easy (and thanks for the suggestion), but I can't see what is going wrong with my HTML/javascript to post a file.  The HTML looks like
```

        <form class="hint">
          <label for="icon">Image file for icon</label>
          <input type="file" name="icon" accept="image/*"
                 onchange="handleIcon(this.files)">
        </form>
```
and the javascript is
```
 function handleIcon(files) {
     for (let i = 0; i < files.length; i++) {
         const file = files[i];

         const reader = new FileReader();
         const xhr = new XMLHttpRequest();

         xhr.open("POST", "/figure/[% self.id %]/" + file.name);
         xhr.overrideMimeType('application/octet-stream');
         reader.onload = function(evt) {
             xhr.send(evt.target.result);
         };
         reader.readAsBinaryString(file);
     }
 }
```
I'm seeing image files corrupted with extra bytes before and after the raw content.  Any suggestions what's going on or how to fix it?

**Comment by seanmonstar** [comment]
I'm not certain, but it could be that `readAsBinaryString` is converting the data to UCS-2, as that is how JS `String`s are encoded.

Perhaps `readAsArrayBuffer` works better? https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsArrayBuffer

**Comment by droundy** [comment]
Thanks for the hint. As it turns out I could just pass the file directly to `xhr.send` it's working perfectly now!

Regarding possible API for multipart/form-data, why not support this with the same API as urlencoded forms? This wouldn't be the most efficient for large files, but would be very easy to use. I could imagine a memory efficient API which takes a directory path and sticks any files in there before giving the "normal" days to a function as arguments?

**Comment by seanmonstar** [comment]
> I could imagine a memory efficient API which takes a directory path and sticks any files in there

That's certainly a popular way in some frameworks, and we could consider doing that here!

I'm going to close this since it's now working, we can discuss API ideas in #40.

**Comment by kindlychung** [comment]
> If you'd like to accept file uploads _right now_ before we figure out an API, here's what I've done: in a case where I controlled the upload client as well, I had the client send the binary data as-is directly to the endpoint. On the server, you could use `warp::body` filters to get the raw stream.

Is there an example of this? I'm very much interested. Thanks.
