### ISSUE TITLE
Any plans to support SNI directly?

### ISSUE THREAD

**Issue by jeffcato** [seanmonstar/warp#176]
Asking for a friend.  😉

**Comment by seanmonstar** [comment]
Seems reasonable! There's support in rustls, so we'd just need to come up with a nice API in warp.

**Comment by jeffcato** [comment]
Ah excellent - I'm a rust noob ATM so I'm probably not your man for this.  We have a nodejs server project I was thinking about rewriting in Rust when my training wheels are off.  I'm leaning heavily toward warp for that, just need SNI support.  Thanks.
