### ISSUE TITLE
Is there a way to turn a Map function that returns a Result into a Rejection?

### ISSUE THREAD

**Issue by nerdrew** [seanmonstar/warp#178]
I'd like to do something like:

```rust
warp::post2()
    .and(warp::path("boom"))
    .and(warp::header::<String>("content-encoding").or(warp::any().map(|| String::new())).unify())
    .and(concat())
    .map(decompress) // fn decompress(e: String, mut b: FullBody) -> Result<Vec<u8>, Error> { }
    // I asssume I need something here...
    .map(|buf: Vec<u8>| b.into())
```

And then have the request get rejected if decompress returns an `Err`. How can I do that?

**Comment by seanmonstar** [comment]
`map` is for conversions that cannot fail. Use `and_then` if you want to be able to return an error.

**Comment by nerdrew** [comment]
Derp. I don't know what I was doing wrong. I think I was missing a `map_err` to convert my `failure::Error` into a `Rejection`. Thanks!

**Comment by nerdrew** [comment]
On a related note: could `Rejection` implement `From<std::error:Error>`? It seems like that would simplify some of my code. As is, I have a wrapper function around my real `decompress` function so I can use `?` in my real decompress and early return my decompress errors, and then the wrapper converts those into a `Rejection`.

**Comment by nerdrew** [comment]
I think I'd also be able to simplify this:

```rust
.and_then(|proto_bytes: Vec<u8>| proto_bytes.try_into().map_err(|e| warp::reject::custom(failure::Error::from(e).compat())))
```

into

```rust
.and_then(|proto_bytes: Vec<u8>| Ok(proto_bytes.try_into()?))
```
