### ISSUE TITLE
[Question] How to deal with relative links when serving a single file

### ISSUE THREAD

**Issue by efugier** [seanmonstar/warp#181]
Hi !
Here's my issue:
* I have two files `A.html` and `A.js` which is required for `A.html` to function. They both are in the same folder.
* I want a short route to access these files.

So I went with
```rust
let a = path!("a").and(warp::fs::file("./public/a/a.html"));
```
But this will prevent `A.html` from loading `A.js`.

So y question is: **how can I attribute a specific route to a file while allowing it to reach out for other files ?** 

Note that in my case, the whole public directory is made discoverable by a `let static_files = warp::fs::dir("./public/");`.

Thanks in advance for any insight :)

**Comment by seanmonstar** [comment]
I'm not sure I yet see what the issue is. You want `/a` to return `A.html`, and ... `/<what?>` to return the `A.js`?

**Comment by efugier** [comment]
Sorry for not being clear enough, I just meant that in  `A.html` there is a relative link to necessary file:
```html
<script type="text/javascript" src="A.js"></script>
```
Which doesn't work when the `A.html` is served trough `warp::fs::file` but does work when `A.html` is  requested in a `warp::fs::dir` through its path.

Like: 
- `/a` -> call to the script file will not work (access through `file`)
- `/some/too/long/path/A.html` -> call to the script file will work (access through `dir`)

**Comment by seanmonstar** [comment]
Ohhh, I see now.

Would you want it to be accessible at `/A.js`? Or have the HTML altered to include the longer path?

**Comment by efugier** [comment]
Well I'm afraid I'a not sure about what I want...
I guess I'd expect the relative path to be the actual one regardless of how it is served but I'm not sure about the implications and if makes sens as I'm not that savvy in web development !

**Comment by seanmonstar** [comment]
The browser will resolve *relative* URLs (ones that don't start with a `/`) compared to the URL of the HTML document. So, if the document is served at `/a`, it will resolve `A.js` as `/A.js`. If it is at `/some/sub/a`, its resolved to `/some/sub/A.js`.

So, your choices are either:

- Provide a route for `/A.js`
- Change the HTML to include an absolute (starts with a `/`) URL to the javascript file, thus working no matter that the URL of the document was.

**Comment by efugier** [comment]
Yeah I think I'll go with the full path as a single utility file doesn't seem worthy of a new filter.
Thanks for your time and the great insights, I really appreciate it.

**Comment by seanmonstar** [comment]
Cheers!
