### ISSUE TITLE
[question] Subdomain support?

### ISSUE THREAD

**Issue by codesections** [seanmonstar/warp#182]
Thanks very much for `warp`—I haven't yet spent a ton of time with it, but my first impression is very positive.

I have a question, though: is there any support for subdomains?  For example, is there a way to serve a particular response at `www.example.com` and a different response at `blog.example.com`?  If there isn't anything built in, do you have any suggestions for how to implement this?

(Sorry if I'm missing something obvious—I searched for related string in the github repo and the docs and didn't find anything, but I could well be missing it.)

**Comment by seanmonstar** [comment]
You should be able to make use of the `Host` header, with something like this:

```rust
let www = warp::headers::exact("host", "www.example.com")
    .and(build_www());
let blog = warp::headers::exact("host", "blog.example.com")
    .and(build_blog())

let apps = www.or(blog);
```

**Comment by codesections** [comment]
Thanks!  Would you be open to an `examples` PR documenting that?  It seems like a decently common use case, and it probably would have taken me quite a while to figure out that I needed to check the headers.

**Comment by mochamadsatria** [comment]
I'm new to warp, but because my project use subdomain quite often too. I decided to create a public package for it, it is based on Koa.Js subdomain parsing method that return array/vector. If you're interested, you can check it here: [warp_subdomain](https://crates.io/crates/warp_subdomain).
