### ISSUE TITLE
Filtering by Address ?

### ISSUE THREAD

**Issue by 0xpr03** [seanmonstar/warp#184]
Hi,
I'm trying to filter requests by their `SocketAddr` so that only a specific IP can connect.
I know that there is `addr::remote()` but I'd like to already "abort" earlier, like with `content_length_limit`.
Is there already something like this or am I missing something ?

**Comment by 0xpr03** [comment]
Ok the solution is actually pretty easy and can be find by exploring filters a little more  😅 
```rust
.and(warp::addr::remote().and_then(|addr: Option<SocketAddr>|{
    if let Some(v) = addr {
        if v == backend.addr {
            Ok(())
        }
    }
    Err(warp::reject::custom())
}))
```

But reading #64 I'm not sure if doing a reject is even correct or what I'd pass to it.

**Comment by 0xpr03** [comment]
So if I understand this right there is no answer to this currently ?

**Comment by seanmonstar** [comment]
Oh sorry, I didn't notice the secondary question, just assumed you'd figured out the issue.

You can pass a custom rejection, being of any type you like, and then later, you can use a `recover` filter to customize the HTTP response sent. For an example, look here: https://github.com/seanmonstar/warp/blob/master/examples/errors.rs

**Comment by 0xpr03** [comment]
I wasn't sure because I don't really intend to recover and in #64 this approach was questioned for error responses

**Comment by seanmonstar** [comment]
Recover is necessary for any custom rejection, since warp doesn't know what sort of error message to send to the client. Without recover, it will send a `500 Internal Server Error` response. You would use recover like this:

```rust
if let Some(cause) = rejection.find_cause::<BadRemote>() {
    let res = http::Response::builder()
        .status(StatusCode::FORBIDDEN)
        .body("bad bad bad")
        .unwrap();
    Ok(res)
}
```

Your other option is use `warp::reject::not_found()`, but that's just a 404, which doesn't give the right message.
