### ISSUE TITLE
Is there a better way to mark an operation as `blocking`?

### ISSUE THREAD

**Issue by nerdrew** [seanmonstar/warp#185]
I currently have:

```rust
let proto = warp::any()
    .and(warp::header::exact_ignore_case(
        "content-type",
        "application/x-protobuf",
    ))
    .and(warp::header::optional::<String>("content-encoding"))
    .and(concat())
    .and_then(decompress);

warp::post2()
    .and(
        warp::path("save")
            .and(proto.clone())
            .and_then(|buf: Vec<u8>| {
                buf.try_into().map_err(|e| warp::reject::custom(failure::Error::from(e).compat()))
            })
            .map(Arc::new)
            .and(saver)
            .and_then(|save_request: Arc<SaveRequestRental>, saver: Arc<Saver>| {
                futures::future::poll_fn(move || {
                    try_ready!(tokio_threadpool::blocking(|| save(save_request.clone(), saver.clone())))
                        .map(futures::Async::Ready)
                })
            }),
    )
```

It works, but it seems like there's a lot of boilerplate there. Also seems sub-optimal that I have to `Arc` my argument...

**Comment by seanmonstar** [comment]
We've mentioned in passing before that it would be nice to make it easier to wrap something in `blocking`... cc @carllerche

I wouldn't expect you to have to put the argument in an `Arc`, however. What if you don't?

**Comment by carllerche** [comment]
Yes, I agree. Doing so is blocked on a generalized blocking solution. Exploration has started here: https://github.com/tokio-rs/tokio/pull/954

**Comment by nerdrew** [comment]
Oh, the `Arc::new` is b/c of my own type. It isn't clone-able. I guess I meant to say "it seems sub-optimal that the args need to move". In my case I need the `Arc` to make the arg clone-able.

**Comment by hwchen** [comment]
I'm not sure if there's another better place to ask, but was curious about the status of this issue. It looks like the link about exploration ended with two closed PRs and an old open issue. Unfortunately, I'm not familiar enough with tokio and futures to understand what's blocking blocking :)

**Comment by jxs** [comment]
with wrap `0.2.x` this is possible using `tokio`'s [`spawn_blocking`](https://docs.rs/tokio/0.2.21/tokio/task/fn.spawn_blocking.html#examples)
