### ISSUE TITLE
How to set expires header?

### ISSUE THREAD

**Issue by kaj** [seanmonstar/warp#187]
I'm looking for a good way to set an expires header in a reply created in a warp request handler.

This may be a very simple question, but I have tried a bunch of approaches and not found any I like.  So far, I've mainly just used chrono to calculate and format a date, and use the `header` method of `Response::builder`.

https://github.com/kaj/fanrs/blob/75c29e39dbdb1a36e8535f872b0042f1dd67f72a/src/server/mod.rs#L159-L163

But that requires chrono as an extra dependency, while warp already formats the `Date` header just fine.  I have found that I can create a typed expires header like so:

```rust
use headers::Expires;
use std::time::{Duration, SystemTime};
let expires = SystemTime::now() + Duration::from_secs(180 * 24 * 60 * 60);
let expires = Expires::from(expires)
```
But that `expires` value is one value, not the `HeaderName`, `HeaderValue` pair that the request builder wants, and the actual value of `expires` is a `HttpDate` that is internal to the package `headers`, so I can't just use that.

Is there a nice way to combine the `expires` value with a `warp::http::Response` object, or any other nice way to set an expires header, preferably using only warp (and modules reexported by warp)?

**Comment by seanmonstar** [comment]
I've been meaning to expose the `headers` crate directly, but meaning to update its dependency on `mime` first...

However, nothing stops you from having your own dependency! You'd just import [`headers::HeaderMapExt`](https://docs.rs/headers/0.2.*/headers/trait.HeaderMapExt.html), and you can set the typed header on the response.

```rust
use headers::HeaderMapExt;

let mut res = Response::new(body);
res.headers_mut().typed_insert(expires);
```
