### ISSUE TITLE
Is there any way to return two different types of Future from and_then?

### ISSUE THREAD

**Issue by anderspitman** [seanmonstar/warp#194]
Been banging my head against this for a while. I feel like I'm close to understanding the type system well enough to make it work but it keeps slipping away from me. I have an `and_then` that's essentially trying to accomplish the following:

```rust
let data: Arc<Mutex<HashMap<String, Data>>> = Arc::new(Mutex::new(HashMap::new()));
...
and_then(|id: String| {
    match data.lock().unwrap().get(&id) {
        Some(data) => {
            // return first type of future       
        },
        None => {
            // return second type of future
        }
    }
})
```

I know this looks like it should be trivial to just make the futures be the same type, but in my actual code the first type is a futures::sync::oneshot::Receiver that's waiting on an asynchronous result, and is returned from a function. The second type can be just a simple 404 rejection because the request was for an invalid data holder. Any suggestions?

**Comment by remexre** [comment]
You probably want [Either](https://docs.rs/futures/0.1.25/futures/future/enum.Either.html).

**Comment by seanmonstar** [comment]
The compiler requires a function to always return the same type, so it knows how big in memory it will be. To return *different* futures in the same function (or closure), you can either: a) wrap them in `futures::future::Either`, or b) convert them into dynamic trait objects, `Box<dyn Future<...>>`.

**Comment by anderspitman** [comment]
Well shoot, I was not expecting a solution that quickly! I've heard of Either but didn't realize it was built into futures directly. It did indeed solve the problem. Thank you!

@seanmonstar so it's possible to specify in the closure that I want it to return a trait object? Would I put the `Box<dyn Future<...>>` after the closure parameters, and then just box the returns, like this?

```rust
|id: String| -> Box<dyn Future<...>> {
    Box::new(fut1)
}
```

**Comment by anderspitman** [comment]
Also is there a shorthand for the futures types, or do I have to figure them all out exactly?
