### ISSUE TITLE
Expose more from log::Info

### ISSUE THREAD

**Issue by bedax** [seanmonstar/warp#197]
Hello, first off, thanks for this pretty incredible crate. I'm adding logging and I want to write the logs in json so they can be more easily parsed later. For this I'm using `warp::filters::log::custom`, but the info object that takes exposes very little information compared to what `warp::log` has access to. It would be very nice to have access to `info.route` and `info.start`, or perhaps even better if everything `warp::log` writes was available as methods, like `info.remote_addr()`, `info.user_agent()`, etc. I'm happy to submit a PR if you agree.

**Comment by seanmonstar** [comment]
I agree! I think I even left a TODO that the info type should have more methods... Are you interested in making a PR with that?

**Comment by bedax** [comment]
Yeah, good stuff, I'll get on that
