### ISSUE TITLE
How to catch unhandled errors?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [seanmonstar/warp#200]
I see there's a `recover` method, but it appears to require that I know the type of the error, while in this case I want to handle every error that would return a 500.  Is that possible?

**Comment by seanmonstar** [comment]
You can check the rejection for certain causes, and then if none are what you are looking for, you can handle that last catch-all case.

**Comment by vpzomtrrfrt** [comment]
What I ended up with is this:
```
                    .recover(|err: warp::reject::Rejection| -> Result<_, _> {
                        let status = err.status();
                        if status.is_server_error() {
                            eprintln!("server error! {:?}", err);
                            return Ok(
                                http::Response::builder()
                                .status(http::StatusCode::INTERNAL_SERVER_ERROR)
                                .body("Internal Server Error")
                            );
                        }
                        Err(err)
                    })
```

Is that the best approach?

**Comment by hgzimmerman** [comment]
What you have is good, but it only handles one case of error.

Take a look at using something like  `if let Some(&err) = err.find_cause::<MyCustomError>() {...}`. This allows you to recover the specific error variant if you rejected them earlier. You can do that for as many different Error types you know you reject elsewhere in your service. It wouldn't hurt to take a look at the [errors example](https://github.com/seanmonstar/warp/blob/master/examples/errors.rs) to get a more complete understanding.
