### ISSUE TITLE
Feature request: Add warp::reply::js() similar to warp::reply::html()?

### ISSUE THREAD

**Issue by nbigaouette** [seanmonstar/warp#202]
With the function `warp::reply::html()` I can reply with the content of a `String` with content type `"text/html; charset=utf-8"`. I use this to include my (small) html content directly in the binary for maximal portability.

Unfortunately, I cannot do the same for javascript files since there is no `warp::reply::js()` (or similar) which would set the content type to `text/javascript`. If I simply use `warp::path("lib.min.js").map(|| JS_CONTENT)` the content is served with `text/plain` and Firefox complains with an invalid MIME type.

As such, I need to use `warp::fs::file()` instead with a path and must make sure that paths are matching.

Could it be possible to have `warp::reply::js()` with a proper content type?

Thanks!

**Comment by nbigaouette** [comment]
Also, css files would be needed too...

I guess a function could be provided which would allow controlling the content type?

**Comment by seanmonstar** [comment]
To get it working immediately, you can use [`with_header`](https://docs.rs/warp/0.1.*/warp/reply/fn.with_header.html)

```rust
warp::path("lib.min.js").map(|| warp::reply::with_header(JS_CONTENT, "content-type", "text/javascript"))
```

**Comment by nbigaouette** [comment]
Great thanks! This works as expected ;)
