### ISSUE TITLE
Confusing missing documentation for beginners

### ISSUE THREAD

**Issue by NeoLegends** [seanmonstar/warp#207]
Just a little heads up. I'm just starting with `warp` today, and these items missing from the docs was a little confusing for me at first:

https://github.com/seanmonstar/warp/blob/4a1c67c4ca0a22e263dcf2d94ee64a36a4682e57/src/lib.rs#L127-L132

At first I was thinking that maybe the usage of warp, as explained in the examples, has been deprecated and there is now a different blessed way to use the filters, and I actually downloaded and compiled all the examples before I noticed that comment and that the filters were simply hidden from the docs.

Maybe you'd want to put them back into the docs, so that, while being verbose, it is nice and clear for everybody.

**Comment by seanmonstar** [comment]
It's hard for me to decide. I've seen some people say just as you have, that them missing from the docs homepage was confusing. Though, there is also cases of other crates hiding "convenient" re-exports from the doc homepage, to provide a clearer organization. An example is how there are multiple things in `std::prelude::v1`, but they aren't shown on the homepage of libstd.

Would it help to call out somewhere that they *are* re-exported, just hidden?

**Comment by NeoLegends** [comment]
> Would it help to call out somewhere that they are re-exported, just hidden?

This would help tremendously.

**Comment by NeoLegends** [comment]
I've got another idea though. I think star-exports aren't "expanded" in the docs. So if you created a prelude module and star-exported that instead, it should work fine and shouldn't be too verbose.

**Comment by seanmonstar** [comment]
On the [`warp::filters` docpage](https://docs.rs/warp/0.1.15/warp/filters/index.html), it has this message:

>  Most of these are available at more convenient paths.
