### ISSUE TITLE
mechanism for statically generating site content?

### ISSUE THREAD

**Issue by droundy** [seanmonstar/warp#211]
This probably seems like a bit of a poor fit, but I've got a dynamically generated site written with warp, and want to create a static copy that can be mirrored easily.  Obviously, it would be lacking in edit abilities, for instance.

I could certainly do this with no help from warp (e.g. by simply downloading all files from localhost), but given that I've already told warp about all the possible paths, it would be lovely if I didn't have to do that.  And sadly, when mirrored the base path will change, so I'd either have to switch to all relative paths (a pain) or I'd have to manually enumerate all possible paths that I may care about.

I wonder whether each `Filter` (or some subset of `Filter`s?) might be able to enumerate the possible sets of paths, compute the content for each path, and then save that content to a file with the path as its name (and some prefix).

Is this too niche?

**Comment by seanmonstar** [comment]
The idea of a `Filter` have some metadata to know its method and path and stuff is discussed in #89. It's likely not super easy, consider that filter chains can require just about anything...

**Comment by droundy** [comment]
Sounds like that issue is a better approach for this.  Thanks!
