### ISSUE TITLE
Index path documentation

### ISSUE THREAD

**Issue by WillSquire** [seanmonstar/warp#214]
Wasn't entirely clear on how to define an index route (i.e. "" or "/"), but found https://github.com/seanmonstar/warp/issues/118 which helped out. Not sure if some documentation on `warp::path` might make it easier to find for future users? I originally assumed `warp::path::end()` matched the URI backwards, i.e. "something/something/this", and `warp::path()` or `warp::path("/")` matched an index or something.

**Comment by seanmonstar** [comment]
I agree, the documentation there should be improved.

It also seems like the `path!` macro could do a better job of helping match full paths, and be less surprising in general (such as how `path!("/my/file")` will match `/my/file/wat`).

**Comment by WillSquire** [comment]
Ah, yes that would definitely catch me out. Though I must say, so far it's an awesome framework. Style wise it just feels right. I tried doing something similar once and made a behaviour tree styled framework in Dart for backends, but this has the HTTP layer covered instead of just a plain old BT, and it's far easier to use! Are there any inverter decorates? I.e. paths that don't match the criteria (`!`)?

**Comment by seanmonstar** [comment]
> Are there any inverter decorates? I.e. paths that don't match the criteria (`!`)?

Not built-in. I believe an inverter can be confusing to recognize what exactly it is doing. Particularly, is it *just* rejecting if the path doesn't match, or does it *also* "consume" that part of the path. What I mean is, assuming some sort of `not(path("blog"))`, when it is applied to `/company/about`, and `company` isn't `blog`, would the next filter in the chain see just `/about`, or still `/company/about`?

**Comment by remram44** [comment]
Got tripped by both those issues today. Is there a way to have path!() not match additional components? And I was also expecting `path!("")` or `path!()` to match `/` (instead of a recursion error).

**Comment by seanmonstar** [comment]
warp v0.2 includes #359, which makes `path!("foo" / "bar")` require the path to end, and allows `path!("foo" / "bar" / ..)` to indicate a prefix.
