### ISSUE TITLE
How can I get feedback for invalid requests?

### ISSUE THREAD

**Issue by Apromixately** [seanmonstar/warp#216]
I was playing around with the todo example and noticed that sending JSON without all the fields required for a Todo resulted in a 400 Bad Request. This is not particularly surprising but I am wondering how I could output a little more information about what the problem. Is there some way to increase the debug level or insert a handler somwhere?

**Comment by seanmonstar** [comment]
Yea, using the [error example](https://github.com/seanmonstar/warp/blob/master/examples/errors.rs), you can check the rejection for a `warp::filters::body::BodyDeserializeError` to get the details, and then give whatever details you want back in a response (sometimes details aren't sent for security or spam-fighting reasons).
