### ISSUE TITLE
Integration testing examples and documentation

### ISSUE THREAD

**Issue by WillSquire** [seanmonstar/warp#217]
I've been reading through the examples and docs but I can't find material on integration testing? Found a good bit on unit testing [here](https://docs.rs/warp/0.1.15/warp/test/index.html) though. Is there material on this?

**Comment by WillSquire** [comment]
Thanks for the detailed post @hgzimmerman. I'm kinda more interested in how a server is 'spun up' in a test though. I see the database side as outside of scope, but it would be good information nonetheless - P.S I've got an open source project I'm tinkering with at the moment that has a similar setup [here](https://github.com/WillSquire/Graphy/blob/8f067ad3b8819e98e0a76f659340d75d88153b00/api/src/lib.rs) if that's a helpful reference for others. Separation in `lib.rs` and `main.rs` is also kinda noteworthy. 

Anyway the bit I'm getting my head around is that `run(([127, 0, 0, 1], 8000))` puts a thread in an infinite loop, so doing an integration test from the app entrypoint causes it to block an never return. I can think of a way around it (i.e. extracting all routing out before this point and testing) but ideally I'd like to spin it up, send a request and stop the server in an integration test just so it can be as close as possible to the real thing. I already compromised with separating the args parsing to `main.rs` and the rest to `lib.rs`.

**Comment by seanmonstar** [comment]
As you've noticed, there's an introduction to testing at the [docs of `warp::test`](https://docs.rs/warp/*/warp/test/index.html). Besides that, all of [warp's own tests](https://github.com/seanmonstar/warp/tree/master/tests) are built using `warp::test`, in case you'd like more examples.

------

@hgzimmerman 

> This facilitates unit testing, but fills me with existential dread, because you now have the problem of ensuring that the mock object behaves the same as your database. 

You could make the default tests use the mock object, and have CI run the tests with a real DB.

> [..], but the effort of creating the mock object and ensuring its parity with the database implementation is more effort than I think faster tests are worth.

To each their own, but in my experience, having fast tests is important to allow a developer to run them more often, being more confident and productive.

**Comment by hgzimmerman** [comment]
@WillSquire In that case, I think [bind_with_graceful_shutdown](https://docs.rs/warp/0.1.15/warp/struct.Server.html#method.bind_with_graceful_shutdown) might serve your needs in that it allows you to shut down your server externally.

--------------
@seanmonstar I feel dumb for having phrased it that way. For professional development with collaborators, unit tests are invaluable, whereas my common use case of non-critical throwaway services is better served by relying on integration tests and Rust's types to keep me safe. And thank you for the suggestion, I never thought to put the mock/db choice for testing behind a feature flag.

**Comment by seanmonstar** [comment]
Is the question answered? Sorry, I got lost in the comments. XD

**Comment by WillSquire** [comment]
@hgzimmerman thanks I'll take a look into this :) but I was hoping there was a way to use the same method as I'd use in production (`run()`)?

@seanmonstar No problem :P it's not quite there for me yet. I guess I'd expect documentation on both unit testing and integration testing like in the [rust docs](https://doc.rust-lang.org/1.30.0/book/second-edition/ch11-03-test-organization.html#integration-tests). Rust seems to have a convention of doing integration tests from the main app entrypoint, which isn't bad, although I understand an integration test in general can be more localised to specific regions on an app. As an example Rocket's got a friendly nod at this in the [testing section](https://rocket.rs/v0.4/guide/testing/) because it explains how to structure the `rocket().launch()` separately (the main entry point).

**Comment by hgzimmerman** [comment]
The Rust docs regarding integration tests you are pointing to pertain to integration tests for libraries, not necessarily for web services, so the approaches are different. While both attempt to cover the publicly facing api of a project, library integration tests exist to ensure that the library works with other libraries or in the context of how it is supposed to be used by consumers of the library. Web service integration tests aim to ensure that the service and all its known dependencies (database, external api calls) work together, and that requests are handled as expected.

Warp's existing test module enables both integration and unit testing, and the distinction hinges only on if you are mocking your external entities or using them directly. The use of warp's testing module isn't practically different than the provided Rocket example, in that `warp::serve()`ing a filter is the same as calling `.launch()` on a Rocket service, and that passing a filter to a test request chain is approximately the same as instantiating a `Client` and running requests against it.

So instead of  the `run()` function you export from `lib.rs`, you might want to export another function that takes your config information and returns your filter (everything currently inside your `warp::serve` in `run()`), that you then use it like `warp::serve(your_filter_here).run(...)` in your `main.rs`. That way, you can test the same lib function that you use in `main()` using warp's existing test framework.

**Comment by WillSquire** [comment]
Thanks @hgzimmerman. I think that any kind of test should be as close as possible to how actually going to be used, but this might be a matter of opinion. Appreciate there can be focus on certain areas for integration tests (such as communicating with databases) and I'm following this up [on diesel](https://github.com/diesel-rs/diesel/issues/2058) as a problem but as something that's outside the scope of this package.

The reason for this ticket and what could hopefully be a helpful improvement is the documentation around integration testing for the main app entrypoint that _handles http requests_, i.e. handled by `run()`. The closer requests fired in tests can be handled in the same manner as they'd be handled in production, the better, but I understand there might be some compromises. So I've tried pulling out the following:

```rust
warp::serve(
  // Snip...
)
.run((config.address, 8000));
```

and returning:
```
warp::get2()
  .and(warp::path::end().and(juniper_warp::graphiql_filter("/graphql")))
  .or(warp::path("graphql").and(graphql(context(db, hasher, tokeniser))))
  .with(log)
```

but `with(log)` returns a type that is internal. I'm currently looking at:
```
impl Filter<Extract = (warp::log::internal::Logged,), Error = warp::Rejection>
```

as the return type, but is there a different signature I should be using to this?

**Comment by hgzimmerman** [comment]
Yeah, without looking too closely, I'm pretty confident that the following should work:
```rust
-> impl Filter<Extract = (impl warp::Reply,), Error = warp::Rejection>
```
or failing that, stick a `.boxed()` at the end of your filter chain and have a return signature of:
```rust
-> BoxedFilter<(impl warp::Reply,)>
```

Check out the [returning example](https://github.com/seanmonstar/warp/blob/master/examples/returning.rs) for a better reference point.

**Comment by WillSquire** [comment]
Brilliant thanks @hgzimmerman that worked great. Wanted to get an example up here to help others, so apologies for going a bit quiet. I haven't got a minimal example yet but hopefully with have soon (I know this sort of thing helps me). Thanks again

**Comment by WillSquire** [comment]
In case it's useful to others, here's the separation in [lib.rs](https://github.com/WillSquire/Graphy/blob/3235ac69a9ab1c92befac568dcec41849b21322f/api/src/lib.rs) and the [integration tests](https://github.com/WillSquire/Graphy/blob/3235ac69a9ab1c92befac568dcec41849b21322f/api/tests/integration_tests.rs). These aren't quite finished yet as the next thing to tackle is database seeding... but that's a whole separate thing. Thanks again :)

**Comment by seanmonstar** [comment]
Additionally, the [todos.rs](https://github.com/seanmonstar/warp/blob/master/examples/todos.rs) example was recently updated to show how to build and app and include tests.
