### ISSUE TITLE
nested querystrings

### ISSUE THREAD

**Issue by hwchen** [seanmonstar/warp#22]
Hi!

Thanks for your hard work on this! I'm enjoying the filters api.

I have a use case for nested querystrings (or some way to create a list out of repeated querystring keys). I don't believe that serde_urlencoded supports this, while I think [serde_qs](https://github.com/samscott89/serde_qs) does.

Would you want to support this in warp, or is there a way for me to write a custom filter?

**Comment by seanmonstar** [comment]
I hadn't heard of serde_qs, does it just support more use cases than serde_urlencoded? I'm certainly interested in providing the best support in warp...

**Comment by caolan** [comment]
Another problem is that serde_urlencoded doesn't support unit enums, which would be handy for strict query parameters.

Example:
https://play.rust-lang.org/?gist=627092ecc8fb4be62189f3997dbd97c8&version=stable&mode=debug&edition=2015

It will serialize them but not deserialize.

There's an old pull request for serde_urlencoded to support it, but it's not been approved: https://github.com/nox/serde_urlencoded/pull/30

**Comment by seanmonstar** [comment]
Having taken a look at serde_qs, the README suggests that unless wanting nested query parameters, to prefer serde_urlencoded. Should the better course of action here be to try to get those two features merged into serde_urlencoded?

**Comment by hwchen** [comment]
Sorry it took me a while to get back to this thread.

I can open an issue for serde_urlencoded and see if there's any interest in supporting nested querystings.

**Comment by hwchen** [comment]
It looks as though the maintainer of serde_urlencoded is not interested in adding nested querystrings.

I understand wanting to use serde_urlencoded, which is probably much more battle tested.

What's the most ergonomic way for me to access the query string? Then I could parse it however I like.

**Comment by seanmonstar** [comment]
We could add a `string()` (naming is hard) filter to the query module, returning a `String`. Then it could be parsed however one sees fit. (This is another case where it can't return the `&str`, but that with `async`/`await`, it probably could.)

**Comment by hwchen** [comment]
would `raw_query()` make sense?

I'm happy to try a pull request if you like.

**Comment by seanmonstar** [comment]
Sure, that'd be great!
