### ISSUE TITLE
Consider removal of `warp::ext::set`

### ISSUE THREAD

**Issue by seanmonstar** [seanmonstar/warp#222]
It takes advantage of warp's usage of thread-local storage, but that means we can't change away from internally using TLS as long as this function requires it.

**Comment by remexre** [comment]
What would the replacement API look like?

**Comment by seanmonstar** [comment]
I'm not certain. Perhaps by adding a way to turn a `Filter` into a `Service`, extensions could be set before reaching the filters. Or a new `warp::ext::with_mut(impl Fn(&mut Extensions))` could be added.

**Comment by carllerche** [comment]
Makes sense :+1:

**Comment by itsfarseen** [comment]
How to set an extension in latest version of warp?

**Comment by paulzhang5511** [comment]
@itsfarseen 
```rust
fn with_db(pool: Pool) -> impl Filter<Extract = (Pool,), Error = Infallible> + Clone {
    warp::any().map(move || pool.clone())
}

let user_create = warp::path!("api" / "user" / "create")
        .and(warp::post())
        .and(warp::body::json())
        .and(with_db(pool.clone()))
        .and_then(user::user_create);
```
