### ISSUE TITLE
Change Server::tls(path, path) to return a builder instead

### ISSUE THREAD

**Issue by seanmonstar** [seanmonstar/warp#223]
The `Server::tls()` method takes 2 paths, one for the key and one for the certificate. It's very easy to mix up the order of the two paths. Instead, `Server::tls()` can return a builder with methods like `key_path` and `certificate_path`. It also allows adding different ways to configure TLS besides requiring file paths.

**Comment by droundy** [comment]
This would be great.  In particular, as I'm in the process of switching to `acme-lib` I now have direct access via the API to the key and certificate contents, but do not have paths for them.
