### ISSUE TITLE
Catch-all path

### ISSUE THREAD

**Issue by stoically** [seanmonstar/warp#224]
Hey, thanks for your work on warp. Was really a breeze to get up and running, even with websockets.

My use-case is to serve a PWA (react app), which means that most of the routing is done client-side by javascript in the browser.

What I currently have is:

```rust
let routes = websocket
    .or(api)
    .or(ui);
```

This works fine, serves `websocket` from `/websocket`, `api` from `/api` and the `ui` is just a `warp::fs::dir` - which makes it so that it's served on `/`.

What I'd now need is something that serves all "undefined" paths from `ui` - I've tried several combinations with `warp::path`, `path!` and `.recover`, but unfortunately to no avail. Would be great if you could point me in the right direction on how to achieve that.

**Comment by udoprog** [comment]
Hey,

This is roughly what I do today to accomplish this:

```rust
let web_root = /*...*/;

let routes = api.recover(recover);
let routes = routes.or(ws.recover(recover));

let main_js = warp::get2()
    .and(warp::path("main.js"))
    .and(warp::filters::fs::file(web_root.join("main.js")));

let index = warp::get2()
    .and(warp::filters::fs::file(web_root.join("index.html")));

let app = main_js.or(index);
let routes = routes.or(app.recover(recover));

let service = warp::serve(routes);
```

Note that the fallback filter doesn't have any path filters associated with it. So it should match anything except for the routes already matched by the `api` or `ws` filters.

**Comment by stoically** [comment]
Works great! Thank you.
