### ISSUE TITLE
Custom header to dir filters

### ISSUE THREAD

**Issue by codri** [seanmonstar/warp#226]
Hi,

I have a folder with some static data in it, that's being served via the dir filters.

```rust
    let data = warp::path("data").and(warp::fs::dir("./data/"));
```

I'd like to add a `Cache-Control` header to the response for each file.
Is there a way to do that? I've tried a bunch of stuff, none of which works.

Thanks

**Comment by seanmonstar** [comment]
Do you just want a static value added?

```rust
warp::fs::dir("data").map(|res: warp::fs::File| {
    warp::reply::with_header("cache-control", "private")
})
```

Or do you mean inspecting the file before deciding what header to add?

**Comment by codri** [comment]
Just a static value, I've tried adding a map, but was adding it after the and combinator, and that didn't work.
Your worked perfectly, thank you.
