### ISSUE TITLE
On the same ip/port more "webapps"

### ISSUE THREAD

**Issue by LucianoBestia** [seanmonstar/warp#230]
In asp.net there is a concept of "webapp". It is an "isolated" application on the same web server+ip+port. Only the route is different. It is then easy to take one webapp and copy it to another server.
 Is it possible to achieve something similar with Warp?
Maybe one frontend application that calls different backend applications for different routes?

**Comment by seanmonstar** [comment]
I've never used .NET, can you explain more? Is each "webapp" a separate OS process? Or simply a separate set of request path routing rules?

**Comment by LucianoBestia** [comment]
Yes, every "webapp" is in a separate OS process. They call it "Worker process".
"Worker Process (w3wp.exe) runs the ASP.Net application in IIS."
http://www.dotnetfunda.com/articles/show/821/beginners-guide-how-iis-process-aspnet-request
One process can be stopped or restarted without affecting other processes on the same IIS server (same ip and port).
I think the IIS server is the one who manages this Worker Processes. 
Asp.net code knows nothing about it. So the same code can run on different IIS servers and in different routes.

**Comment by LucianoBestia** [comment]
I see people often use nginx reverse-proxy forwarding to achieve something similar.
I am mentioning nginx only because I found a lot of talk about that.
Is it possible to use `warp` for that reverse-proxy forwarding?
So I could start my separate `warp web apps`: mem1, mem2, mem3,... on different ports on 127.0.0.1: 8081, 8082, 8083,..
Then I would prepare a new `warp` app just to forward from the port 80 on the external IP to some port on the internal IP depending on the route.
```
#nginx conf example
server {
        listen 80 default_server;
...
    location /mem4/ {
	proxy_pass http://127.0.0.1:8084/;
    }
...
```
