### ISSUE TITLE
Consider to unseal `reply::Reply` trait

### ISSUE THREAD

**Issue by boxdot** [seanmonstar/warp#233]
Currenty, `warp::reply::Reply` trait is sealed and is implemented only for 
 - `http::StatusCode`
 - `http::Response<impl Into<hyper::Body>>`
 - `String`
 - `&'static str`

### Why this is a limitation?  

If we could implement `Reply` for custom types, we would be able to offload more of the API definition onto the type system. That is, we could express entirely in the type system what a handler might return. E.g.

* `-> Json<SomeSerializableType>`
* `-> Result<(), StatusBadRequestUnit>`
* `-> Result<Json<User>, Either<StatusBadRequestUnit, StatusNotFoundUnit>>`

This is great for writing and reading APIs. More important, it allows to easily test such handlers. Currently, we have either to split handlers into several functions, or to inspect the value of returned response. Further, it also allow to generate an API spec like OpenAPI from the handler signature. I also think this follows the warp philosophy where an app is defined by a single composed Rust type.

### Example

I unsealed the `Reply` trait and implemented it for `()`, `Result<T,E>` with `T, E: Serializable`, and I also exposed a `Json<T>` wrapper. I change the todos example to show how the API might look. Feel free to take a look at the diff: https://github.com/seanmonstar/warp/compare/master...boxdot:unseal-reply

What do you think?

**Comment by seanmonstar** [comment]
I think unsealing `Reply` is probably a fine thing to do!

However, I think a couple implementations perhaps *shouldn't* be included:

- `()`: My gut says it could be too easy to accidentally return a response from a function that forgot a return type. I think acknowledging that a return value is *something* is clearer.
- `Result<T, E>`: The current mechanism for a filter failing is to return a `Rejection`, I think it could be confusing if somethings return a `Rejection` and others return some other error type.

**Comment by boxdot** [comment]
* `()`: Indeed. It looks like it is better to be explicit here.
* `Result<T, E>`: It might be that I got confused by the implementation 

  ```rust
  impl<T> ReplySealed for Result<T, ::http::Error>
  ``` 

  on https://github.com/seanmonstar/warp/blob/60edfae/src/reply.rs#L416. I thought it can be generalized.

  Unfortunately, the rejection API does not provide a description on type level what might go wrong, it hides it behind the `Rejection` struct which we have to downcast. Since I don't have a better proposal how to do this, I think it is fine not to provide this implementation for now. In the end clients can implement `Reply` for their own custom `Result` enum. In any case, I will try it for my APIs and if it works out I will either submit another proposal or more examples.

For this issue, I will submit a PR which unseals the `Reply` trait. Or, do you want to wait until 0.2?
