### ISSUE TITLE
Operators for filters

### ISSUE THREAD

**Issue by StevenDoesStuffs** [seanmonstar/warp#240]
In boolean algebra, and is represented as multiplication and or as addition. I was wondering if it'd be a good idea to implement these operators for filter.

Code:
```rust
(path!("api"/"login"/u32) * json::<Login>())
    .and_then(login) +
(path!("api"/"login"/u16) * json::<Login>())
    .and_then(login);
```
would be come
```rust
path!("api"/"login"/u32)
    .and(json::<Login>())
    .and_then(login)
.or(path!("api"/"login"/u16)
    .and(json::<Login>())
    .and_then(login));
```

One thing to consider is that the and method in Filter isn't associative, and the order in which rust evaluates these operators is left to right.

**Comment by StevenDoesStuffs** [comment]
Should I close this and #239 in favor of #26?
See https://github.com/seanmonstar/warp/issues/26#issuecomment-501587092

**Comment by seanmonstar** [comment]
I wanted to implement `&` and `|` initially, but it's not possible to do so in a generic way for *all* filters. It's a sealed trait, but the compiler doesn't know, so it worries about what if one crate implements `Filter` for a type, and another implements `BitAnd` for the same type.

**Comment by StevenDoesStuffs** [comment]
Yes, I saw that after I read #26, and so I wrote up a proposal for a routing macro that uses operators, so they don't have to be implemented as traits. Can you please check that out?
Here it is: https://github.com/seanmonstar/warp/issues/26#issuecomment-501587092
