### ISSUE TITLE
Filter to get the current URI?

### ISSUE THREAD

**Issue by droundy** [seanmonstar/warp#247]
I can't seem to find a filter that will return the current URI.  I believe I need this in order to implement a redirect from http:XXX/YYY to https:XXX/YYY.  Unless there is some additional undocumented logic in redirect that would append the remaining portion of the path to the redirect?

**Comment by seanmonstar** [comment]
When you mean current URI, do you mean the full path that the client sent to the server? Or only what has been matched so far?

**Comment by droundy** [comment]
Either the full path or what has not yet been matched would work.

**Comment by seanmonstar** [comment]
There's `warp::path::full()` and `warp::path::tail()`, respectively.

**Comment by droundy** [comment]
Thanks, I don't know how I didn't see those!
