### ISSUE TITLE
Get body as String

### ISSUE THREAD

**Issue by lpil** [seanmonstar/warp#248]
I feel somewhat foolish asking this, but how do I get the request body as a String?

I ask as in my application I wish to parse the JSON body handler rather than by using `body::json` as I wish to return more detailed error messages to the user instead of just 404.

**Comment by vasilakisfil** [comment]
In case someone else is looking for that, I just managed to create a custom filter that does exactly that:

```

pub fn body_to_string() -> BoxedFilter<(String,)> {
    use std::iter::FromIterator;
    use bytes::buf::Buf;

    warp::any()
        .and(warp::filters::body::concat())
        .map(|mut full_body: warp::body::FullBody| {
            let vec: Vec<u8> = full_body.collect();
            std::str::from_utf8(&vec).unwrap().to_owned()
        }).boxed()
}
```

**Comment by vasilakisfil** [comment]
Right, makes sense! Thanks for the tip :)

**Comment by Jupp56** [comment]
Just a quick heads up: This doesnt work anymore, thanks to the restructuring of the body api.

> In case someone else is looking for that, I just managed to create a custom filter that does exactly that:
> 
> ```
> 
> pub fn body_to_string() -> BoxedFilter<(String,)> {
>     use std::iter::FromIterator;
>     use bytes::buf::Buf;
> 
>     warp::any()
>         .and(warp::filters::body::concat())
>         .map(|mut full_body: warp::body::FullBody| {
>             let vec: Vec<u8> = full_body.collect();
>             std::str::from_utf8(&vec).unwrap().to_owned()
>         }).boxed()
> }
> ```
> 
> or if you want to handle the errors gracefully:
> 
> ```
> pub fn body_to_string() -> BoxedFilter<(String,)> {
>     use std::iter::FromIterator;
>     use bytes::buf::Buf;
>     use std::str::Utf8Error;
> 
>     warp::any()
>         .and(warp::filters::body::concat())
>         .map(|mut full_body: warp::body::FullBody| {
>             full_body.collect::<Vec<u8>>()
>         }).and_then(|vector: Vec<u8>| {
>             let res = std::str::from_utf8(&vector);
>             match res {
>                 Ok(s) => Ok(s.to_owned()),
>                 Err(e) => Err(warp::reject::custom(e))
>             }
>         }).boxed()
> }
> ```

**Comment by roper79** [comment]
Hi, I am a newbie here, but why `warp::body::string()` is not in the API?

**Comment by Jupp56** [comment]
A currently (0.3) working string filter:
```rust
use bytes::Bytes;
use warp::Filter;

use crate::service::error::ApiError;

/// Extracts the body of a request as string
#[allow(dead_code)]
pub fn string_filter(
    limit: u64,
) -> impl Filter<Extract = (String,), Error = warp::Rejection> + Clone {
    warp::body::content_length_limit(limit)
        .and(warp::filters::body::bytes())
        .and_then(convert_to_string)
}

async fn convert_to_string(bytes: Bytes) -> Result<String, warp::Rejection> {
    String::from_utf8(bytes.to_vec())
        .map_err(|_| ApiError::WrongRequestData("String not UTF-8 compliant".to_string()).into())
}
```

**Comment by kaj** [comment]
Just a minor note: The example filters provided here does not respect the content-type / charset of the body, and will fail for any body data that is not utf8 / ascii.  If the intent is to actually parse the data in the handler (as json or some other format), it is in most cases much better to handle the data as a `Vec<u8>` or `Bytes` as you get from the provided `warp::filters::body::bytes()`.

Most parsers ignore the utf-8 guarantee of a string anyway and takes their input as a (something that can look like) a `&[u8]`.
