### ISSUE TITLE
mechanism for stopping the server and restarting?

### ISSUE THREAD

**Issue by droundy** [seanmonstar/warp#252]
I'm working on a crate to automatically handle lets-encrypt for TLS, and it's mostly working pretty well:

https://crates.io/crates/lets-encrypt-warp

However, I'm now trying to figure out how to make it renew the certificate before it expires, and I'm not sure how to best stop the server so I can create a new one with the new certificate.

Obviously I could kill the entire process and restart it, but that seems inelegant.  I'd rather have a built-in approach that could avoid missing connections, e.g. I tell warp to stop listening for new connections, then I start the new warp, but the old one could finish responding to any connections that have already been made?

Currently I can't see any way to achieve this other than to fork the entire process so I can kill it and start over, which seems a bit heavy-handed.

**Comment by seanmonstar** [comment]
You could use the [graceful shutdown mechanism](https://docs.rs/warp/0.1.17/warp/struct.Server.html#method.bind_with_graceful_shutdown).

**Comment by droundy** [comment]
That looks like just about what I want.  Is there any way to know when it will be safe to restart the server (i.e. the port will be available to be opened again)? If not, I'd imagine just waiting a few seconds, and perhaps retrying every time it fails to start, but that sounds potentially complicated.

**Comment by droundy** [comment]
Hi @seanmonstar ,

I'm somehow triggering a bug in https://github.com/tokio-rs/tokio when calling your `bind_with_graceful_shutdown`.  I'm not sure where the bug might lie, but tokio is calling `unwrap` incorrectly.  I imagine this may be a `tokio` bug, but am uncertain where the bug actually lies.
```
# RUST_BACKTRACE=1 /home/droundy/lists/target/debug/thing-lists --domain lists.for-our.info
The time to expiration of "lists.for-our.info.pem" is Some(7252387s)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: tokio_executor::global::spawn
             at /home/droundy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:165
  11: tokio::executor::spawn
             at /home/droundy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/executor/mod.rs:133
  12: hyper::rt::spawn
             at /home/droundy/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.33/src/rt.rs:30
  13: lets_encrypt_warp::lets_encrypt
             at /home/droundy/.cargo/git/checkouts/lets-encrypt-warp-a7a1b78d91809bab/30ee580/src/lib.rs:96
  14: thing_lists::main
             at src/main.rs:113
  15: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  16: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  18: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  19: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  20: main
  21: __libc_start_main
  22: _start
```

**Comment by seanmonstar** [comment]
The unwrap is expected, and is inside `spawn`. Calling `spawn` just be done from within a running runtime. You could do so like this:

```rust
tokio::run(futures::future::lazy(|| {
    tokio::spawn(server);
    tokio::spawn(other_future);
});
```

**Comment by droundy** [comment]
Hi @seanmonstar 

Thanks for all your patient help!

I've attempted to use run and lazy as you suggest, and am now at an impasse again.  Everything compiles (again), and it runs without giving any error messages, but doesn't seem to be serving anything up on ports 80 or 443.  (I'm trying to serve on both ports at once.)  At this stage I'm not sure how to debug what might be going wrong.  When using ordinary warp::server ... .run() I've never had such a problem.

Any suggestions? My code is at:

https://github.com/droundy/lets-encrypt-warp/blob/master/src/lib.rs

and

https://github.com/droundy/lists/blob/master/src/main.rs

**Comment by droundy** [comment]
Never mind, I think I managed to get things working by wrapping each call to spawn in a separate `tokio::run`, which itself is wrapped in a `std::thread::spawn` (so I'll be able to in my main thread sleep and then send the signal to shut down gracefully at the right time.

Does this sound like the right way of going about this? Is it a problem (or bad idea) to have multiple tokio runtimes going at the same time?  My basic pattern is now looking like:
```
std::thread::spawn(|| {
    tokio::run(futures::future::lazy(move || {
        tokio::spawn(
            warp::serve(redirect)
                .bind_with_graceful_shutdown(([0, 0, 0, 0], 80), rx80)
                .1,
        )
    }));
});
```
If this is the "expected" way to use `bind_with_graceful_shutdown`, then presumably you could create an API that does this? It feels very heavy-handed and cumbersome.  But when I tried having just one runtime (with one big `tokio::run` wrapping everything), it didn't seem to work.

**Comment by seanmonstar** [comment]
To read up a little on the runtime model, you could start here: https://tokio.rs/docs/getting-started/runtime/

I mention `spawn` if you were to want to launch multiple tasks into the runtime, like 1 for the server, and another with something like `tokio-signal` watching for signals. If you don't need more than 1, you can just use `tokio::run`, which will automatically spawn the passed future for you.

```rust
std::thread::spawn(|| {
    tokio::run(
        warp::serve(redirect)
            .bind_with_graceful_shutdown(([0, 0, 0, 0], 80), rx80)
            .1
    );
});
```

**Comment by droundy** [comment]
Thanks so much for your help! I've got everything working now (I think), and it doesn't look like there is a particular need for a change in warp.  I do have a quick question, though:  does `bind_with_graceful_shutdown` close the socket quickly? Because I'm assuming that waiting a second (for tokio to run the `bind_with_graceful_shutdown`) will be (usually) enough to enable me to start a new server (with a renewed credential).  This could be a problem if you waited until all connections to finish to close the port.

**Comment by seanmonstar** [comment]
Yes, once the shutdown signal is received, it drops the `TcpListener` immediately, and tells all the existing connections to close when they can (if idle, immediately, otherwise after the response finishes). Then it waits until all have done so.

**Comment by droundy** [comment]
Great, I think everything's working then!

**Comment by avkonst** [comment]
@seanmonstar is there any way to await for "graceful shutdown completed" event? I mean I would like to await for the server stopped and all connections (idle and non idle) closed. In other words I would like to get a callback when the server stops/completes waiting for "Then it waits until all have done so." (as per your message above)

**Comment by avkonst** [comment]
@seanmonstar please ignore the previous comment. I have found I can await for completion of `warp::serve()` by chaining with `then`
