### ISSUE TITLE
Modify response body for static files

### ISSUE THREAD

**Issue by terhechte** [seanmonstar/warp#253]
Hey,
I'm trying to return static files, but for each (HTML) file I'd like to inject a small HTML payload into the bottom of the file. I could not find a way to achieve this. The closest I've come is:

``` rust
    let files = warp::fs::dir(folder)
        .map(|res: warp::fs::File| {
            let mut response = res.into_response();
            let mut body = response.body_mut();
            body.push_str("test");
        });
```

However, `push_str` does not work because `Response` is not `Response<String>`. I'm pretty sure that I have to read the body first in order to retrieve it (since it is streamed), but I could not figure out how to do that.. Thanks!

**Comment by seanmonstar** [comment]
You use `Stream::chain` to add some data on the end. Something like this (types my be slightly off):

```rust
resp.map(|body| {
    let chained = body.chain(futures::stream::once("test".into()));
    Body::wrap_stream(chained)
})

**Comment by terhechte** [comment]
Thanks! I’ll try it out!
