### ISSUE TITLE
Expose `http1_max_buf_size` for Hyper server?

### ISSUE THREAD

**Issue by nerdrew** [seanmonstar/warp#259]
Is there a way to configure the hyper server `http1_max_buf_size` right now through warp? If not, are there plans to expose it?

**Comment by seanmonstar** [comment]
I didn't have any plans (yet). Before we do, why so you need it? To reduce memory usage of the server? Or increase the throughput?

**Comment by nerdrew** [comment]
I'm trying to increase throughput. I'm using warp to handle > 100MB requests and it looks like it spends a lot of time just reading the body. It seems like bumping `http1_max_buf_size` or even `http1_read_buf_exact_size` would be a way to fix this. Is setting `http1_read_buf_exact_size` to 8MB or 16MB crazy for a server?

**Comment by seanmonstar** [comment]
The hope is that the adaptive read buffer strategy would make things better automatically. Does it not go high enough, is that the issue? If so, it may be reasonable to increase the default max in hyper now that the adaptive strategy exists.

**Comment by nerdrew** [comment]
I'll test a larger default buffer and get back to you. Thanks for warp, it is fun to work with.

**Comment by seanmonstar** [comment]
Assuming the adaptive default is fine. We can re-open if not.
