### ISSUE TITLE
Show GitHub: An experimental router DSL for warp

### ISSUE THREAD

**Issue by ayosec** [seanmonstar/warp#27]
I'm posting this as an issue because some people here may be interested in exploring an idea like this one. If you feel that this is not an appropriate place, please feel free to close the issue.

My intention is not change the code in the warp crate, but to discuss the idea of using a DSL to write the routes.

## Context

As someone who used [spray-routing](http://spray.io/documentation/1.2.4/spray-routing/) (which was integrated in [Akka HTTP](https://doc.akka.io/docs/akka-http/current/routing-dsl/index.html) a few years ago) for 5 years, it was a pleasant surprise to discover this project in the [Reddit post](https://www.reddit.com/r/rust/comments/93tcxs/warp_a_new_web_framework_for_rust/).

I miss the routing DSL of Spray/Akka-HTTP, and when I saw the warp documentation I thought that it could be a perfect foundation to write something like that.

## The warp_dsl crate

[Repository](https://github.com/ayosec/warp_dsl)

During the last couple of days I made a crate that implements a DSL to write routes. The code is a bit junky, there are a lot of missing features, and I'm pretty sure that there are some  edge cases that will generate broken code, but at least it works well enough to experiment with it. It also works on Rust stable.

As an example, it converts the following code:

```rust
let routes = router!(
    path("blogs") {
        get & index {
            complete { "Get all blogs" }
        }

        path(u32) |blog_id| {
            get {
                complete { format!("Details for blog {}", blog_id) }
            }

            delete {
                complete { format!("Delete blog {}", blog_id) }
            }
        }
    }

    path("blog" / u32 / "posts") |blog_id| {
        post & index & (body::json()) |post: Post| {
            complete {
                format!("Publish post '{}' with body '{}' in blog {}", post.title, post.body, blog_id)
            }
        }

        get & path(u32) & index |post_id| {
            complete {
                format!("Read post {} in blog {}", post_id, blog_id)
            }
        }
    }
);
```

To this:

```rust
let routes = (((::warp::get((path!("blogs")).and(::warp::index()).map(
    || "Get all blogs",
)))).or(
    ((::warp::get((path!("blogs")).and(path!(u32)).map(|blog_id| {
        format!("Details for blog {}", blog_id)
    })))).or(
        (::warp::delete((path!("blogs")).and(path!(u32)).map(|blog_id| {
            format!("Delete blog {}", blog_id)
        }))),
    ),
)).or(
        ((::warp::post(
            (path!("blog" / u32 / "posts"))
                .and(::warp::index())
                .and(body::json())
                .map(|blog_id, post: Post| {
                    format!(
                        "Publish post '{}' with body '{}' in blog {}",
                        post.title,
                        post.body,
                        blog_id
                    )
                }),
        ))).or(
            (::warp::get(
                (path!("blog" / u32 / "posts"))
                    .and(path!(u32))
                    .and(::warp::index())
                    .map(|blog_id, post_id| {
                        format!("Read post {} in blog {}", post_id, blog_id)
                    }),
            )),
        ),
    );
```

This [example](https://github.com/ayosec/warp_dsl/blob/master/examples/blog_api.rs) is available in the repository of the crate, and can be tested with:

```bash
$ cargo run --example blog_api
```

## Some implementation details

* It relies on [proc-macro-hack](https://github.com/dtolnay/proc-macro-hack) to use procedural macros in Rust stable.

* The DSL is heavily inspired by Spray/Akka.

* The rules to combine filters are simple:

    * Nested filters are combined with `and`.
    * Filters in the same block are combined with `or`.

    So, a declaration like:

    ```rust
    path("p") {
        foo { ... }
        bar { ... }
    }
    ```

    Emits the code:

    ```rust
    (
        path!("p").and(foo()).and(...)
    ).or(
        path!("p").and(bar()).and(...)
    )
    ```

* The operator `&` can be used to combine filters when there is only one child (from Spray/Akka).

    A declaration like:

    ```rust
    a {
        b {
            c {
                complete { ... }
            }
        }
    }
    ```

    Can be written as:

    ```rust
    a & b & c {
        complete { ... }
    }
    ```

* The handler of the request is defined with the `complete` directive (also from [Spray/Akka](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/route-directives/complete.html#example)).

* Closure arguments are accumulated until the `complete` block is found.

    For example, a route like:

    ```rust
    path("x" / usize) |x| {
        (warp::header::<SocketAddr>("host")) |host| {
            complete {
                do_stuff(x, host)
            }
        }
    }   
    ```

    Will emit something like:

    ```rust
    path!("x" / usize)
        .and(warp::header::<SocketAddr>("host"))
        .map(|x, host| {
            do_stuff(x, host)
        });
    ```

* HTTP methods are moved to the top of the filter, since the [current functions in `warp::filters::method`](https://docs.rs/warp/0.1.0/warp/filters/method/index.html) expect a filter as an argument.

    The DSL is able to detect when a route contain multiple HTTP methods. A declaration like

    ```rust
    post {
        get {
            ...
        }
    }
    ```

    Produces an error during compilation.

**Comment by seanmonstar** [comment]
This is *really* cool! (And perhaps somewhat related to #12 and #26).

Something I didn't want to replicate from Akka is the very easy-to-trigger ignored directive since its valid syntax to forget `~`. It looks like this doesn't suffer from that.

I haven't built a large app with Akka, but when looking at the examples, it felt like the nested directive style would get very unwieldy with larger and larger apps. Have you noticed that?

**Comment by ayosec** [comment]
> Something I didn't want to replicate from Akka is the very easy-to-trigger ignored directive since its valid syntax to forget `~`. It looks like this doesn't suffer from that.

Yep. In Scala it is easier to miss the separator because the `;` is optional, so you don't  get any help from the compiler. The issue is easier to detect with tests, but still a bit unfortunate.

> I haven't built a large app with Akka, but when looking at the examples, it felt like the nested directive style would get very unwieldy with larger and larger apps. Have you noticed that?

You can split the route in multiple functions/files, and put part of its logic in small functions.

Thus, the route tree contains only the declarations to “interpret” the request. The code is also much easier to understand and to maintain.

For example:

```scala
// Auth.scala

case class Auth(...) {

  def userAuthenticator(creds: Credentials): Future[Option[User]] = ???

  // Directive to authenticate users
  def requireUser = authenticateBasicAsync(realm = "API", userAuthenticator)

}


// ProjecsAPI.scala

case class ProjecsAPI(...) {

  val auth = Auth()

  def listProjects(user: User) = ???

  def findProject(user: User, projectId: Int): Future[Option[Project]] = ???

  def deleteProject(project: Project): Future[Unit] = ???

  // Routes for /projects

  def routes = pathPrefix("projects") {
    auth.requireUser { user =>
      pathEnd {
        complete(listProjects(user))
      } ~
      path(IntNumber) { projectId =>
        onSuccess(findProject(user, projectId)) {
          case None => 
            complete(NotFound)

          case Some(project) =>
            get {
              complete(project)
            } ~
            delete {
              onSuccess(deleteProject(project)) {
                complete(NoContent)
              }
            }
        }
      }
    }
  }

}


// UsersAPI.scala

case class UsersAPI(...) {

  val auth = Auth()

  // Routes for /users

  def routes = pathPrefix("users") {
    auth.requireUser { user =>
      path("current") {
        complete(user)
      }
    }
  }

}


// Main.scala

val routes = (
  ProjecsAPI().routes ~
  UsersAPI().routes
  // ~ More().routes
)
Http().bindAndHandle(routes, "0.0.0.0", 8080)
```


([Full example](https://gist.github.com/ayosec/d08c0afacd38e8efc78c4028d9125f3b))
