### ISSUE TITLE
Cannot get CORS to work

### ISSUE THREAD

**Issue by jekelija** [seanmonstar/warp#271]
Attempting to do a basic login/auth from a React app to a Warp Server. However, I keep get a CORS error.

My main.rs looks like this (didnt include mods and uses for brevity):

```
fn main() {
    dotenv().ok();
    env_logger::init();
   // Get a filter that adds a session to each request.
    let pgsess = create_session_filter("host=localhost port=5432 dbname=medieval-realms connect_timeout=10 user=postgres password=Hufflepuff4life");
    let s = move || pgsess.clone();
    let signup = s().and(path("signup"))
                    .and(body::json())
                    .and_then(do_signup);

    let logout = s().and(path("logout"))
                    .and_then(do_logout);

    let login = s().and(path("login"))
                    .and(body::json())
                    .and_then(do_login);

    let create_game = s().and(path("create"))
                    .and(body::json())
                    .and_then(do_create_game);
    let join_game = s().and(path("join"))
                    .and(body::json())
                    .and_then(do_join_game);

    let game = warp::path("game").and(create_game.or(join_game));
    let cors = warp::cors()
        .allow_any_origin()
        .allow_headers(vec!["*"])
        .allow_methods(vec!["POST"]);

    let post = warp::post2().and(signup.or(logout).or(login).or(game)).with(cors);
    warp::serve(post).run(([127, 0, 0, 1], 3030));
}
```

I assume I'm not setting up the cors filter correctly somehow, because i get the error:

> Access to XMLHttpRequest at 'http://localhost:3030/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by seanmonstar** [comment]
Are you able to turn on logging for warp? And/or add a logger filter via `warp::log`?

**Comment by jekelija** [comment]
I actually cannot, as the most recent release of warp does not include the fix for https://github.com/seanmonstar/warp/issues?utf8=%E2%9C%93&q=cors. Is there a way for me to patch that in? Or another way to turn logging on?

**Comment by seanmonstar** [comment]
I've just published 0.1.20 which has that change. You can also turn on warp's internal logging, like if using something like `env_logger`, by setting `RUST_LOG=warp`.

**Comment by jekelija** [comment]
Hmm pulled down 0.1.20 and it seems to compile, but i am not seeing any logs coming out to console, or to a file?
`    let routes = post.with(cors).with(warp::log("cors test"));
`

**Comment by jekelija** [comment]
Also, i apologize in advance, this is my first foray into Rust, so a lot of the project setup and syntax is still a bit of a mystery to me.

**Comment by seanmonstar** [comment]
Oh, the way most logging works in Rust is libraries use the `log` crate, and apps can choose a *logger*. A simple one you can use is https://crates.io/crates/env_logger, which allows you turn on logging just through an environment variable. Others exist that allow more complex configuration if you like.

**Comment by jekelija** [comment]
Got the logs
`
     Finished dev [unoptimized + debuginfo] target(s) in 12.09s
     Running `target/debug/medieval-realms-server`
2019-09-18T15:46:18 [INFO] - warp drive engaged: listening on http://127.0.0.1:3030
2019-09-18T15:46:18 [DEBUG] - adding I/O source: 0
2019-09-18T15:46:18 [DEBUG] - scheduling Read for: 0
2019-09-18T15:46:32 [DEBUG] - scheduling Read for: 0
2019-09-18T15:46:32 [DEBUG] - adding I/O source: 4194305
2019-09-18T15:46:32 [DEBUG] - scheduling Read for: 1
2019-09-18T15:46:32 [DEBUG] - read 489 bytes
2019-09-18T15:46:32 [DEBUG] - parsed 12 headers
2019-09-18T15:46:32 [DEBUG] - incoming body is empty
2019-09-18T15:46:32 [INFO] - 127.0.0.1:61261 "OPTIONS /login HTTP/1.1" 403 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" 95.732µs
2019-09-18T15:46:32 [DEBUG] - rejected: Rejection(CorsForbidden { kind: HeaderNotAllowed })
2019-09-18T15:46:32 [DEBUG] - flushed 166 bytes
2019-09-18T15:46:32 [DEBUG] - scheduling Read for: 1

`

**Comment by seanmonstar** [comment]
Ah ok, the preflight request is rejected because one of the `Access-Control-Request-Headers` isn't allowed. I just now noticed you pass a `*` in the config, that doesn't allow all headers. You'd need to add the actual header names to allow.

**Comment by jekelija** [comment]
I've updated it to be:

>     let cors = warp::cors()
>         .allow_any_origin()
>         .allow_headers(vec!["User-Agent", "Sec-Fetch-Mode", "Referer", "Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers"])
>         .allow_methods(vec!["POST", "GET"]);

But still getting the same "HeaderNotAllowed" error. Looking at the network tab, i don't see any other headers:
![image](https://user-images.githubusercontent.com/1067894/65366660-05114880-dbf5-11e9-92e6-27ac2fa885fc.png)

Any other suggestions?

**Comment by seanmonstar** [comment]
The "allow headers" must contain the headers the browser sends in the `access-control-request-headers`. In your case, it's `content-type`.

**Comment by jekelija** [comment]
Ahhhhh! Thank you for your patience! That did the trick.

**Comment by sync** [comment]
solved my issue as well thanks @seanmonstar  ❤️

**Comment by sanket143** [comment]
didn't worked for me.

```rust
  let routes = health_route
    .or(register_routes)
    .or(ws_route)
    .or(publish)
    .with(warp::cors()
      .allow_any_origin()
      .allow_headers(vec![
        "Host",
        "User-Agent",
        "Accept",
        "Accept-Language",
        "Accept-Encoding",
        "Access-Control-Request-Method",
        "Access-Control-Request-Headers",
        "Referer",
        "Origin",
        "Connection",
        "Cache-Control",
      ])
      .allow_methods(vec!["GET", "POST", "DELETE", "OPTION"]));

```

```
OPTIONS /register HTTP/1.1
Host: localhost:41431
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Referer: http://127.0.0.1:8000/test.html
Origin: http://127.0.0.1:8000
Connection: keep-alive
Cache-Control: max-age=0
```

```
Status: 403 Forbidden
Version: HTTP/1.1
Transferred: 124 B (0 B size)
Referrer Policy: no-referrer-when-downgrade
```
Logs
```
[2020-08-02T18:26:55Z INFO  warp::server] Server::run; addr=V4(127.0.0.1:41431)
[2020-08-02T18:26:55Z INFO  warp::server] listening on http://127.0.0.1:41431 
[2020-08-02T18:28:11Z DEBUG warp::filter::service] rejected: Rejection(CorsForbidden(HeaderNotAllowed)) 
```

**Comment by Z4RX** [comment]
Your answers helped me a lot. Thanks @seanmonstar !

**Comment by Stalinium-Network** [comment]
hello, I have the same problem, I tried to fix the CORS error, but I can’t do it 


use mongodb::{bson::Document, options::ClientOptions, Client};
use std::sync::Arc;
use warp::Filter;
use warp::http::Method;

mod auth;
mod socket;


#[tokio::main]
async fn main() {
    let client_options: ClientOptions = ClientOptions::parse("mongodb://localhost:27017").await.unwrap();
    let client: Client = Client::with_options(client_options).unwrap();
    let db: mongodb::Database = client.database("myApp");
    let collection: mongodb::Collection<Document> = db.collection::<Document>("users");
    let shared_collection: Arc<mongodb::Collection<Document>> = Arc::new(collection);

    let shared_collection_clone = Arc::clone(&shared_collection);
    let with_collection = warp::any().map(move || Arc::clone(&shared_collection.clone()));


    let login_route = warp::post()
        .and(warp::path("login"))
        .and(warp::body::json())
        .and(with_collection.clone())
        .and_then(auth::auth::login);

    let register_route = warp::post()
        .and(warp::path("signup"))
        .and(warp::body::json())
        .and(with_collection)
        .and_then(auth::auth::register);


    let port = 3001;

    // CORS
    let cors = warp::cors()
        .allow_any_origin()
        .allow_headers(vec![
            "User-Agent", "Sec-Fetch-Mode", "Referer", "Origin",
            "Access-Control-Request-Method", "Access-Control-Request-Headers",
            "Content-Type" 
        ])
        .allow_methods(vec!["POST", "GET"]);

    //  for OPTIONS
    let options_route = warp::options()
        .map(|| warp::reply::with_header("OK", "Access-Control-Allow-Origin", "*"));

    // 
    let routes = login_route
        .or(register_route)
        .or(options_route)
        .with(cors);

    //  HTTP server
    let warp_server = warp::serve(routes).run(([127, 0, 0, 1], port));

    //  socketioxide server
    let socket_io_server = socket::io::main(shared_collection_clone);

    // run 2 servers 
    tokio::join!(warp_server, socket_io_server);
}
