### ISSUE TITLE
Updating to std::future::Future

### ISSUE THREAD

**Issue by xfix** [seanmonstar/warp#279]
Not sure how that would work (`IntoFuture` doesn't exist in futures 0.3, and because futures don't have to return `Result`s anymore, it cannot really exist), but being able to use futures 0.3 without `.compat()` would be useful.

**Comment by thomaseizinger** [comment]
It is being worked on already :)

https://github.com/seanmonstar/warp/pull/265

**Comment by xfix** [comment]
I see, I wasn't able to find this issue.
