### ISSUE TITLE
Example on crates.io does not compile

### ISSUE THREAD

**Issue by hjr3** [seanmonstar/warp#28]
On https://crates.io/crates/warp, I see the following example:

```rust
extern crate warp;

use warp::Filter;

fn main() {
    // GET /hello/warp => 200 OK with body "Hello, warp!"
    let hello = warp::path!("hello" / String)
        .map(|name| format!("Hello, {}!", name));

    warp::serve(hello)
        .run(([127, 0, 0, 1], 3030));
}
```

This does not compile for me using rust 1.28.0. It looks like it is a cross between using the `path!` macro and using the `warp::path` function.

**Comment by seanmonstar** [comment]
Yea, it was written with the new Rust 2018 macro syntax. It's currently fixed on master.

**Comment by seanmonstar** [comment]
With the publish of 0.1.1, the shown example should now be correct.

**Comment by Ran4** [comment]
The example code does not seem to work anymore, on Rust 1.39.0

### Code (retrieved from https://crates.io/crates/warp)

```rust
// src/main.rs
use warp::{self, path, Filter};

fn main() {
    // GET /hello/warp => 200 OK with body "Hello, warp!"
    let hello = path!("hello" / String)
        .map(|name| format!("Hello, {}!", name));

    warp::serve(hello)
        .run(([127, 0, 0, 1], 3030));
}
```

### Error(s)

```bash
$ cargo run
   Compiling warpexample v0.1.0 (/home/ran/src/rust/warp/warpexample)
warning: unused implementer of `core::future::future::Future` that must be used
 --> src/main.rs:6:5
  |
6 |     warp::serve(hello).run(([127, 0, 0, 1], 3030));
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
  = note: futures do nothing unless you `.await` or poll them

    Finished dev [unoptimized + debuginfo] target(s) in 8.42s
     Running `target/debug/warpexample`
                
```

### Version

`rustc 1.39.0 (4560ea788 2019-11-04)`

### Cargo dependencies

```toml
edition = "2018"

[dependencies]
warp = "0.2.0"
```

**Comment by jxs** [comment]
Hi, yeah crates.io uses the repo README.md as the frontpage for the crate, and the example was only updated on https://github.com/seanmonstar/warp/pull/384 after the release of 0.2.0, you can use the [README.md example](https://github.com/seanmonstar/warp#example)

**Comment by Ran4** [comment]
The crates.io example should probably include tokio dependencies too.
