### ISSUE TITLE
Could `Reject` trait be public?

### ISSUE THREAD

**Issue by dora-gt** [seanmonstar/warp#280]
When I was writing custom errors, it made me feel like "Why is the `Reject` trait private?" because if we could just return`Reject` trait as errors, it is more useful than creating custom `Rejection`s every time and handling these again in `recover` .

I've just started Rust, so I'm sorry if I'm saying something impossible.

**Comment by seanmonstar** [comment]
The reason for needing the `Rejection` type instead is due to `Filter::or` needing to be able to combine rejections if each side of the `or` rejects.

**Comment by dora-gt** [comment]
Thank you, I'm closing.
