### ISSUE TITLE
How to use Unix sockets with warp? (documentation request)

### ISSUE THREAD

**Issue by codesections** [seanmonstar/warp#282]
How can I use Unix sockets with Warp?  From the [relevant section of the documentation](https://docs.rs/warp/0.1.20/warp/struct.Server.html), I see that I should be able to use the `use_incoming` method, which is described like this:
> Run this Server forever on the current thread with a specific stream of incoming connections.
> This can be used for Unix Domain Sockets, or TLS, etc.

But, for some reason, I cannot figure out how to do so.  I have attempted to pass `use_incoming` a `std::os::unix::net::UnixListener` or a `std::os::unix::net::UnixStream`; neither worked.  I also tried passing it a String with the address of the socket, which also didn't work.  Can anyone point me in the right direction?

If anyone can help me figure this out, I'd be happy to submit a documentation PR with an example so that others aren't similarly confused in the future.

**Comment by remexre** [comment]
@codesections example in https://github.com/seanmonstar/warp/pull/332.
