### ISSUE TITLE
struggling to efficiently proxy cached String between reqwest + warp

### ISSUE THREAD

**Issue by jakswa** [seanmonstar/warp#283]
:wave: newer rust dev here

Is there a minimal-allocation path between taking a `reqwest::Response` and proxying it to `warp::Reply`? Right now I'm doing `text()` and then upon needing it I `.clone()` that `String` fresh, but I want to avoid that allocation as it might be tens of kB of string.

(code from [this repo](https://github.com/jakswa/warp_proxy/issues/1))
```rust
 // read from cache if it's still valid, otherwise hit the URL + write 
 fn cache_visit(cache: Store) -> impl warp::Reply { 
     let mut timed_string = cache.lock().unwrap(); 
     if Instant::now() > timed_string.time { 
         timed_string.time = Instant::now() + Duration::from_secs(10); 
         timed_string.text = reqwest::get(&timed_string.url).unwrap().text().unwrap(); 
     } 
     timed_string.text.clone() 
 }
```

The answer I'm missing feels obvious (the docs describe a flexible `warp::Reply` trait that I'm struggling to understand). I'm hoping this is a quick-win of a question.

For more context, I took the [todos example](https://github.com/seanmonstar/warp/blob/master/examples/todos.rs) and tried to turn it into a http proxy which caches the proxied payload for 10s. I've taken a stab at this proxy few times in rust, and Warp is definitely the farthest I've gone with the most-readable output IMO, so thanks a ton for this library!

edit: I tried to lay this issue out briefly and get community input over [here](https://users.rust-lang.org/t/warp-trying-not-to-clone-a-string-hacktoberfest-opportunity/33283) and [here](https://github.com/jakswa/warp_proxy/issues/1), but so far I got nothing. If you'd rather close this and take the convo to one of those, feel free.

**Comment by seanmonstar** [comment]
You could use the `bytes` crate, it provides a `Bytes` type that you can create from a string (or other things) that is ref-counted. You could also make some newtype `Cached(Arc<String>)`, but `Bytes` already has support in hyper/warp.

**Comment by jakswa** [comment]
awesome, thank you, I'll give that a shot

**Comment by jakswa** [comment]
update: looks like it works! Thanks again. For future reference, the above method turned into this and seems to work so far (haven't benchmarked or anything yet):
(note: left out the struct definition changes to get `Bytes` on it)
```rust
 // read from cache if it's still valid, otherwise hit the URL + write 
 fn cache_visit(cache: Store) -> impl warp::Reply { 
     let mut timed_string = cache.lock().unwrap(); 
     if Instant::now() > timed_string.time { 
         timed_string.time = Instant::now() + Duration::from_secs(10); 
         timed_string.text = Bytes::from(reqwest::get(&timed_string.url).unwrap().text().unwrap());
     } 
     Response::new(timed_string.text.clone()); // this is from `use warp::http::Response`
 }
```

I have yet to benchmark this, but from my reading `.clone()` on Bytes only clones the reference, not the underlying data. :crossed_fingers:
