### ISSUE TITLE
Add tracing support

### ISSUE THREAD

**Issue by emschwartz** [seanmonstar/warp#288]
I'd like to use [`tracing`](https://github.com/tokio-rs/tracing/) with a `warp` API. Do you have any recommendations about the best way to do this? Should there be a `Wrap` for tracing like the `Log` one, or should `Filter` implement `tracing-futures::Instrument`?

I'm happy to work on a PR for this if I can figure out the right direction (and if you think this should be added to warp).

Thank you!

**Comment by emschwartz** [comment]
Once https://github.com/tokio-rs/tracing/pull/386 is merged, it will be possible to enable support for tracing by implementing:

```
impl<T> Filter for Instrumented<T>
where
  T: Filter
{
...
}
```

This would allow `warp` users to call `filter.instrument(debug_span!("in warp filter"))` and include all events logged (with `log` or `tracing`) when the filter is called in a given `span`.

**Comment by emschwartz** [comment]
@seanmonstar if you'd be open to a PR on this, I'd be happy to put one together

Let me know if you have any thoughts on how it should be implemented

**Comment by seanmonstar** [comment]
Sorry, my context of exactly how `tracing` works is quite low. What would warp need to provide for it to work? It can't work without warp doing something?

**Comment by emschwartz** [comment]
I'm not an expert on it either but I think the three options for how it could be integrated would be:
- Implement `FilterBase` for [`Instrumented<T: FilterBase>`](https://docs.rs/tracing-futures/0.1.0/tracing_futures/struct.Instrumented.html)
- Make `FilterBase` public to allow writing custom `Filter`s
- Add a way to wrap a `Filter` with some function that has access to the request and response when that `Filter` is called

**Comment by emschwartz** [comment]
I took a stab at implementing the first option [here](https://github.com/emschwartz/warp/tree/es-tracing) but can't seem to figure out why the `tracing` `Span` isn't being propagated all the way through. If anyone has ideas, I'd be very open to suggestions!
