### ISSUE TITLE
Authorization header filter that uses `secrecy` types

### ISSUE THREAD

**Issue by emschwartz** [seanmonstar/warp#289]
Would you be open to adding a filter for the `Authorization` header that uses the [`SecretString`](https://docs.rs/secrecy/0.5.0/secrecy/type.SecretString.html) type from [`secrecy`](https://crates.io/crates/secrecy)?

I'd understand if you don't want to add additional dependencies but parsing the auth header as plaintext is a big potential footgun because it can be accidentally printed or returned in some API error message.

**Comment by seanmonstar** [comment]
While that crate does look cool, I'm not sure I'd want to expose it as a public dependency.

You can get part way there using `http::HeaderValue::set_sensitive`...

**Comment by emschwartz** [comment]
Ok, worth asking :man_shrugging:
