### ISSUE TITLE
Providing parameters to websocket closure

### ISSUE THREAD

**Issue by caolan** [seanmonstar/warp#29]
I'd like to use a path parameter from the update request inside the websocket handling code, but the current API doesn't provide an easy way to do that:

```rust
warp::path("example")
    .and(warp::path::param())
    .and(warp::ws(|websocket| {
        // cannot access path parameter easily here
    }))
```

**Comment by seanmonstar** [comment]
Hm, possibly the design of the `ws` filter could be changed, to not use a closure when building, but rather to attach how to handle the upgraded websocket in `map`...

```rust
warp::path::param()
    .and(warp::ws())
    .map(|param: MyParam, ws: Ws| {
        ws.on_upgrade(move |websocket| {
            // moved `param` in here...
        })
    })
```

That'd change the `Ws` to not `impl Reply`, and instead, calling `Ws::on_upgrade` would return the `impl Reply`.

**Comment by seanmonstar** [comment]
Done in #34
