### ISSUE TITLE
Graceful shutdown not working reliably

### ISSUE THREAD

**Issue by michael-p** [seanmonstar/warp#290]
Dear all,

I'm seeing a weird behvior with `Server::bind_with_graceful_shutdown()` where depending on the browser making Http-Requests the server does not shut down. Consider the following example:
```rust
use futures::sync::oneshot;
use std::{thread, time::Duration};
use warp::Filter;

fn main() {
    let index = warp::path::end().map(|| "Hello world");
    let (shutdown_tx, shutdown_rx) = oneshot::channel();
    let web_thread = thread::spawn(move || {
        println!("Webserver thread starting");
        let (_, server) =
            warp::serve(index).bind_with_graceful_shutdown(([0, 0, 0, 0], 8080), shutdown_rx);
        tokio::run(server);
        println!("Webserver thread stopped");
    });

    // Let server run for some time - please make a few Http calls now! :)
    thread::sleep(Duration::from_secs(10));

    println!("Requesting shutdown...");
    shutdown_tx.send(()).expect("shutdown webserver");
    web_thread.join().unwrap();
    println!("Done")
}
```
Now, when I run this example and make a few http requests during the 10 seconds window with **Firefox** or **Safari**, the example prints
```
Webserver thread starting
Requesting shutdown...
Webserver thread stopped
Done
```
as expected. However, if I do exactly the same with **Chrome** then the server does not shutdown. As soon as I close Chrome, the server shuts down (just closing the browser tab is not enough).

Is there a way to make the graceful shutdown a bit less graceful? I guess this problem is due to some tcp/ip keep-alive but still, I would prefer the server to still shutdown in this case.

This happens with warp version 0.1.20 on macOS 10.14.6, Chrome 77.

**Comment by seanmonstar** [comment]
I think there may be a bug in hyper about calling `Connection::graceful_shutdown`. I noticed this happening in a branch recently in hyper master, and I fixed what i was seeing there, but it may be hard to backport the fix to warp 0.1.x.

**Comment by clintnetwork** [comment]
How to make a graceful shutdown only using run()?

**Comment by seanmonstar** [comment]
The warp v0.2 release upgrades hyper, so this should be fixed.

**Comment by clintnetwork** [comment]
Really nice!
