### ISSUE TITLE
[DOC REQUEST] Steps for how to build Warp with TLS support

### ISSUE THREAD

**Issue by silvioprog** [seanmonstar/warp#292]
Hi.

It would be nice some documentation (Github wiki?) for how to build Warp with TLS support.

Another interesting information would be to inform if websocket works under TLS.

Thank you!

**Comment by jxs** [comment]
Hi, did you see the [tls example](https://github.com/seanmonstar/warp/blob/master/examples/tls.rs) ?

**Comment by silvioprog** [comment]
@jxs this is exactly I'm looking for. Thank you very much!
