### ISSUE TITLE
How can I write a middleware to collect metrics (duration and status code)

### ISSUE THREAD

**Issue by bbigras** [seanmonstar/warp#295]
I would like to collect metrics (for prometheus) for every requests.

Is `Filter` used to write middlewares?

**Comment by seanmonstar** [comment]
There's a middleware already available to get some of those things: [`warp::log::custom()`](https://docs.rs/warp/0.1.20/warp/filters/log/fn.custom.html).

A more generic middleware approach is still not available.

**Comment by serejkaaa512** [comment]
Is it possible to log requests and responses jsoned bodies?
