### ISSUE TITLE
Returning unit from map or and_then is weird

### ISSUE THREAD

**Issue by seanmonstar** [seanmonstar/warp#3]
While warp usually handles unit `()` from built-in `Filter`s quite well, if a user tries to `map` (or `and_then`) a `Filter` and return nothing, the unit is no longer dropped.

Example

```rust
warp::any()
    // unit was dropped, no arg needed
    .map(|| {
        println!("no returning anything");
    })
    // return of `map` was auto-wrapped in `(T,)`, becoming `((),)`
    .map(|((),))| {
        println!("gross");
    })

```

**Comment by seanmonstar** [comment]
A possible fix is used internally, the `unit()` combinator. That could be made public, but it feels bad...

**Comment by Reconcyl** [comment]
Another option: add a specialized method for `()` that simply discards it. I would suggest calling it `inspect` after [`std::iter::Iterator::inspect`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.inspect).
