### ISSUE TITLE
Push an update on Crate.io

### ISSUE THREAD

**Issue by FedericoPonzi** [seanmonstar/warp#308]
Hello,

I would like to try out warp with the new hyper and all the goodies of the new futures, but on crates.io the last update was 2 months ago.
I don't know how much time would require, but could you please push a new release? I know I can go with the git repo, but I would rather not.

Thanks for the awesome library though :) it's really fun to use!

**Comment by jxs** [comment]
Hi Federico,
a new release is [getting ready](https://twitter.com/seanmonstar/status/1192166709391552512)!
in the meanwhile you can depend on warp from the git repository to have access to the new async await version

**Comment by FedericoPonzi** [comment]
Awesome, looking forward to it! Thanks for the fast response.
