### ISSUE TITLE
Limit request body size

### ISSUE THREAD

**Issue by dominikwerder** [seanmonstar/warp#326]
What is the best way to limit a request's body size?

`warp::filters::body::content_length_limit` checks the http header, but what about malicious requests? Or does hyper already check the correctness of the content-length header?

**Comment by seanmonstar** [comment]
hyper will treat the `content-length` according to RFC 7230: once `$content_length` bytes have been read, the message body is complete. Any bytes after that are assumed to be part of a new message. hyper will handle backpressure by not reading the next request until you have responded to the first one.
