### ISSUE TITLE
Why are HTTP methods suffixed with 2?

### ISSUE THREAD

**Issue by polarathene** [seanmonstar/warp#328]
In some of the examples provided there is a `2` as a suffix to HTTP methods, but this doesn't appear to be explained to new users what is going on with that?

Looks like it is referred to as `v2` and [discussed here](https://github.com/seanmonstar/warp/pull/21#issuecomment-411113974)?

I came across these `v2` variants in the docs [here](https://docs.rs/warp/0.1.20/warp/filters/method/v2/index.html), but the [related docs appear to just import `warp::Filters` and use the suffixed `2` variants](https://docs.rs/warp/0.1.20/warp/filters/method/v2/fn.post.html), even though the docs for that module have no suffix on them? It's a little confusing. [Moving up the module path in the docs](https://docs.rs/warp/0.1.20/warp/filters/method/index.html), this appears to be due to `v2` being re-exported with the `2` suffix? 

**I think my confusion may have come from seeing examples of current stable and development(master) branches.** `body.rs` example [stable](https://github.com/seanmonstar/warp/blob/0.1.x/examples/body.rs) vs [master](https://github.com/seanmonstar/warp/blob/master/examples/body.rs) shows that the `2` suffix is removed now? So this will be going away in a future release?

**Comment by seanmonstar** [comment]
Yes, the 2 suffix was because the first version of those filters was odd, and the second version made them behave like all the rest (but was a breaking API change). In the next version coming real soon, we were able to replace the first version with the second and remove the prefix.
