### ISSUE TITLE
Use a filter extract in later Or branches

### ISSUE THREAD

**Issue by dominikwerder** [seanmonstar/warp#329]
What is the best way to use extracted parameters in different inner branches of `or` ?

```rust
warp::path("api")
.and(
  warp::path::param::<u32>()
  .and(
      warp::path("cats")
      .map(|| format!("u32 value?"))
    .or(
      warp::path("dogs")
      .map(|| format!("u32 value?"))
    )
  )
)
.map(|_, x| x)
```

Written in this way I can not access the `u32` in the inner branches.

I've tried so far to look for a way to `map` the `u32` into a new filter chain, but I can not "flatten" that subchain into the main chain to get it executed.

`ext::get` and `ext::set` work but it seems more brittle than it could be because of the possible panic.

**Comment by khigia** [comment]
The inner `map` is applied only to a sub filter and cannot see the param. So `map` has to be applied after the matching at the same level. For this simple case, something like below would probably achieve it:
```
warp::path("api")
        .and(warp::path::param::<u32>())
        .and(warp::path("cats"))
        .map(|cat_param| format!("u32 value {}", cat_param))
        .or(warp::path("dogs"))
        .map(|dog_param| format!("u32 value {}", dog_param));
```

**Comment by m-lima** [comment]
@khigia Seems like the concept above doesn't work.
The first `map` function (after the path "cats") is able to handle the parameter (it comes as a **String**), but `dog_param` gets typed as `warp::generic::Either<(String,), ()>`, which is not the output of `warp::path::param::<u32>()` (or even **Display**able for that matter).

So it seems like the above pattern does not work. Are there extra steps required?
How can you achieve what OP was interested in?

**Comment by khigia** [comment]
Ooops. You are right @m-lima , my solution does not work. Lesson learnt, following code is tested :).

An alternative is to factor the code (but internally warp would still try both Filter one after another instead of factoring the common base parsing):

```
let common = warp::path::param::<u32>();
let route_cats = common
    .and(warp::path("cats"))
    .map(|cat_param| format!("u32 CATS value {}", cat_param));
let route_dogs = common
    .and(warp::path("dogs"))
    .map(|dog_param| format!("u32 DOGS value {}", dog_param));
let routes = warp::path("api").and(route_cats.or(route_dogs));
```

Maybe it make sense to keep `map` having access only to the `Filter` it is applied to (and not its containing Filter). If really the common part of path make sense, then the code itself could make 
sure it handle it in a common way, like in following where only the Filter where `n` is defined is receiving it while mapping:

```
    #[derive(Debug)]
    enum Animal {
        Cat,
        Dog,
    };

    let routes = warp::path("api")
        .and(warp::path::param::<u32>())
        .and(
            warp::path("cats").map(|| Animal::Cat)
            .or(warp::path("dogs").map(|| Animal::Dog))
            .unify(),
        )
        .map(|n, kind| match kind {
            Animal::Cat => format!("u32 value {} CAT", n),
            Animal::Dog => format!("u32 value {} DOG", n),
        });
```

**Comment by m-lima** [comment]
Thanks, @khigia 
That's a great summary and it clears up the confusion I had on my side :)
It seems like the filter pattern is not the best for this use case (if you have an "expensive" common filter that is)
