### ISSUE TITLE
Custom Failure / error handling

### ISSUE THREAD

**Issue by kamek-pf** [seanmonstar/warp#33]
Hey,
Really like what you did !

Say I want to define very rich, specific errors, I usually do this with `failure`.
I'd like to be able to return my own custom failures in the `and_then` combinator, and then either simply log them or present a detailed error page.

Do you currently have a way to do this ? Is it a goal at all ?
Maybe I just have the wrong approach, what would you recommend to deal with this ?

**Comment by seanmonstar** [comment]
As of 0.1.0, warp only allows errors back into the filter chain that are `warp::Rejection`s. You can create your own futures, and your own errors, definitely, you'll just need to map your custom errors into an appropriate `Rejection`. Take look at the [errors example](https://github.com/seanmonstar/warp/blob/master/examples/errors.rs).

I do think it'd probably be nice to expand the rejection system to allow for better typed application errors, but I don't yet know the best way to do so.
