### ISSUE TITLE
Clarify use of `#[tokio::main]`

### ISSUE THREAD

**Issue by hwchen** [seanmonstar/warp#339]
This is also an issue in https://github.com/hyperium/hyper/issues/2028.

Basically, the `#[tokio::main]` macro is used for examples but the dependency is not explicitly mentioned in readme or docs. Could be pretty confusing (I have at least one person who copied over the `hello world` example and it didn't work.

Also, the dep should look something like:
```
tokio = { version = "0.2.3", features = ["macros"] }
```

**Comment by EverlastingBugstopper** [comment]
+1 - I'd also recommend providing an alternative example that shows how you can create a new tokio runtime without `#[tokio::main]`

**Comment by iammichiel** [comment]
I am not yet familiar with the `async`/`await` syntax but is the Tokio runtime required to run an async main function ?

**Comment by seanmonstar** [comment]
I've updated the README to include instructions about adding Tokio as a dependency.
