### ISSUE TITLE
Where is the right place for support / asking questions?

### ISSUE THREAD

**Issue by shepmaster** [seanmonstar/warp#347]
Is filing individual issues for each question the right thing? Is there a forum / chat service that people using warp congregate around? It would be great to list this type of thing on the README...

**Comment by jxs** [comment]
Hi!
there isn't yet a forum/chat service to ask questions about warp, most of the users do it via issues yeah, but maybe it's time to get a chat for warp. 
What do you think @seanmonstar ?

**Comment by gperinazzo** [comment]
Having a chat would be really nice :+1:

**Comment by seanmonstar** [comment]
I'd love to, it mostly feels quite in flux at the moment.

- Mozilla's IRC is shutting down in a couple months.
- Gitter is unreliable.
- I personally really dislike Discord.

I'd consider moving to Matrix, though I don't know yet where is a good place to host a free chat.

**Comment by asonix** [comment]
Synapse doesn't take a ton of resources to run, but it does take a ton of resources to run _well_. I'd suggest a fairly cheap (but not the cheapest tier) VPS if you want to do something like matrix.warp.rs. I'd also suggest hosting riot (a matrix web interface) at chat.warp.rs with the server defaulting to matrix.warp.rs so people have an easier time signing up and talking, and you have something to link to

**Comment by Karlinde** [comment]
You could just create a public room for warp on the matrix.org homeserver. There are thousands of random rooms there, and I follow several projects that coordinate and chat in their own rooms there without having to host their own servers.

**Comment by rtyler** [comment]
I went ahead and created `#warp-rs:matrix.org` ([link](https://matrix.to/#/!RpXuGZxOjokbxeDwIF:matrix.org?via=matrix.org))

If @seanmonstar or @carllerche, I'll be sure to make them admins

**Comment by carllerche** [comment]
Given the overlap in users, I created `#hyper` and `#warp` channels in the Tokio discord server: https://discord.gg/tokio

These can be "unofficial" until an official location lands.

**Comment by giganteous** [comment]
zulipchat, greatest chat for async work IMHO.

**Comment by MikeCamel** [comment]
You might want consider rocket.io.  They are also quite generous about free resources for open source projects on occasion.  They've donated resources for us ([https://chat.enarx.io/](https://chat.enarx.io/) - soon moving to [https://chat.enarx.dev/](https://chat.enarx.dev/).

**Comment by seanmonstar** [comment]
I'm still not 100% sold, but it seems like the current best thing is to continue using the `#warp` channel on https://discord.gg/tokio.

I'll add a badge to the README to close this issue out.
