### ISSUE TITLE
`.map` reply with a Future.

### ISSUE THREAD

**Issue by norcalli** [seanmonstar/warp#35]
If we were implementing something like a proxy (which might be a good example to add), you would want to issue a request that would return a Future. I'm not exactly sure which combinator to use with it. I thought it would be `.and_then`, but the example is geared towards validation and returning a `CombineReject`, and I believe that `map` doesn't accept a future.

**Comment by seanmonstar** [comment]
The `and_then` combinator is meant for returning a `Future`. The validation part is just that a user needs to explicitly handle their `Future`'s error, and convert it into an appropriate rejection (or reply, if that's preferred).

**Comment by norcalli** [comment]
Ah, ok. I got it working, I believe. Essentially, as long as I `map_err` into `warp::reject()` or the like, it's accepted. The error message was a bit opaque, especially since `CombineRejection` is a sealed trait. For future reference, this is a working snippet from my code:
```
use std::time::Duration;

use futures::prelude::*;
use futures_timer::Delay;

use warp::Filter;

fn gpu_task(input: String) -> impl Future<Item = String> {
    Delay::new(Duration::from_millis(100)).map(move |()| input)
}

fn main() {
    let route = warp::path("batch")
        .and(warp::filters::body::json())
        .and_then(|input: String| {
            gpu_task(input)
                .map(|output| warp::reply::json(&output))
                .map_err(|_| warp::reject::server_error())
        });

    warp::serve(route).run(([0; 4], 3030));
}
```
