### ISSUE TITLE
warp::body::stream() fillter example for async

### ISSUE THREAD

**Issue by madmaxio** [seanmonstar/warp#362]
Can you pease provide a working example for warp::body::stream() filter. I found an older issue but can't compile it for master. The error says chunk  doesn't have a size known at compile-time for my code
```
async fn handle_upload<S>(stream: S) -> impl warp::Reply
    where
        S: Stream<Item = Buf>        
{
    let s = stream.for_each(|chunk| {            
        async move {        
        }
    });

    
    async move {        
    };

    Response::builder().body("hi").unwrap()
}

```

**Comment by seanmonstar** [comment]
There's a [unit test](https://github.com/seanmonstar/warp/blob/4687c03ed9620e1ae8aaa4fd6cbd8e100091e584/tests/body.rs#L180-L196) that might help. What would want to do that's different from `warp::body::bytes()`?

**Comment by madmaxio** [comment]
I need to handle large file upload. warp::body::bytes() pull all the data into memory, while I need to stream of small chunks of bytes.

**Comment by seanmonstar** [comment]
You can either use `impl Trait` in argument position:

```rust
async fn handle_upload(stream: impl Stream<Item = Result<impl Buf, warp::Error>>) -> impl warp::Reply
```

Or add another generic:

```rust
async fn handle_upload<S, B>(stream: S) -> impl warp::Reply
where
    S: Stream<Item = Result<B, warp::Error>>,
    B: Buf,
```
