### ISSUE TITLE
Expose internal HTTP error types

### ISSUE THREAD

**Issue by aksiksi** [seanmonstar/warp#364]
As far as I can tell, the only accessible rejection type is `not_found`.  The rest are kept internal to the crate.  

Is there any reason why these can't be exposed for external use?  Or is the intention that users always need to implement custom errors for relevant HTTP status codes?

**Comment by jxs** [comment]
Hi
> Is there any reason why these can't be exposed for external use? Or is the intention that users always need to implement custom errors for relevant HTTP status codes?

Reply is also implemented for [StatusCode](https://github.com/seanmonstar/warp/blob/master/src/reply.rs#L403)  so you can return them directly:

```Rust 
async fn reply_unauthorized() -> Result<StatusCode, warp::Rejection> {
    Ok(StatusCode::UNAUTHORIZED)
}

#[tokio::main]
async fn main() {
    let routes = warp::any().and_then(reply_unauthorized);

    warp::serve(routes).run(([127, 0, 0, 1], 3030)).await;
}
```

**Comment by aksiksi** [comment]
Damn, not sure how I missed that.  Thanks!
