### ISSUE TITLE
Example does not compile (CI issue?)

### ISSUE THREAD

**Issue by codesections** [seanmonstar/warp#365]
The `unix_socket` example added in #332 (thanks for that, @remexre, by the way!) does not currently compile.  With the current master, I get error in the screenshot below:
![image](https://user-images.githubusercontent.com/35405463/71938222-baecac80-317c-11ea-9c34-8d8bd63a2979.png)

This raises a couple of related issues.  First, how should this example be updated to compile properly/be a valid example?

Second, why did this compilation failure not cause the build to fail?  I *suspect* that the build didn't fail because the `unix_socket` example was excluded due to a feature mismatch.  Note the command above ended with `--features="tokio/uds"`.  I added this because, when I tested the example without it, I was given an error stating that the `unix_socket` target required that feature.  Could that error be causing CI tests to skip the example without registering a failure?

If so, are any other tests being inadvertently skipped?

**Comment by seanmonstar** [comment]
I think the problem is that `incoming` just borrows from the listener, but we don't store it in a local slot. The fix probably just requires splitting that line to so we store `let mut listener = ...`, and then can say `let incoming = listener.incoming()`.
