### ISSUE TITLE
update websocket filter to use tokio-tungstenite

### ISSUE THREAD

**Issue by jxs** [seanmonstar/warp#366]
now that [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite/) has been updated to `std::futures` we could update the websockets filter to use it instead, should we wait for it to be published though?

**Comment by seanmonstar** [comment]
I can't remember why I removed the support before... What do we gain by adding it back? Less code to maintain?

**Comment by jxs** [comment]
yeah, also less `unsafe` in the codebase  since their implementation no longer has unsafe, and tls support for websockets afaik

**Comment by jxs** [comment]
fixed with #430
