### ISSUE TITLE
warp::filters::ws::Message::ping() not functioning

### ISSUE THREAD

**Issue by codesections** [seanmonstar/warp#368]
I am attempting to use the code I previously contributed to send WebSocket ping messages, but it does not appear to function.

Specifically, constructing a `ping` message and then sending it through an existing WebSocket connection does not result in the client receiving that ping.

I am working around the issue by sending text messages as a less-elegant form of a keep-alive ping, but wanted to raise it here—especially given that I contributed the code that doesn't seem to work correctly.

**Comment by seanmonstar** [comment]
It might be that there is [code that specifically ignores sending pings](https://github.com/seanmonstar/warp/blob/4687c03ed9620e1ae8aaa4fd6cbd8e100091e584/src/filters/ws.rs#L329-L337) 😆 

We should probably add a unit test to `tests/ws.rs` when fixing this.
