### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by seanmonstar** [seanmonstar/warp#373]
I can't think of anything else blocking the release. @jxs can you?

**Comment by jxs** [comment]
only #318 I think, do you want me to update it and resolve conflits, or do you prefer to derive from it?

**Comment by seanmonstar** [comment]
For #318, I don't yet know what the `Certificate` type should look like. I think we can punt, since it's possible to create that functionality outside warp now, combining `warp::service` and extensions.

**Comment by jxs** [comment]
ok, great! let's release 0.2 then 🙌🏻
