### ISSUE TITLE
Implement Reply for Result<T, E> where E: Reply

### ISSUE THREAD

**Issue by kdy1** [seanmonstar/warp#391]
Currently, only Result<T, http::Error> implements Reply, but some error can be changed into http response. I'll send a pr.

**Comment by jxs** [comment]
Hi, 
to achieve that you need to wrap your Error with [`warp::reject::custom`](https://docs.rs/warp/0.2.0/warp/reject/fn.custom.html) you can see an example of that on the [`rejections`](https://github.com/seanmonstar/warp/blob/master/examples/rejections.rs) example

**Comment by kdy1** [comment]
@jxs Oh. I didn't know that. Thank you! Closing..
