### ISSUE TITLE
SSE Chat Example is incorrect

### ISSUE THREAD

**Issue by Koxiaet** [seanmonstar/warp#394]
So the [SSE example](https://github.com/seanmonstar/warp/blob/master/examples/sse_chat.rs) has the following code:
```rust
    // Create channel to track disconnecting the receiver side of events.
    // This is little bit tricky.
    let (mut dtx, mut drx) = oneshot::channel::<()>();

    // When `drx` will dropped then `dtx` will be canceled.
    // We can track it to make sure when the user leaves chat.
    tokio::task::spawn(async move {
        dtx.closed().await;
        drx.close();
        user_disconnected(my_id, &users2);
    });
```
Which does not actually do anything - `dtx` and `drx` are both moved into the task, which runs and never completes. As a result, no clients are ever disconnected from the server (I tested this).

I think the SSE example needs major changes in order to allow clients to be disconnected, as far as I can tell from the docs.

**Comment by jxs** [comment]
yeah, it also seems outdated regarding the `Mutex` use, can be switched to the `tokio::sync::Mutex` would you like to try and PR an update to it?
