### ISSUE TITLE
Add a trait FromRequest

### ISSUE THREAD

**Issue by kdy1** [seanmonstar/warp#398]
With the help of a proc macro (#395), such trait will be very useful. I'm currently experimenting with it at https://github.com/kdy1/rweb/pull/5.

Trait definition will be
```rust
pub trait FromRequest: Sized {
    type Filter: Filter<Extract = (Self,), Error = Rejection>;

    fn new() -> Self::Filter;
}
```
and this trait should be exposed, thus the user can implement it. Type inference is not a problem at all, as proc macro suggested by #395 can insert a fully qualified path.

```rust
use rweb::{filters::BoxedFilter, *};

impl FromRequest for User {
    type Filter = BoxedFilter<(User,)>;

    fn new() -> Self::Filter {
        // In real world, this can be changed to use Authorization header
        header::<String>("x-user-id").map(|id| User { id }).boxed()
    }
}

struct User {
    id: String,
}

#[get("/")]
fn index(user: User) -> String {
    user.id
}

```

It also allows using `filters::ws::Ws` without any annotation and provides more natural syntax for forms.

```rust
#[post("/json")]
fn json(body: Json<LoginForm>) -> Result<String, Error> {
    Ok(serde_json::to_string(&body).unwrap())
}
```

looks much more natural than

```rust
#[post("/json")]
fn json(#[json] body: LoginForm) -> Result<String, Error> {
    Ok(serde_json::to_string(&body).unwrap())
}
```

**Comment by seanmonstar** [comment]
Is such a trait actually required in warp, or can the macros crate just provide it?

**Comment by kdy1** [comment]
> Is such a trait actually required in warp, or can the macros crate just provide it?

It should be supported by runtime. Being in warp does not matter.
