### ISSUE TITLE
How to gracefully shutdown server when endpoint hit

### ISSUE THREAD

**Issue by keirlawson** [seanmonstar/warp#399]
I'm trying to figure out how one could shut down a warp server when a served endpoint is hit.  As `map` on `Filter` takes an `Fn` rather than an `FnMut` it seems that I can't use a Tokio `mpsc` to signal the shutdown, any suggestions?

**Comment by seanmonstar** [comment]
You could clone the `Sender` and then call `send`.

```rust
let filter = warp::path!("quitquitquit").map(move || {
    let mut tx = tx.clone();
    drop(tx.try_send(()));
});
```

**Comment by keirlawson** [comment]
That was it, thanks for your help :)
