### ISSUE TITLE
Add multipart filters

### ISSUE THREAD

**Issue by seanmonstar** [seanmonstar/warp#40]
It would be nice to include some built-in filters in `warp::multipart` (or `warp::body`?). I'm not sure what the API should look like. Some things that come to mind that a user could want to do:

- Decode a multipart body via `serde::Deserialize`.
- Receive a file upload.
- Receive multiple file uploads.
- Allow streaming of the data, since buffering an entire file upload in memory could be bad if the files are huge.

**Comment by abonander** [comment]
I looked through `warp`'s docs when you announced it to see if integration with `multipart` was feasible but I found that the `Filter` trait is designed not to allow outside implementors since `FilterBase` isn't exported. Was this a deliberate design decision and, if so, is it a permanent one?

**Comment by seanmonstar** [comment]
Yes, `Filter` is a sealed trait for now, since I suspect there might need to be some breaking changes to its internal method (during development, I iterated a few times with passing different arguments to `Filter::filter`). New filters can be created by combining with `map` or `and_then`. If wanting to turn just *any* value into a filter, it can be done with `warp::any()`.

For example:

```rust
let port = warp::any().map(|| env!("PORT"));
```

**Comment by abonander** [comment]
I see. I think `multipart` could provide a `impl Filter` helper wrapping `filter::header::<ContentType>()` and some hypothetical streaming body filter. The latter I think is all that really needs to be implemented for me to start experimenting on my end. I could use `body::concat()` if I really needed to, I guess.

**Comment by abonander** [comment]
>Decode a multipart body via serde::Deserialize

I looked into this but `serde` isn't really designed for push- or poll-based interfaces like async APIs. 

I pitched [this idea on the Gotham-rs issue board](https://github.com/gotham-rs/gotham/issues/11#issuecomment-373565350) about a derive-based solution to form processing that included validation, but I haven't really gotten anywhere with prototyping it yet.

**Comment by seanmonstar** [comment]
> some hypothetical streaming body filter

I'm adding a `warp::body::stream()` filter right now :D

> I looked into this but serde isn't really designed for push- or poll-based interfaces like async APIs.

Yea, I've also looked because I was curious asynchonously deserializing a stream of JSON. At least in `serde_json`, it kind of looks like it could be possible, with `StreamingDeserializer`, as the comments suggest one could try again if the deserializer returns an EOF error.

Still, it might be useful for accepting form-data that *doesn't* include a file.

**Comment by abonander** [comment]
> Still, it might be useful for accepting form-data that doesn't include a file.

Of course you can pick the encoding type when displaying a form or I think invoking cURL but typically if the form doesn't include a file field then it shouldn't be encoded as `multipart/form-data`, that's just a bunch of overhead for zero gain. I would probably not even have a request endpoint that can accept urlencoded OR multipart, the complexity isn't worth it.

**Comment by abonander** [comment]
> Still, it might be useful for accepting form-data that doesn't include a file.

I deleted my original reply because I thought "duh, you can have *optional* file fields and thus get multipart request bodies that don't contain files" but if you're expecting a multipart body without any possible file fields then that's a lot of overhead for zero gain compared to urlencoding. Do you have a use-case in mind or is it more just supporting every possibility? If the client submitted a multipart body where urlencoding was expected it'd probably be better to emit an error unless you want to adhere to the "strict in what you send, liberal in what you accept" rule.

**Comment by seanmonstar** [comment]
No, I don't have an exact use case, I was kind of assuming that if you used `FormData` in JavaScript, or `<form>`, it could use `multipart/form-data` without a file, but I don't have any proof.

**Comment by abonander** [comment]
Anything is possible, of course. You can specify `enctype="multipart/form-data"` without needing a file field and the docs for `FormData` say it encodes to `multipart/form-data` (I think `URLSearchParams` encodes to `www-form-urlencoded`). 

But that's why instead of Serde, I was conceiving of using a custom derive designed for form data, since you could also include files in your deserialized form type and the framework would just handle it. The idea was to eventually integrate with a renderer/template engine as well so the generated HTML form matched the expected structure. I just got sidetracked with work/life and forgot about it.

**Comment by abonander** [comment]
@seanmonstar what is that body stream filter gonna look like anyway? Are you refactoring filters to allow returning futures or are you making it work like a synchronous API?

**Comment by seanmonstar** [comment]
I've added it to master already. Using `Filter::and_then`, you can return a Future. So it could be done as:

```rust
let filter = warp::body::stream()
    .and_then(process_async);
```

It currently returns a pseudo `impl Stream`, as I expect the type to change slightly to allow adding in decompression filters in the chain as well.

**Comment by abonander** [comment]
@seanmonstar unfortunately I need the stream type to be nameable as the return type of my multipart filter would have to be `impl Filter<Extract = (Multipart<ImplStream>,), Error = ...>`

**Comment by seanmonstar** [comment]
If it's a filter built in to warp, it can both use the concrete type directly, and also not expose a generic.

**Comment by abonander** [comment]
I was hoping to start experimenting in `multipart-async` though. And that kind of hurts composability in general.

**Comment by seanmonstar** [comment]
> I was hoping to start experimenting in multipart-async

Oh OK, as an immediate solution, it should be possible to turn it into a `Box<Stream<Item = Box<Buf>>`:

```rust
warp::body::stream()
    .map(|s| {
        Box::new(s.map(|buf| Box::new(buf) as Box<Buf + Send>))
            as Box<Stream<Item = Box<Buf + Send>, Error = warp::Error> + Send>
    })
    .and_then(|boxed_stream| {

    })
```

>  And `impl Trait` everywhere kind of hurts composability in general.

Yea, in some ways it might, but I've also been wanting to use warp to explore exactly this issue, if we can actually use `impl Trait` a bunch, or if it's only useful in tiny doses. This is relevant since `async` will be making everything use `impl Future`.

**Comment by seanmonstar** [comment]
As part of [v0.1.7](https://github.com/seanmonstar/warp/releases/tag/v0.1.7), the types are now exported as `BodyStream` and `StreamBuf`.

**Comment by abonander** [comment]
@seanmonstar it's been a bit, kinda forgot about net stuff for a while.

Would it be feasible/efficient to implement `split` methods on `StreamBuf` like those on `bytes::Bytes`? Multipart-async is built entirely around those so it would have to perform a lot of copying otherwise.

**Comment by seanmonstar** [comment]
That should be doable.
