### ISSUE TITLE
Documentation: list the re-exported functions and types

### ISSUE THREAD

**Issue by kud1ing** [seanmonstar/warp#404]
Examples often use `warp::path()` but https://docs.rs/warp/0.2.0/warp/ does not lead you where/how that function is defined. The only `path` there is the macro.

You need to know that it is a re-export of https://docs.rs/warp/0.2.0/warp/filters/path/fn.path.html
I think this makes the documentation and examples hard to understand.

**Comment by seanmonstar** [comment]
As mentioned in the source of `lib.rs`, a newcomer landing on the homepage seeing a huge list of functions can be off-putting, so they are hidden, and examples show that they can be used.

**Comment by kud1ing** [comment]
Maybe not every function, but just `warp::path()` which appears in many examples.

**Comment by kud1ing** [comment]
Maybe the glossary of a warp book would be a better place https://github.com/kud1ing/Warp-Book/blob/master/README.md for such explanations.
