### ISSUE TITLE
A TCP session task is not dropped always

### ISSUE THREAD

**Issue by jq-rs** [seanmonstar/warp#405]
I am working on a WebSocket proxy which upgrades WebSocket connection and forwards its messages to a new TCP session and vice versa. Pretty straightforward and works already with tk-http + tokio.

When porting this to 0.1.x Warp, I have encountered an issue that sometimes the new TCP session is not closed properly after `on_upgrade` even though the task is finished and WS connection closed.  Same happens no matter is it spawned as a separate task or combined with select (futures 0.1). Having a threadpool or current thread does not matter either. Sometimes it works. Maybe the TCP session is not dropped properly based on timing?

Anyone seen this kind of behaviour? Any clues what could be going on? It is easy to reproduce but I need to do a minimal setting for reference (I do not yet have it), if this is needed.

**Comment by seanmonstar** [comment]
Which `TcpStream` is not dropped? The one inside `warp::ws::WebSocket`?

**Comment by jq-rs** [comment]
Thanks for the reply! Yes, the one inside WebSocket.

**Comment by seanmonstar** [comment]
Ah OK, thanks for pasting the example, I think I know the issue.

The `mles_rx` keeps the proxies TCP task alive until there are no more messages. It will be notified of no more messages when all the senders have been closed. You have a couple of clones of `mles_tx`, and until all those are dropped, the channel doesn't close. I believe you can remove all the clones of that sender, and just move it into the `ws_reader` for_each.

**Comment by jq-rs** [comment]
Thanks! I dropped the clones (see https://github.com/jq-rs/arki-server/blob/jq-rs/timeout_draft/src/main.rs) and tested. For some reason it does not help, the issue that TCP session is left there sometimes remains even after that.

**Comment by seanmonstar** [comment]
I can't say exactly, [these lines](https://github.com/jq-rs/arki-server/blob/2c9f50131eb374b81a454cdda79abf01d819c5e7/src/main.rs#L111-L117) look suspicious... It seems they are ignoring errors and `NotReady`. What if you wrote:

```rust
let write_wstx = stream.for_each(move |buf| {
    let mut ws_tx_inner = ws_tx.clone();
    // send to websocket
    ws_tx_inner.send(buf)
    // do you need to map the send error?
    // .map_err(|err| ...)
});
```

-----

I don't believe this is a bug in warp, so I'm going to close up here.

**Comment by jq-rs** [comment]
OK, I'll work on a minimized example so it can be easily reproduced and see if I can find more details when (and where) exactly it fails. Maybe it helps me to find out where the problem is.

**Comment by jq-rs** [comment]
I found out the problem, it is indeed not in Warp. Sorry for the trouble.

I was trying to close the connection time by enabling TCP level keepalives on my server and assumed they would work by default. I was wrong, they need to be enabled on socket level. There is no API to do that for WebSocket stream so seems that I would really need the keepalives feature #269. If I can help there, e.g. by testing, I'd be happy to do that.
