### ISSUE TITLE
Streaming large files from a DB connection?

### ISSUE THREAD

**Issue by cheako** [seanmonstar/warp#414]
I make the analogy of a DB connection to simplify things.  However the truth is that this is a tokio TcpStream that has the Body for the next content length.  Afterwards it should be dropped, so it will return to the pool that it comes from(a heavily modified lifeguard).

The files could be GBs in size so I'm concerned about buffering by warp.
https://gitlab.com/cheako/files-rs/blob/a8438e799c85fc1fef407d73727bedf92a4d72d0/src/freenet/download.rs#L86

**Comment by jxs** [comment]
Hi, have you seen hyper's [Body::channel()](https://docs.rs/hyper/0.13.1/hyper/struct.Body.html#method.channel) and [Body::wrap_stream()](https://docs.rs/hyper/0.13.1/hyper/struct.Body.html#method.wrap_stream) ?
in your case it seems you can use `Body::channel()` and send through the channel the bytes read from the socket

**Comment by cheako** [comment]
I think Body::wrap_stream() is what I need, but I don't KNOW.  For example should I use
```impl FromIterator<u8> for Bytes``` or will the first thing that will do is is exhaust the Iterator into a slice?

**Comment by cheako** [comment]
I did this: https://gitlab.com/cheako/files-rs/blob/96145297a4837b00476e216741ba28a3a69f6f96/src/freenet.rs#L53-72   Don't know if it'll work as it should?
