### ISSUE TITLE
Stream is ?Sized.

### ISSUE THREAD

**Issue by cheako** [seanmonstar/warp#419]
https://github.com/seanmonstar/warp/blob/c5f4de891e9b66f9e5a8d115f2b858004d5264ae/src/filters/body.rs#L78
```impl Buf``` instead of ```Bytes``` causes:
```
the size for values of type `(dyn bytes::buf::buf_impl::Buf + 'static)` cannot be known at compilation time

doesn't have a size known at compile-time

help: the trait `std::marker::Sized` is not implemented for `(dyn bytes::buf::buf_impl::Buf + 'static)`
note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
note: required by `std::result::Result`
```

I'm also interested in #323 and in relation too #414

**Comment by seanmonstar** [comment]
I'm sorry, I don't quite understand what you did to trigger that error.

**Comment by cheako** [comment]
There was a situation where I wanted to store the body stream in a struct and I couldn't for whatever reason wrap it in a Box.
