### ISSUE TITLE
Help with shared channel

### ISSUE THREAD

**Issue by drewkett** [seanmonstar/warp#423]
I'm struggling to figure out how to pass around a channel that is effectively a job queue with warp.  The following is the basic idea behind the code. I've tried a bunch of variations of cloning `snd`, using `move` and/or using a reference. When I use `&snd` as a reference I get an error saying that `snd` may outlive the current function which makes sense to me with async as it has no way of knowing when the closure will run. But if I use `move` with the closure it complains that the closure is `FnOnce` instead of `Fn` since its moving `snd`. 

One thing I looked for but didn't see was a filter that took an owned `Clone` object and cloned it for every connection, but I couldn't find it, nor am I positive that would be a solution. 

Any guidance would be appreciated. Thanks

```rust
#[tokio::main]
async fn main() {
    let (snd, mut rcv) = tokio::sync::mpsc::unbounded_channel::<String>();
    tokio::spawn(async move {
        while let Some(request) = rcv.recv().await {
            // Run request
        }
    })
    let hello = warp::path("test").and_then(|_| async {
         snd.send("hi".to_owned()
    });
    warp::serve(hello).run((127.0.0.1].8088)).await;
}
```

**Comment by seanmonstar** [comment]
> One thing I looked for but didn't see was a filter that took an owned Clone object and cloned it for every connection

This is done with `warp::any`:

```rust
let with_sender = warp::any().map(move || snd.clone());
```

And now, you just need to `move` a clone into the `async` (otherwise, the `async` just borrows the sender, which is why you see the lifetime error):

```rust
#[tokio::main]
async fn main() {
    let (snd, mut rcv) = tokio::sync::mpsc::unbounded_channel::<String>();
    tokio::spawn(async move {
        while let Some(request) = rcv.recv().await {
            // Run request
        }
    });

    let with_sender = warp::any().map(move || snd.clone());
    let hello = warp::path("test").and(with_sender).and_then(|snd| async move {
         snd.send("hi".to_owned()).await;
    });
    warp::serve(hello).run((127.0.0.1].8088)).await;
}
```

**Comment by drewkett** [comment]
Awesome, thanks!
