### ISSUE TITLE
`addr::remote` filter doesn't work with `Server::run_incoming`

### ISSUE THREAD

**Issue by tedsta** [seanmonstar/warp#428]
Hi! I have a (perhaps ugly / misguided) use-case where I need to get at the underlying [file descriptor](https://docs.rs/tokio/0.2.11/tokio/net/struct.TcpStream.html#method.as_raw_fd) of each incoming WebSocket so that I can pass it to [libc](https://docs.rs/libc/0.2.66/libc/fn.ioctl.html) to get the [linux-specific `send-q` stat](https://docs.rs/libc/0.2.66/libc/constant.TIOCOUTQ.html) - how much unacknowledged data is in the queue.

A solution to my use-case is to store the file descriptor of each incoming socket in a `HashMap<SocketAddr, RawFd>` using `TryStreamExt::inspect_ok`. This works as long as one can get the `SocketAddr` of the connection from inside the warp filters.

Unfortunately that's not currently possible, because `run_incoming` wraps everything in `LiftIo`, which always returns `None` for `Transport::remote_addr()`.

A solution to this is to expose `Transport` and `run_incoming2` (probably under a new name) so that people can implement Transport for their own types and pass it directly to `run_incoming2`.

**Comment by jxs** [comment]
Hi, have you seen the [filter to service conversion](https://docs.rs/warp/0.2.3/warp/fn.service.html)?
also see https://github.com/seanmonstar/warp/issues/16#issuecomment-573959674,  [`make_service_fn`](https://docs.rs/hyper/0.13.6/hyper/service/fn.make_service_fn.html#example) receives `AddrStream` which implements `Transport`

**Comment by tedsta** [comment]
Oh cool! That almost works for me, but `AddrStream` does not implement `AsRawFd`. The underlying `tokio::net::TcpStream` does, but `AddrStream` doesn't provide any way to get at it with a borrowed `&AddrStream` (and no way to convert a `tokio::net::TcpStream` back into an `AddrStream` even if it were owned). I think that solves my use-case as far as warp is concerned though, I'll have to take the `AsRawFd` issue to hyper. Thanks.

I still feel that it is a bit of a wart that there is no way to make `warp::addr::remote()` work in a situation where it is technically possible.
