### ISSUE TITLE
Handling errors as responses

### ISSUE THREAD

**Issue by Jiroscopes** [seanmonstar/warp#434]
Hello, 

I am new to rust and I am trying to make a simple auth server. I cannot figure out how to handle errors in warp so that I can return errors as responses like 400 or 500 or whatever. 

My Handler
```
pub async fn register(req: RegisterUser, db: PgPool) -> Result<Response<()>> {

    let mut conn = db.begin().await?;

    let insert_user = sqlx::query!(r#"INSERT INTO users VALUES ( $1::text, $2::text, $3::text )"#, req.username, req.email, req.password)
        .execute(&mut conn)
        .await?;

    conn.commit().await?;
    
    let response = Response::builder()
        .status(StatusCode::OK)
        .body(())
        .unwrap();
    Ok(response)
 
}
```

My Filters

```
async fn main() {

    // attempt to create our pool
    let state = match create_pool().await {
        Ok(state) => state,
        Err(_) => panic!("Connection pool creation failed")
    };

    // Clone our state
    let state = warp::any().map(move || state.clone());
    // POST filter
    let register = warp::path("register")
        .and(warp::body::json())
        .and(state.clone())
        .and_then(app::users::register);
    // Make our routes go through the /users/ path
    let routes = warp::path("users").and(register);
    // Serve our routes
    warp::serve(routes).run(([127, 0, 0, 1], 8000)).await;
}
```

I am getting this error
```
the trait bound `sqlx_core::error::Error: warp::reject::sealed::CombineRejection<warp::reject::Rejection>` is not satisfied
```

What is CombineRejection and how can I fix it?

**Comment by jxs** [comment]
Hi, have you seen the [rejections example](https://github.com/seanmonstar/warp/blob/master/examples/rejections.rs)? 
you need to return a type that implements [`Reject`](https://docs.rs/warp/0.2.1/warp/reject/trait.Reject.html) and then threat the rejection type accordingly on the recover handler

**Comment by Jiroscopes** [comment]
I understand I need to return a rejection, but how do I implement `reject` for an error? I tried to use `impl reject for T` and then use `?` to convert the error but it does not seem to work. Any ideas?

**Comment by jxs** [comment]
> I understand I need to return a rejection, but how do I implement reject for an error?

[Reject doesn't have methods ](https://github.com/seanmonstar/warp/blob/master/src/reject.rs#L146) you can impl it with `impl Reject for ErrorType {}`  but your type has to impl `Debug` and be `Send + Sync + 'static`
to use ? in your case you have to wrap Sqlx Error with your Error type and reject it with [`warp::reject::custom`](https://docs.rs/warp/0.2.1/warp/reject/fn.custom.html) eg:
```Rust
#[derive(Debug)]
enum Rejections {
    Sqlx(sqlx::Error)
}
impl warp::reject::Reject for Rejections {}

pub async fn register(req: RegisterUser, db: PgPool) -> Result<impl warp::Reply, warp::reject::Rejection> {

    let mut conn = db.begin().await?;

    let insert_user = sqlx::query!(r#"INSERT INTO users VALUES ( $1::text, $2::text, $3::text )"#, req.username, req.email, req.password)
        .execute(&mut conn)
        .await
        .map_err(|err| warp::reject::custom(Rejections::sqlx(err)))?;

    conn.commit().await?;
    
    let response = Response::builder()
        .status(StatusCode::OK)
        .body(())
        .unwrap();
    Ok(response)
 
}

```

**Comment by Jiroscopes** [comment]
I see. I was close, I was misunderstanding `reject` and `Rejection`. Thank you for the help!
