### ISSUE TITLE
Cross-Origin Request Blocked in browser on 404

### ISSUE THREAD

**Issue by 1init** [seanmonstar/warp#435]
Hi guys i have the following code
async fn main() {
```
  let cors = warp::cors()
    .allow_any_origin();
  if env::var_os("RUST_LOG").is_none() {
    env::set_var("RUST_LOG", "guest_msgs=info");
  }
  pretty_env_logger::init();
  let db = models::blank_db();
  let api = filters::guest_msgs(db);
  let routes = api.with(warp::log("guest_msgs"))
  .with(&cors);
  warp::serve(routes).run(([127, 0, 0, 1], 3030)).await;
}
```
It works with curl and warp test 
how ever when i use a front end framework such as seed it comes up with
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:3030/guest_msgs. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```
i was wondering if any one else come across this. I am currently reading the warp rust doc. I am thinking weather to replace seed fetch with reqwest if possible or somehow use warp to  combine seed into warp 
my seed request looks like this:
```
async fn send_request(make_id: String, make_name: String, make_country: String, make_subject: String, make_message: String) -> Result<Msg, Msg> {
    fetch::Request::new(get_request_url())
        .method(fetch::Method::Post)
        .header("Content-Type", "application/json")
        .send_json(&shared::SendMessageRequestBody { id: make_id, name: make_name, country: make_country, 
            subject: make_subject, message: make_message,  })
        .fetch_json_data(Msg::Fetched)
        .await
}
```

thanks in advance, i am looking for some one to suggest a approach on resolving  this. i think i put the cors in the wrong place as i do not have other routes. other then the path per request

warp
```
  pub fn guest_msgs_create(db: Db,) -> impl Filter<
    Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
      warp::path!("guest_msgs")
        .and(warp::post())
        .and(json_body())
        .and(with_db(db))
        .and_then(handlers::create_guest_msg)
    }
```

**Comment by 1init** [comment]
here is my full code:

> #![deny(warnings)]
> 
> use std::env;
> use warp::{http::Method, Filter};
> 
> #[tokio::main]
> async fn main() {
>   let cors = warp::cors()
>     .allow_any_origin()
>     .allow_methods(&[Method::POST, Method::GET]);
>   if env::var_os("RUST_LOG").is_none() {
>     env::set_var("RUST_LOG", "guest_msgs=info");
>   }
>   pretty_env_logger::init();
>   let db = models::blank_db();
>   let api = filters::guest_msgs(db)
>   .with(cors);
>   let routes = api.with(warp::log("guest_msgs"));
>   warp::serve(routes).run(([127, 0, 0, 1], 3030)).await;
> }
> 
> mod filters {
>   use super::handlers;
>   use super::models::{Db, ListOptions, GuestMsg};
>   use warp::Filter;
> 
>   // 4 guest_msgs filters together
>   pub fn guest_msgs( db: Db, ) -> impl Filter <
>     Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
>       guest_msgs_list(db.clone())
>         .or(guest_msgs_create(db.clone()))
>         .or(guest_msgs_update(db.clone()))
>         .or(guest_msgs_delet(db))
>     }
> 
>     //get /guest_msg?offset=3&limit=5
>     pub fn guest_msgs_list( db: Db,) -> impl Filter<
>       Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
>         warp::path!("guest_msgs")
>           .and(warp::get())
>           .and(warp::query::<ListOptions>())
>           .and(with_db(db))
>           .and_then(handlers::list_guest_msgs)
>       }
> 
>   //post /guest_msg/:hobby with JSON body
>   pub fn guest_msgs_create(db: Db,) -> impl Filter<
>     Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
>       warp::path!("guest_msgs")
>         .and(warp::post())
>         .and(json_body())
>         .and(with_db(db))
>         .and_then(handlers::create_guest_msg)
>     }
> 
>   //put /guest_msgs/:hobby with Json body
>   pub fn guest_msgs_update(db: Db,) -> impl Filter<
>     Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
>       warp::path!("guest_msgs" / String)
>       .and(warp::put())
>       .and(json_body())
>       .and(with_db(db))
>       .and_then(handlers::update_guest_msg)
>     }
> 
>   // DELETE /toods/:hobby
>   pub fn guest_msgs_delet(db : Db,) -> impl Filter<
>     Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
>       let admin_only = warp::header::exact("authorizeMe", "aDm1n5t0r 34j3kbk3b3jk2sd");
>       warp::path!("guest_msgs" / String)
>         .and(admin_only)
>         .and(warp::delete())
>         .and(with_db(db))
>         .and_then(handlers::delete_guest_msg)
>     }
> 
>   fn with_db(db: Db) -> impl Filter<
>     Extract = (Db,), Error = std::convert::Infallible> + Clone {
>       warp::any().map(move || db.clone())
>     }
> 
>     //json body acceptance here
>   fn json_body() -> impl Filter<
>     Extract = (GuestMsg,), Error = warp::Rejection> + Clone {
>       warp::body::content_length_limit(1024 * 16).and(warp::body::json())
>     }
> }
> 
> mod handlers {
>   use super::models::{Db, ListOptions, GuestMsg};
>   use std::convert::Infallible;
>   use warp::http::StatusCode;
> 
>   pub async fn list_guest_msgs(opts: ListOptions, db: Db) -> Result<impl warp::Reply, Infallible> {
>     let guest_msgs = db.lock().await;
>     let guest_msgs: Vec<GuestMsg> = guest_msgs
>     .clone()
>     .into_iter()
>     .skip(opts.offset.unwrap_or(0))
>     .take(opts.limit.unwrap_or(std::usize::MAX))
>     .collect();
>   Ok(warp::reply::json(&guest_msgs))
>   }
> 
>   pub async fn create_guest_msg(create: GuestMsg, db: Db) -> Result<
>   impl warp::Reply, Infallible> {
>     log::debug!("create_guest_msg: {:?}", create);
>     let mut vec = db.lock().await;
> 
>     for guest_msg in vec.iter() {
>       if guest_msg.hobby == guest_msg.hobby {
>       log::debug!("   -> hobby exists: {}", create.hobby);
>       return Ok(StatusCode::BAD_REQUEST);
>       }
>     }
>     vec.push(create);
>     Ok(StatusCode::CREATED)
>   }
> 
>   pub async fn update_guest_msg(
>     hobby: String,
>     update: GuestMsg,
>     db: Db,
>     ) -> Result<impl warp::Reply, Infallible> {
>     log::debug!("update_guest_msg: hobby={} guest_msg={:?}", hobby, update);
>     let mut vec = db.lock().await;
> 
>     for guest_msg in vec.iter_mut() {
>       if guest_msg.hobby == hobby {
>         *guest_msg = update;
>         return Ok(StatusCode::OK);
>       }
>     }
> 
>     log::debug!("   -> guest_msg hobby not found!");
> 
>     Ok(StatusCode::NOT_FOUND)
>   }
> 
>   pub async fn delete_guest_msg(hobby: String, db: Db) -> Result<impl warp::Reply, Infallible> {
>     log::debug!("delete_guest_msg: hobby {}", hobby);
>     let mut vec = db.lock().await;
> 
>     let len = vec.len();
>     vec.retain(|guest_msg| {
>       guest_msg.hobby != hobby
>     });
>     let deleted = vec.len() != len;
> 
>     if deleted {
>       Ok(StatusCode::NO_CONTENT)
>     } else {
>       log::debug!("   -> guest_msg hobby not found!");
>       Ok(StatusCode::NOT_FOUND)
>     }
>   }
> }
> 
> mod models {
>   use serde_derive::{Deserialize, Serialize};
>   use std::sync::Arc;
>   use tokio::sync::Mutex;
> 
> // in memory db
>   pub type Db = Arc<Mutex<Vec<GuestMsg>>>;
> 
>   pub fn blank_db() -> Db {
>     Arc::new(Mutex::new(Vec::new()))
>   }
> 
>   #[derive(Debug, Deserialize, Serialize, Clone)]
>   pub struct GuestMsg {
>       pub hobby: String,
>   }
> 
> //the query parameters for list_guest_msgs.
>   #[derive(Debug, Deserialize)]
>   pub struct ListOptions {
>     pub offset: Option<usize>,
>     pub limit: Option<usize>,
>   }
> }
> 
> #[cfg(test)]
> mod tests {
>     use warp::http::StatusCode;
>     use warp::test::request;
> 
>     use super::{
>         filters,
>         models::{self, GuestMsg},
>     };
> 
>     #[tokio::test]
>     async fn test_post() {
>         let db = models::blank_db();
>         db.lock().await.push(guest_msg1());
>         let api = filters::guest_msgs(db);
> 
>         let resp = request()
>             .method("POST")
>             .path("/guest_msgs")
>             .json(&GuestMsg {
>                 hobby: "1".to_string(),
>             })
>             .reply(&api)
>             .await;
> 
>         assert_eq!(resp.status(), StatusCode::CREATED);
>     }
> 
>     #[tokio::test]
>     async fn test_post_conflict() {
>         let db = models::blank_db();
>         db.lock().await.push(guest_msg1());
>         let api = filters::guest_msgs(db);
> 
>         let resp = request()
>             .method("POST")
>             .path("/guest_msgs")
>             .json(&guest_msg1())
>             .reply(&api)
>             .await;
> 
>         assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
>     }
> 
>     #[tokio::test]
>     async fn test_put_unknown() {
>         let _ = pretty_env_logger::try_init();
>         let db = models::blank_db();
>         let api = filters::guest_msgs(db);
> 
>         let resp = request()
>             .method("PUT")
>             .path("/guest_msgs/1")
>             .header("authorizeMe", "aDm1n5t0r 34j3kbk3b3jk2sd")
>             .json(&guest_msg1())
>             .reply(&api)
>             .await;
> 
>         assert_eq!(resp.status(), StatusCode::NOT_FOUND);
>     }
> 
>     fn guest_msg1() -> GuestMsg {
>         GuestMsg {
>             hobby: 1.to_string(),
>         }
>     }
> }
>

**Comment by 1init** [comment]
![image](https://user-images.githubusercontent.com/43924216/74584595-160b8d80-4fcc-11ea-8f38-73cb7bd34535.png)

**Comment by seanmonstar** [comment]
I believe what's happening is you don't have a filter that handles `/livereload`, and so all the filters wrapped in the `cors` filter just reject as not found. Once warp sees the not found rejection, it just replies with a 404, but at that point, no longer within the `cors` wrapper.

**Comment by 1init** [comment]
this was fixed sorry i did not use "./static"  folder i used "/static" i like warp its really good but i wish i could find away to download the docs .rs on warp as pdf. so i can keep it on my andriod tablet to read.

**Comment by 1init** [comment]
thanks so much for making this awesome web framework
