### ISSUE TITLE
example/tls.rs got an error

### ISSUE THREAD

**Issue by seuai** [seanmonstar/warp#436]
hello, I want to solve error.

Cargo.toml

    [package.metadata.docs.rs]
    features = ["tls"]

    [dependencies]
    tokio = { version = "0.2", features = ["macros"] }
    warp = "0.2"

src/main.rs

    #![deny(warnings)]

    #[cfg(feature = "tls")]
    #[tokio::main]
    async fn main() {
        use warp::Filter;

        // Match any request and return hello world!
        let routes = warp::any().map(|| "Hello, World!");
	
        warp::serve(routes)
	.tls()
        .cert_path("/root/fullchain.pem")
        .key_path("/root/privkey.pem")
        .run(([0, 0, 0, 0], 443))
        .await;
    }

cargo run

error : consider adding a `main` function to `src/main.rs`

**Comment by jxs** [comment]
Hi, you probably don't want to have the `#[cfg(feature = "tls")]` above the `main` function, as it  only exposes it when you run your program with `--features tls` . 
If you want to depend on warp with `tls` feature, that is defined on cargo,  you can check more on cargo dependencies and features [here ](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html)
