### ISSUE TITLE
Expose private fields on standard rejects

### ISSUE THREAD

**Issue by johnchildren** [seanmonstar/warp#440]
When handling rejections in `recover` it would be quite handy to be able to access in internal fields of the standard rejection structs. For example, with a missing header it would be nice to be able to see which header was missing, such as when the "Authorization" header is missing and you would like to provide a "WWW-Authenticate" header in your rejection response.

I suspect there are other use cases as well for doing this when you want to include more information in error messages and it should be a reasonably trivial change.

Am willing to submit a PR if this would be appropriate.

**Comment by jxs** [comment]
Hi, can't you get those fields by downcasting via [`Rejection::find`](https://github.com/seanmonstar/warp/blob/master/examples/rejections.rs#L69) to the `Reject` type? the [example shows how to](https://github.com/seanmonstar/warp/blob/master/examples/rejections.rs#L69)

**Comment by johnchildren** [comment]
> Hi, can't you get those fields by downcasting via [`Rejection::find`](https://github.com/seanmonstar/warp/blob/master/examples/rejections.rs#L69) to the `Reject` type? the [example shows how to](https://github.com/seanmonstar/warp/blob/master/examples/rejections.rs#L69)

Unless I'm missing something that will give you the struct but the fields inside the struct are private, for example:

```rust
    if let Some(err) = rejection.find::<warp::reject::MissingHeader>() {
        let missing_header = err.name; // error[E0616]: field `name` of struct `warp::reject::MissingHeader` is private
    }
```

What I would like to be able to do is get access to the `name` field, sorry if my original explanation was poor.

**Comment by jxs** [comment]
>What I would like to be able to do is get access to the name field, sorry if my original explanation was poor.

ah I see, no worries, I didn't understand that sorry.  Regarding `MissingHeaders`, it implements `Display` which makes it impl `ToString` but it will convert into "Missing request header {:?}" header.name but that is not what you are looking for yeah.

Known Rejections like `MissingHeader`, `InvalidHeader`, `MissingCookie` could offer a `name()` method to access it's inner fields
CC @seanmonstar
