### ISSUE TITLE
PSA: `Filter::Extract` should be a tuple

### ISSUE THREAD

**Issue by mikeyhew** [seanmonstar/warp#441]
I was getting an error that I didn't understand when I extracted part of a filter into a function. The problem was I was using the wrong incantation for the return type of the function. Here is the code that triggered the error:

```rust
use warp::Filter;

fn main_filter() -> impl warp::Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    warp::path("api").and(list_todos())
}

fn list_todos() -> impl warp::Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    warp::get()
        .and(warp::path!("todos"))
        .map(|| warp::reply::json(&Vec::<()>::new()))
}
```

This causes this compiler error:

```
error[E0277]: the trait bound `impl warp::reply::Reply: warp::generic::Tuple` is not satisfied
 --> src/lib.rs:4:23
  |
4 |     warp::path("api").and(list_todos())
  |                       ^^^ the trait `warp::generic::Tuple` is not implemented for `impl warp::reply::Reply`

error[E0277]: the trait bound `impl warp::reply::Reply: warp::generic::Tuple` is not satisfied
 --> src/lib.rs:3:21
  |
3 | fn main_filter() -> impl warp::Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `warp::generic::Tuple` is not implemented for `impl warp::reply::Reply`
4 |     warp::path("api").and(list_todos())
  |     ----------------------------------- this returned value is of type `warp::filter::and::And<warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>, impl std::clone::Clone+warp::filter::Filter>`
  |
  = note: required because of the requirements on the impl of `warp::filter::FilterBase` for `warp::filter::and::And<warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>, impl std::clone::Clone+warp::filter::Filter>`
  = note: the return type of a function must have a statically known size

error: aborting due to 2 previous errors
```

The error goes away if you replace `impl warp::Reply` with `(impl warp::Reply,)`:

```rust
use warp::Filter;

fn main_filter() -> impl warp::Filter<Extract = (impl warp::Reply,), Error = warp::Rejection> + Clone
{
    warp::path("api").and(list_todos())
}

fn list_todos() -> impl warp::Filter<Extract = (impl warp::Reply,), Error = warp::Rejection> + Clone
{
    warp::get()
        .and(warp::path!("todos"))
        .map(|| warp::reply::json(&Vec::<()>::new()))
}

```

**Comment by jxs** [comment]
Hi there, yeah it's [documented](https://docs.rs/warp/0.2.1/warp/trait.Filter.html#extracting-tuples)

**Comment by mikeyhew** [comment]
Ah I see, thanks for the link. Well, I guess at least this issue will help someone like me in the future who doesn't read the docs thoroughly enough.

I got the type `impl warp::Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone` from the todos example. We should probably fix that example to make the `Extract` type a tuple.

I also think the documentation on returning filters from functions could be improved - it would be great to have examples using `impl Filter` and `BoxedFilter` on the `Filter` trait. I can't do that right now, but I'll see if I can open a PR in the next week or so. If someone beats me to it though I won't complain :smile:

**Comment by joeri** [comment]
Small remark: the phrasing "You may notice that several of these filters extract some tuple" to me indicated that it's not necessary for a filter to extract tuples. I had to figure this out the hard way too.

To make matters even more confusing the todos.rs example does compile and run, despite the fact that as far as I can see the trait bound for the Extract type to be a Tuple is actually required through FilterBase, while warp::Reply does not implement that trait bound.

**Comment by joeri** [comment]
Okay, I think I understand it now. There is an implementation of the `Reply` trait for something of the form `(impl Reply,)`, so you can leave out the tuple from your type and just use `impl Reply` as your Extract type, this works because Rust knows locally that it actually is a tuple which fulfills the trait bound on FilterBase::Extract.

However some combinators (such as `and` or `map`) do need to know more about the structure of the Extract type, they will fail when you "summarize" the type too much. The reason the todos example gets away with it is that neither `or` nor `with` rely on such type information.

**Comment by seanmonstar** [comment]
If there's a sentence we could add to the docs, that's fine!
