### ISSUE TITLE
Unexpected retries on panics

### ISSUE THREAD

**Issue by davidcornu** [seanmonstar/warp#442]
With the following code in place

`Cargo.toml`

```toml
[package]
name = "warp-panic"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
```

`src/main.rs`

```rust
use warp::Filter;

#[tokio::main]
async fn main() {
    let handler = warp::path("hi")
        .and(warp::get())
        .and_then(hello_handler);

        warp::serve(handler)
        .run(([127, 0, 0, 1], 3030))
        .await;
}

async fn hello_handler() -> Result<impl warp::Reply, std::convert::Infallible> {
    dbg!("Running handler");
    panic!("PANIC");
    Ok("unreachable")
}
```

running `cargo run` (rust `1.41.0`) and hitting `/hi` results in the following output

```
❯ cargo run
   Compiling warp-panic v0.1.0 (/Users/david/Development/warp-panic)
warning: unreachable expression
  --> src/main.rs:17:5
   |
16 |     panic!("PANIC");
   |     ---------------- any code following this expression is unreachable
17 |     Ok("unreachable")
   |     ^^^^^^^^^^^^^^^^^ unreachable expression
   |
   = note: `#[warn(unreachable_code)]` on by default
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

    Finished dev [unoptimized + debuginfo] target(s) in 1.76s
     Running `target/debug/warp-panic`
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
[src/main.rs:15] "Running handler" = "Running handler"
thread 'main' panicked at 'PANIC', src/main.rs:16:5
```

which shows the handler function being called 10 times.

This can be quite the gotcha as if your handler panics for one reason the first time, it's entirely possible you could hit different errors on subsequent retries which makes things quite hard to debug.

I've been digging around to try and figure out why this is happening but a lot of the futures code is way above my head. Any idea why this is happening and whether it's intended behaviour?

**Comment by jxs** [comment]
Hi, so by hitting what do you mean? I ran your example and if I make a single request to `/hi`  it panics once

**Comment by davidcornu** [comment]
> Hi, so by hitting what do you mean?

Make a request to `/hi`.

> I ran your example and if I make a single request to /hi it panics once

This got me curious. If I run it with `curl` I get the one panic, however if I load `http://localhost:3030/hi` in a browser (I tried Safari, Chrome, and Firefox) I end up with multiple panics despite the developer tools showing only a single request.

Note - this is all on macOS 10.15.3. I haven't had a chance to try this out on Linux.

**Comment by seanmonstar** [comment]
I suspect the browser is retrying the request internally since the connection is ended abruptly. warp does not do anything to retry a panicked filter.

**Comment by davidcornu** [comment]
Will attempt to confirm this and re-open if that isn't the case
