### ISSUE TITLE
Feature Request: Integration with `serde_json`

### ISSUE THREAD

**Issue by Bunogi** [seanmonstar/warp#444]
Having some way of replying to a request with a `serde_json::Value` would be useful. It would allow users to use it's macros to create a JSON value, instead of having to write a new type every time. 

Example: 
```rust
//Current way
fn some_endpoint() -> Result<Json, Infallible> {
  #[derive(serde::Serialize)]
  struct ResponseStruct {
     foo: &'static str
  }
  Ok(warp::reply::json(&ResponseStruct { foo: "some-value" }))
}

//If this were to be implemented:
fn some_endpoint() -> Result<Json, Infallible> {
  //something like this
  Ok(serde_json::json!({ "foo": "some-value" }))
}
```

**Comment by HiruNya** [comment]
You're almost there! You just need to use ``warp::reply::json`` on your newly created JSON Value.
```rust
fn some_endpoint() -> Json {
    warp::reply::json(&serde_json::json!({ "foo": "some-value" }))
}
```

**Comment by Bunogi** [comment]
Thanks for clearing that up, didn't realize `Value` implements `Serialize`. This means that a feature like this is unnecessary. I'll close this now :)
