### ISSUE TITLE
Websocket chat example prone to DOS.

### ISSUE THREAD

**Issue by bohdan77** [seanmonstar/warp#446]
If I use the web socket chat [example](https://github.com/seanmonstar/warp/blob/master/examples/websockets_chat.rs) verbatim. 
and then open a web-socket using curl.
`curl --include      --no-buffer      --header "Connection: Upgrade"      --header "Upgrade: websocket"           --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ=="      --header "Sec-WebSocket-Version: 13"      http://127.0.0.1:3030/chat `
The server becomes completely unresponsive, and the logs spam with 
` DEBUG warp::filters::ws            > websocket poll error: Trying to work with closed connection` 
indefinitely. I'm not exactly sure why this occurs. Something with curl opening and closing the connection too quickly perhaps?

**Comment by asonix** [comment]
@bohdan77 if you solved this issue, could you tell us how?

**Comment by bohdan77** [comment]
@asonix Sorry I didn't think the fix was worth responding.

The [issue](https://github.com/seanmonstar/warp/blob/b79d489cc7e7d2ac017647a8c8e505ac9d65485c/examples/websockets_chat.rs#L84) is here.
If you simply change the `continue` to a `break`, the issue is eliminated.
