### ISSUE TITLE
Interest in body_peek filter ( access to body without consume it )

### ISSUE THREAD

**Issue by AtsukiTak** [seanmonstar/warp#452]
I'm interesting in `body_peek` filter because it will make it easy to implement JSON RPC filters.

### What I'd like to implement

```rust
let add_rpc_filter = json_rpc::method("add")  // matches "add" rpc method
    .and(json_rpc::params::<(u8, u8)>())  // matches rpc parameter
    .and(authenticate())    // some user defined filter
    .and_then(|a, b| future::ok(a + b))
    .and_then(json_rpc::reply());

let another_rpc_filter = ...;

let rpc_filter = filters::path::("rpc")
    .and(add_rpc_filter.or(another_rpc_filter));
```

### The hard part

`json_rpc::method` and `json_rpc::params` filters need to access `Body`. But it will panic when `Body` is accessed more than once.

### Ideas to solve it

1. To access `Body` using `filters::body::body_peek` or `filters::body::json_peek` filter.
Such filter allow us to access `Body` more than once.

2. Add extension to store extracted `Body` data.
Perhaps, this is better than above but I'm not sure how to do it without direct use of `hyper`.
According to #222 , I should use `Service` directory and if my understand is correct, I should provide the mechanism almost same with warp's server module by myself. Is it right?

3. Do you have any ideas?
I probably don't understand warp enough. So if you let me know another idea, I'm very very happy!

Thank you!

**Comment by AtsukiTak** [comment]
I'm working on `warp::ext::with_mut(impl Fn(&mut Extensions))` .
https://github.com/seanmonstar/warp/issues/222#issuecomment-491106090

**Comment by AtsukiTak** [comment]
I have created PR #457 but it might have some issues...
So for now, I personally use custom `Service` which wraps `FilteredService`. It seems to work well :)

**Comment by haarts** [comment]
@AtsukiTak could you give me a nudge in the right direction? Perhaps a code snippet? I'm struggling.

**Comment by AtsukiTak** [comment]
@haarts Hi. I chose solution 2 listed above.

> 2. Add extension to store extracted Body data

To do that, what I did are

1. convert `Filter` into `Service` using `warp::serivce`. 
2. prepare a space for extracted body. [sample code](https://github.com/AtsukiTak/warp-json-rpc/blob/master/src/service.rs#L33-L36)

After that, when I want to touch request body,

1. get from that space if it is filled.
2. extract from request.

[sample code](https://github.com/AtsukiTak/warp-json-rpc/blob/master/src/filters.rs#L27)

I hope this would help you :)
