### ISSUE TITLE
real ip/X-Forwarded-For support for remote_addr

### ISSUE THREAD

**Issue by bbigras** [seanmonstar/warp#454]
Right now I'm using the following for logging. It would be nice if it would handle "real ip" transparently.

```
let log = warp::log::custom(|info| {
        info!(
            "{:?} {} {} {} {:?}",
            info.remote_addr(),
            info.method(),
            info.path(),
            info.status(),
            info.elapsed(),
        );
    });
```

**Comment by jxs** [comment]
see https://github.com/seanmonstar/warp/issues/553#issuecomment-620651864

**Comment by Oliboy50** [comment]
I'd really love to have a `warp::addr::real_ip()` (or `client_ip()`) filter too...

ℹ️ I found this crate: https://crates.io/crates/warp-real-ip

but I didn't want to use it since I don't want to trust too many lib authors
