### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by softshipper** [seanmonstar/warp#455]
Hi all 
I would like to use warp in production and would like to know, if it is production ready? 

Thanks

**Comment by seanmonstar** [comment]
If it works for you, it works ;)

There's plenty of people already using it in production. It's possible there are bugs somewhere, but that's true of any software, and we try to fix them pretty quickly.

**Comment by dvic** [comment]
> I would like to use warp in production and would like to know, if it is production ready?

We've been using it for more than a year in production and we have not seen a single issue with it.
