### ISSUE TITLE
Server on IPv6

### ISSUE THREAD

**Issue by Eragonfr** [seanmonstar/warp#456]
Is warp able to serve content to an IPv6 address ?

**Comment by seanmonstar** [comment]
Yep!

**Comment by Eragonfr** [comment]
How i can use warp with IPv6 ? there are no examples.

**Comment by jxs** [comment]
Hi, you can use it in a similar way as one uses it with an [IPV4 ip ](https://github.com/seanmonstar/warp/blob/master/examples/hello.rs#L9) eg: `warp::run(([0, 0, 0, 0, 0, 0xffff, 0xc00a, 0x2ff], 8080))`.  
[`warp::run()`](https://docs.rs/warp/0.2.1/warp/struct.Server.html#method.run) accepts [`Into<SocketAddr>`](https://doc.rust-lang.org/nightly/std/net/enum.SocketAddr.html) as the server address.

**Comment by Eragonfr** [comment]
And can i specify an hostname like `localhost` or `my-domain.tld` ?

**Comment by seanmonstar** [comment]
It's more complicated to do so (try looking at [here](https://docs.rs/tokio/0.2.11/tokio/net/trait.ToSocketAddrs.html).

As this isn't a bug in warp, I'm going to close.

**Comment by nbari** [comment]
how to listen on both ipv4 and ipv6?
