### ISSUE TITLE
Limit number of tokio threads

### ISSUE THREAD

**Issue by plauche** [seanmonstar/warp#459]
Hi,

I'm looking for a way to limit the number of threads that tokio is allowed to spin up underneath warp/hyper. It appears that this can be done via the `core_threads` (or maybe `blocking_threads`) option when [building a `tokio::runtime`](https://docs.rs/tokio/0.1.22/tokio/runtime/struct.Builder.html#method.core_threads).

What would be the best way to modify this? Is it possible to run an instance of warp in a custom tokio runtime?

**Comment by jxs** [comment]
Hi, yeah, but you can define that on the [`tokio::main`](https://docs.rs/tokio/0.2.11/tokio/attr.main.html#set-number-of-core-threads) macro, eg:
```Rust
#[tokio::main(core_threads = 1)]
async fn main() {
    let routes = warp::any().map(|| "Hello, World!");

    warp::serve(routes).run(([127, 0, 0, 1], 3030)).await;
}
```

**Comment by plauche** [comment]
@jxs that looks awesome! However I probably should have mentioned that I'm currently using warp 0.1 and tokio 0.1 due to other dependencies. It looks like that `tokio::main` macro was introduced with tokio 0.2?

**Comment by seanmonstar** [comment]
With 0.1, you can build a Tokio runtime yourself and use `warp::Server::bind` instead of `run`.

**Comment by plauche** [comment]
Thanks @seanmonstar that did the trick!
