### ISSUE TITLE
Add compression Filters

### ISSUE THREAD

**Issue by seanmonstar** [seanmonstar/warp#46]
These would likely need to be `with` filters.

Some hypothetical example:

```rust
let route = warp::fs::dir("static")
    .with(warp::compress::gzip());
```

**Comment by seanmonstar** [comment]
As an update, quoting from #103:

> I'm hopeful with the changes to support tower (#58), we can just make use of the existing [deflate middleware](https://github.com/carllerche/tower-web/tree/master/src/middleware/deflate).

**Comment by jxs** [comment]
related to #58 
cc @luciofranco

**Comment by ParkMyCar** [comment]
If we can't integrate with tower's deflate middleware right now, I'd take a stab at implementing this, seems pretty interesting to me!

**Comment by asonix** [comment]
@ParkMyCar if you're going to look into this, here's a PR that may be of interest to you: https://github.com/seanmonstar/warp/pull/397

I've been thinking about @seanmonstar 's comments on there and tbh I'm not sure a whole lot can be done re: the second point, but I feel the first point is easily solved

**Comment by jxs** [comment]
@ParkMyCar if you are looking for a deflate crate with AsyncRead/Async Write there's https://docs.rs/async-compression/0.2.0/async_compression/
