### ISSUE TITLE
Tail() call crashes to expect

### ISSUE THREAD

**Issue by jq-rs** [seanmonstar/warp#460]
When configuring redirect with `tail()`, it crashes from time to time to `.expect("server URIs should always have path_and_query")` with Warp 0.1.x. It could be because someone accesses it with `CONNECT foo.bar`. See #429 for discussion.

**Comment by jq-rs** [comment]
This can be worked around by not using tail() when doing redirect.

**Comment by seanmonstar** [comment]
It looks like this occurs in 0.2.x as well.

Simple test case:

```rust
let filter = warp::path::tail();

let _tail = warp::test::request()
    .path("localhost")
    .filter(&filter)
    .await
    .unwrap();
```
