### ISSUE TITLE
Add a filter for multipart/mixed

### ISSUE THREAD

**Issue by pdolezal** [seanmonstar/warp#466]
It would be nice to have `multipart/mixed` supported.

Perhaps it could be possible to support multiple `multipart` subtypes at once while leveraging their common roots for the implementation and providing a unified API (I see here a relationship to #323). Moreover `multipart/mixed` parser could be used as the default parser for any yet unsupported or unknown `multipart` types, as the RFC suggests.

The use cases for `multipart/mixed` content type, that I'm concerned with, are related to various RESTful services that handle composite requests from non-browser clients or perform some bulk processing where the response may consist of multiple parts, possibly with different content types. Interoperability with such services is yet another concern.

**Comment by jxs** [comment]
Hi, can you comment that on #323? so that it's all in the same issue and topic?
thanks!
