### ISSUE TITLE
Registering Template Directory

### ISSUE THREAD

**Issue by ChristophHess** [seanmonstar/warp#469]
I hope this is not just a result of my stupidity.
I tried registering a template dir via the *register_template_files* function.

`static TEMPLATE_EXT: &str = "html";
hb = register_template_files(hb);
hb.register_templates_directory(TEMPLATE_EXT, Path::new("templates/")).expect("Template dir not found");`

This however result in the error
`error[E0599]: no method named 'register_templates_directory' found for type 'handlebars::registry::Registry<'_>' in the current scope`

**Comment by jxs** [comment]
Hi, it seems [register_templates_directory](https://docs.rs/handlebars/3.0.1/handlebars/struct.Handlebars.html#method.register_templates_directory) is a method of [HandleBars](https://docs.rs/handlebars/3.0.1/handlebars/struct.Handlebars.html) and you are calling it on `'handlebars::registry::Registry`. 
But that is related to the [`handlebars`](https://crates.io/crates/handlebars) crate, not `warp`

**Comment by ChristophHess** [comment]
Hi Jxs, thanks for the feedback. You're totally right. Wrong repository.
