### ISSUE TITLE
Problems mouting multiple endpoints under common path with shared filters

### ISSUE THREAD

**Issue by mdirkse** [seanmonstar/warp#470]
I'm following the examples and trying to create my API but I've hit a snag. I want to have two endpoints, `/v1/hello/{param}` and `/v1/profile`. I also want to protect these with a CORS filter and another filter that validates a bearer token and extracts a subject from it. I've currently got the following:

```rust
#[tokio::main]
async fn main() {
   ...
   let cors = warp::cors()
        .allow_origin(config.fields.http_origin.string_value.as_str())
        .allow_header("Authorization")
        .allow_methods(vec!["GET", "OPTIONS", "POST"]);

    let hello = warp::path!("v1" / "hello" / String)
        .and(warp::get())
        .and(auth())
        .map(|name, user| format!("Hello, {}! (req from {})", name, user));

    let get_profile = warp::path!("v1" / "profile")
        .and(warp::get())
        .and(auth())
        .map(|user| format!("Profile for {}.", user));

    let routes = hello.or(get_profile).with(cors).recover(handle_rejection);

    warp::serve(routes).run(([0, 0, 0, 0], 8080)).await;
}

fn auth() -> impl Filter<Extract = (String,), Error = Rejection> + Copy {
    warp::header::<String>("Authorization").and_then(|token: String| async move {
        match verify_jwt(token.replace("Bearer ", "").as_str()) {
            Ok(t) => Ok(t),
            Err(_) => return Err(warp::reject::custom(Unauthorized)),
        }
    })
}
```
This works, but as you can see there's a lot of repetition in the hello and get_profile routes. So I tried to simplify it to this:
```rust
#[tokio::main]
async fn main() {
   ...
    let cors = warp::cors()
        .allow_origin(config.fields.http_origin.string_value.as_str())
        .allow_header("Authorization")
        .allow_methods(vec!["GET", "OPTIONS", "POST"]);

    let hello = warp::path!("hello" / String)
        .and(warp::get())
        .map(|name, user| format!("Hello, {}! (req from {})", name, user));

    let get_profile = warp::path!("profile")
        .and(warp::get())
        .map(|user| format!("Profile for {}.", user));

    let routes = warp::path!("v1")
        .and(auth())
        .and(hello.or(get_profile))
        .with(cors)
        .recover(handle_rejection);

    warp::serve(routes).run(([0, 0, 0, 0], 8080)).await;
}
```

This doesn't compile:

```
error[E0593]: closure is expected to take 1 argument, but it takes 2 arguments
   --> src/main.rs:104:10
    |
104 |         .map(|name, user| format!("Hello, {}! (req from {})", name, user));
    |          ^^^ ------------ takes 2 arguments
    |          |
    |          expected closure that takes 1 argument
    |
    = note: required because of the requirements on the impl of `warp::generic::Func<(std::string::String,)>` for `[closure@src/main.rs:104:14: 104:74]`
```
Which makes sense, I guess, because the `auth` filter is no longer in the chain for `hello` or `get_profile` so it doesn't know that a `user` variable is forthcoming. So __my first question__ is, how do I abstract `auth` out into a common path prefix filter (`v1` in my case) while still being able to use the value it produces in other paths that I mount under that common filter?

I can work around the problem by including the `auth` filter in each endpoint:
```rust
    let hello = warp::path!("hello" / String)
        .and(warp::get())
        .and(auth())
        .map(|name, user| format!("Hello, {}! (req from {})", name, user));

    let get_profile = warp::path!("profile")
        .and(warp::get())
        .and(auth())
        .map(|user| format!("Profile for {}.", user));
```

Now it compiles but when I try to `GET /v1/profile` I get an error. I've turned the log up to `TRACE` and all I get is:
```
 TRACE warp::filters::path > "v1"?: "v1"
 ERROR turbotrader         > unhandled rejection: Rejection(NotFound)
```
That second line is from my own code which simply prints the rejection type.

So __my second question__ is: what am I doing wrong in composing the paths like this? There's an example which [seems to do exactly this](https://github.com/seanmonstar/warp/blob/master/examples/routing.rs#L31) and yet I can't get it to work.

**Comment by seanmonstar** [comment]
The difference between what you're trying to do and what the example does is: your closure wants a second parameter, and the example is *only* add a 0-extracting filter (a path prefix).

```rust
let hello = warp::path!("hello" / String)
        .and(warp::get())
        .map(|name, user| format!("Hello, {}! (req from {})", name, user));
```

At the call to `map`, the compiler expects `warp::path!(..).and(warp::get())` to extract `(name, user)`, but it doesn't (only `name`).

----

It's been asked several times for the ability to add filters as prefixes that include new arguments, but I don't see how to get the type system to let us do that...

**Comment by mdirkse** [comment]
Me neither :)

I don't mind a little repetition, but even when I try to prefix with something that doesn't include new arguments it doesn't work:

```rust
    let hello = warp::path!("hello" / String)
        .and(warp::get())
        .and(auth())
        .map(|name, user| format!("Hello, {}! (req from {})", name, user));

    let get_profile = warp::path!("profile")
        .and(warp::get())
        .and(auth())
        .map(|user| format!("Profile for {}.", user));

     let routes = warp::path!("v1").and(hello.or(get_profile)).with(cors).recover(handle_rejection);
```
When I try to `GET /v1/profile` with this config I get:
```
TRACE warp::filters::path > "v1"?: "v1"
ERROR turbotrader         > unhandled rejection: Rejection(NotFound)
```
`warp::path!("v1")` doesn't add any arguments (and the whole thing compiles), so what am I doing wrong?

**Comment by seanmonstar** [comment]
`path!("v1")` assumes that's the full path. To declare a prefix, use `path!("v1" / ..)`.

**Comment by mdirkse** [comment]
Works! Thanks.

**Comment by dpc** [comment]
I'm not sure if this is the same problem, but I'm trying to make two route handlers, sharing all the arguments extracted with `.and(...).and(...).and(...)`, but with a different method (post vs get) somehow share that invocation.

As per type-system - couldn't these filter just carry the type of "previous common arguments" as a type? They would start with `()`, but if chained from already extracted values, they would have them somewhere?
