### ISSUE TITLE
Usage issue with Multipart Part stream going from Bytes to Buf 

### ISSUE THREAD

**Issue by xd009642** [seanmonstar/warp#474]
So I'm working with https://docs.rs/warp/0.2.2/warp/filters/multipart/struct.Part.html#method.stream which internally is a `Bytes` type and in a previous release the `Bytes` type was exposed. 

I was going to clone the bytes type to send the data into two functions which each take a `Stream` but I can't clone `Buf`, so if there's another way to do achieve what I'm looking to do it would be helpful. 

I'd also rather not have to copy the data as there are some large files coming and from benchmarking a gRPC server I wrote with tonic doing a similar thing I found copying the data added an unacceptable slow down.

**Comment by seanmonstar** [comment]
You could call `Buf::to_bytes()`. If the type is `Bytes`, it will be free.

**Comment by xd009642** [comment]
Ah I'm clearly blind :sweat_smile: thanks
