### ISSUE TITLE
warp::ws::Ws.on_upgrade 'static lifetime too limiting?

### ISSUE THREAD

**Issue by ecton** [seanmonstar/warp#477]
I'm running into an issue while trying to access the SocketAddr while inside of an on_upgrade scenario:

```
warp::addr::remote()
            .and(warp::ws())
            .map(|addr: Option<SocketAddr>, ws: warp::ws::Ws| {
                ws.on_upgrade(|websocket| async {
                    // How can I use addr here?
                })
            });
```

Any reference to `addr` inside of that closure breaks the 'static lifetime requirement of the function passed into on_upgrade. I'm fairly new to rust, but my current understanding of rust makes me think that the lifetime of on_upgrade should be restricted to the lifetime of ws, not to a 'static lifetime. By restricting it to static, doesn't that mean that I can't access any state-ful information about the current connection including the filters leading up to the upgrade?

I have tried `async move`, but that doesn't help, still complaining about borrowing the value (even though I really want to copy it!).

Thanks for any assistance. I'm hoping this is just something I don't understand yet about how to pass things across the closure lifetime boundaries. Apologies if this was answered in a previous issue, I tried but nothing seemed the same as this issue.

**Comment by seanmonstar** [comment]
You need to move the value into the closure passed to `on_upgrade` as well.

`ws.on_upgrade(move |websocket| async move {`.

**Comment by ecton** [comment]
That does it. Thank you @seanmonstar, I tried so many things but never guessed that. I need to dig in and understand the closure syntax more!
