### ISSUE TITLE
closure is `FnOnce` because it moves the variable `voyager_html` out of its environment

### ISSUE THREAD

**Issue by DrYSG** [seanmonstar/warp#480]
I did not find too much about this error when googling. Except here and with hyper. Is there something specific that I am doing wrong:

```
error[E0525]: expected a closure that implements the `Fn` trait, but this closure only implements `FnOnce`
   --> examples\warp_subscriptions\src\main.rs:189:14
    |
189 |         .map(move || voyager_html))
    |              ^^^^^^^^------------
    |              |       |
    |              |       closure is `FnOnce` because it moves the variable `voyager_html` out of its environment
    |              this closure implements `FnOnce`, not `Fn`
...
194 |     warp::serve(routes).run(([127, 0, 0, 1], 8080)).await;
    |     ----------- the requirement to implement `Fn` derives from here
```

The voyager_html is a ```Reply``` that is defined above the route definition:

```
    let voyager_html = warp::reply::html(voyager::voyager_source());
```

and the invokation is:

```
    .or(warp::get()
        .and(warp::path("voyager"))
        .map(move || voyager_html))
    .or(homepage)
    .with(log)
    .with(cors);
```

Most likely this is my very newbie knowledge of what WARP does.

**Comment by AtsukiTak** [comment]
Hi. I'm not 100% sure but probably I can help you :)

As compiler says, the problem is that your closure returns `voyager_html` which is captured outside of your closure and does not implement `Copy`.

To fix the error, you should pass `warp::reply::html(voyager::voyager_source())` into `map` function.

```
.or(warp::get()
        .and(warp::path("voyager"))
        .map(|| warp::reply::html(voyager::voyager_source())
    .or(homepage)
    .with(log)
    .with(cors);
```

I hope this helps you. And if this explanation is not enough, please feel free to tell me.

Thanks.

**Comment by DrYSG** [comment]
That was not the solution. I tried that first, but voyager_source() was a async method. So that was failing. My real solution was to use static pages:
```
    .or(warp::path("static")
        .and(warp::fs::dir("static")))
```

**Comment by AtsukiTak** [comment]
Happy to hear that!
BTW, if it’s an aync method, have you tried `and_then` instead of `map`? If you already have tried, judt ignoreme. Thanks. 😁
