### ISSUE TITLE
next('route') like expressjs ?

### ISSUE THREAD

**Issue by all789-pixel** [seanmonstar/warp#481]
Hello

Expressjs provide multiple callback functions that behave just like middleware, except that these callbacks can invoke ``next('route')`` to bypass the remaining route callback(s). You can use this mechanism to impose pre-conditions on a route, then pass control to subsequent routes if there is no reason to proceed with the current route. 

Example

```js
app.get('/user/:id', function (req, res, next) {
  // if the user ID is 0, skip to the next route
  if (req.params.id === '0') next('route')
  // otherwise pass the control to the next middleware function in this stack
  else next()
}, function (req, res, next) {
  // render a regular page
  res.render('regular')
})

// handler for the /user/:id path, which renders a special page
app.get('/user/:id', function (req, res, next) {
  res.render('special')
})
```

Warp can allow ``next('route')`` ?
Thank

**Comment by seanmonstar** [comment]
If I'm understanding correctly, a similar mechanism in warp is the `Rejection`. Any filter can "reject" a request, signalling that some precondition is not fulfilled, and it should try any other filters that are joined via `or`.

So, translating your example:

```rust
let normal = warp::path!("user" / u32).and_then(|id| async {
    if id == 0 {
        // reject as not-found
        // could also use warp::reject::custom(IdIsZero) or something
        return Err(warp::reject());
    } else {
        // normal stuff
});

let special = warp::path!("user" / u32).and_then(|id| async {
    // id should always be 0
});

let routes = normal.or(special);
```

**Comment by AlbanMinassian** [comment]
Thank you very much!
