### ISSUE TITLE
Serve files from embedded resources (rust-embed)

### ISSUE THREAD

**Issue by clintnetwork** [seanmonstar/warp#486]
Hi,

I'm looking for serve files that are store as embedded resources, the goal is to have a small WebUI compiled into the binary and serve it easily!

Do you have a good way to do that with warp? maybe you could propose this kind of feature.

Kind regards

**Comment by nytopop** [comment]
I was looking for something similar and couldn't find anything, so I made [static_dir](https://docs.rs/static_dir/latest/static_dir/macro.static_dir.html).

**Comment by seanmonstar** [comment]
Could you clarify what you mean by embedded resources? Do you mean like things compiled in, like using `include_str!` or similar?

**Comment by clintnetwork** [comment]
yeah exactly!

You know in C++ you can add files with `resources.h` i speak about the same things.

**Comment by seanmonstar** [comment]
If you have the resource available as a `&'static str` or `&'static [u8]`, you can just use that in a reply, like this example: https://github.com/seanmonstar/warp/blob/2587c5939a8775044edc41ad5997aac82ecf59ea/examples/websockets_chat.rs#L43

**Comment by clintnetwork** [comment]
Oh it's a good idea
