### ISSUE TITLE
Performance implication of filter order

### ISSUE THREAD

**Issue by kellytk** [seanmonstar/warp#490]
Is route matching time constant or should hot routes be ordered first as shown below?

```
let routes = routes::hot_route()
    .or(routes::warm_route())
    .or(routes::cold_route());

warp::serve(routes).run(([127, 0, 0, 1], 1234)).await;
```

**Comment by seanmonstar** [comment]
Filters are tried in order of "ors".

**Comment by kellytk** [comment]
@seanmonstar Meaning that in my example `hot_route()` would match in less time than `cold_route()` would, correct?

**Comment by seanmonstar** [comment]
I don't know about in less time. But it will first check `hot`, and if that rejects, then check `warm`, and so forth.
