### ISSUE TITLE
WebSocket session termination

### ISSUE THREAD

**Issue by kellytk** [seanmonstar/warp#491]
Within a WebSocket filter, what API is available to terminate the client connection?

```
.map(|ws: warp::ws::Ws| {
            ws.on_upgrade(|websocket| async {
    // ?
}
```

**Comment by jxs** [comment]
Hi, you can gracefully close the websocket connection with [close](https://docs.rs/warp/0.2.1/warp/filters/ws/struct.WebSocket.html#method.close)

**Comment by kellytk** [comment]
@jxs 

Please how should the following error be resolved:

```
pub fn websocket_route() -> BoxedFilter<(impl Reply,)> {
    warp::path("ws")
        .and(warp::path::end())
        .and(warp::ws())
        .map(|ws: warp::ws::Ws| {
            ws.on_upgrade(|websocket| async {
                let (mut tx, mut rx) = websocket.split();
//                                     --------- value moved here
                websocket.close();
//              ^^^^^^^^^ value used here after move
// note: move occurs because `websocket` has type `warp::filters::ws::WebSocket`, which does not implement the `Copy` trait
            })
        })
        .boxed()
}
```

**Comment by jxs** [comment]
[split](https://docs.rs/futures-util/0.3.0/futures_util/stream/trait.StreamExt.html#method.split) uses self, so that's why it's moved, you have to call [reunite ](https://docs.rs/futures-util/0.3.0/futures_util/stream/struct.SplitSink.html#method.reunite) to get the websocket again

**Comment by kellytk** [comment]
@jxs I'd be using it within a loop handling each received message and in so doing I'm encountering two errors:

```
pub fn websocket_route() -> BoxedFilter<(impl Reply,)> {
    warp::path("ws")
        .and(warp::path::end())
        .and(warp::ws())
        .map(|ws: warp::ws::Ws| {
            ws.on_upgrade(|websocket| async {
                let (mut tx, mut rx) = websocket.split();

                while let Some(received) = rx.next().await {
//                                         ^^ value borrowed here after move
                    rx.reunite(tx).unwrap().close().await.unwrap();
//                             ^^ value moved here, in previous iteration of loop
                }
            })
        })
        .boxed()
}
```

**Comment by seanmonstar** [comment]
If you're splitting the socket in a sink and stream, you can make use of [`SinkExt::close`](https://docs.rs/futures/0.3.*/futures/sink/trait.SinkExt.html#method.close).

```rust
use futures::sink::SinkExt;

let (mut tx, mut rx) = websocket.split();

// whatever you're doing with tx or rx
// ...

// and then closing
tx.close().await
```

You can also send custom websocket close messages with options on [`warp::ws::Message`](https://docs.rs/warp/0.2.*/warp/filters/ws/struct.Message.html)

**Comment by kellytk** [comment]
@seanmonstar Re: custom close messages, is the idea that a Close message is sent in place of calling `close()` or in addition to it?  May I ask what an example would look like?  The WebSocket examples don't demonstrate server-initiated connection closing.

**Comment by kellytk** [comment]
Testing with `tx.send(warp::ws::Message::close_with(StatusCode::BAD_REQUEST, "Invalid Request")).await.unwrap();` I observe the connection close and `tx.close().await` appears to be unnecessary.  Where can I find the definition of `send()`?  I'd like to read the code handling the sending of Close messages.

**Comment by seanmonstar** [comment]
Note that the code passed for websockets is not the same as `http::StatusCode`. See https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent#Status_codes.

**Comment by kellytk** [comment]
@seanmonstar Thank you.  What's the most straightforward way to use `CloseCode` as is done at https://github.com/seanmonstar/warp/blob/fbbbc5b8377914463e4411ef6fc48bfd97d15a6d/src/filters/ws.rs#L294?  Does Warp reexport it?

**Comment by TimvanScherpenzeel** [comment]
> If you're splitting the socket in a sink and stream, you can make use of [`SinkExt::close`](https://docs.rs/futures/0.3.*/futures/sink/trait.SinkExt.html#method.close).
> 
> ```rust
> use futures::sink::SinkExt;
> 
> let (mut tx, mut rx) = websocket.split();
> 
> // whatever you're doing with tx or rx
> // ...
> 
> // and then closing
> tx.close().await
> ```
> 
> You can also send custom websocket close messages with options on [`warp::ws::Message`](https://docs.rs/warp/0.2.*/warp/filters/ws/struct.Message.html)

Hi Sean,

I'm facing a similar issue where `ws_sink` is moved to the tokio task meaning I don't have access to it anymore after the task spawn. Would you have an idea how I could solve this? My goal is to be able to terminate the websocket session from the server at a later point in the code.

```
    let (ws_sink, mut ws_stream) = ws.split();
    let (tx, rx) = mpsc::unbounded_channel();

    tokio::task::spawn(rx.forward(ws_sink).map(|result| {
        if let Err(err) = result {
            error!("Websocket failed to send: {}", err);
        }
    }));
```

**Comment by Simhyeon** [comment]
@TimvanScherpenzeel I know this is old but I was also wondering how to close the channel while following websocket example. 

Looks like there is no chance for simple method solution but drop the whole stream object. 

I just reused disconnected code.

```rust
users.write().await.remove(&my_id);
```
