### ISSUE TITLE
Expose FilteredService::call_with_addr or similar

### ISSUE THREAD

**Issue by bharrisau** [seanmonstar/warp#494]
I'm enjoying using warp, but looking to go a little bit further in my project I saw the option to use `warp::service` to change from a `Filter` into a `hyper::Service`. The current implementation is a little bit awkward because `call` takes a `mut self` and the remote address isn't able to be passed through. The `mut self` then adds an unnecessary clone when using the API.

e.g. internally Warp does the equivalent of this
```
let inner = warp::service(filter);
hyper::service::make_service_fn(move |transport: &AddrStream| {
    let inner = inner.clone();
    let remote_addr = Some(transport.remote_addr());
    async move {
        let svc = hyper::service::service_fn(move |req: Request<Body>| {
            async move {
                inner.call_with_addr(req, remote_addr).await
            }
        });
        Ok::<_, Infallible>(svc)
    }
});
```

External users need to add in an extra clone and can't pass the remote_addr.
```
let inner = warp::service(filter);
hyper::service::make_service_fn(move |_: &AddrStream| {
    let inner = inner.clone();
    async move {
        let svc = hyper::service::service_fn(move |req: Request<Body>| {
            let mut inner = inner.clone();
            async move {
                inner.call(req).await
            }
        });
        Ok::<_, Infallible>(svc)
    }
});
```

Is there room to add a method to convert a `Filter` into a `Fn(Request, Option<SocketAddr>) -> Future<Output = Result<Response<Body>, Infallible>>`, or otherwise expose `FilteredService::call_with_addr`?

**Comment by wngr** [comment]
You should be able to do the following and get around said `clone`:
```rust
let inner = warp::service(filter);
hyper::service::make_service_fn(move |_| {
    let inner = inner.clone();
    async move { Ok::<_, Infallible>(inner) }
});
```

**Comment by bharrisau** [comment]
That option doesn't expose the `inner.call(req)`. Which I think I was
wanting to be able to add timing/tracing code just before and after the
call.

It's been a few months now, so the project may have changed so much to make
the issue stale and can be closed.
