### ISSUE TITLE
WebSocket close code recommendation

### ISSUE THREAD

**Issue by kellytk** [seanmonstar/warp#498]
How should the [close code](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent#Status_codes) be provided to `warp::ws::Message::close_with()`?  `CloseCode` is used at https://github.com/seanmonstar/warp/blob/fbbbc5b8377914463e4411ef6fc48bfd97d15a6d/src/filters/ws.rs#L294 however I don't know that that's also intended for users of Warp.

**Comment by NickeZ** [comment]
If you close with a code of 4000-4999 you will be able to recover the code in the client. That way you can have application specific reasons for rejecting/closing the socket.

* https://tools.ietf.org/html/rfc6455#section-7.4.2
* https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

**Comment by NickeZ** [comment]
Or maybe you meant how to send it? just created it with the function you found and then send it to the sink.

**Comment by kellytk** [comment]
I would prefer to provide an enum such as CloseCode::Normal, however that doesn't appear to be an option.  Also, providing the numeric close code fails:

```
tx.send(warp::ws::Message::close_with(1000, "reason")).await
//      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<i32>` is not implemented for `u16`
// error[E0277]: the trait bound `u16: std::convert::From<i32>` is not satisfied
// pub fn close_with(code: impl Into<u16>, reason: impl Into<Cow<'static, str>>) -> Message {
//                              --------- required by this bound in `warp::filters::ws::Message::close_with`
```

**Comment by NickeZ** [comment]
You can use `Message::close()` to construct a message with the default "successful" close.

Can you try `1000u16` as the number instead? But again, if you want to construct it with `1000` you should use the default constructor I mentioned above.

**Comment by NickeZ** [comment]
Even simpler is to call `close().await` on the sending sink.

**Comment by kellytk** [comment]
> Can you try `1000u16` as the number instead?

That was successful, thank you.  Do you think Warp should reexport `tungstenite`'s `CloseCode` enum?  IMHO the use of an overloaded primitive data type is error-prone.

**Comment by NickeZ** [comment]
warp cannot expose any types from the tungstenite crate. I think the solution provided is good enough. If you want to close with the "normal" code, you should just close the sink. Why are you manually sending the close message?

**Comment by seanmonstar** [comment]
Warp doesn't expose tungstenite as a public dependency, so we can upgrade versions internally without a breaking change.

**Comment by kellytk** [comment]
@NickeZ 
> Why are you manually sending the close message?

It's only an example and I will be using other close codes such as 1002.

@seanmonstar Makes sense, thanks.  Would you be opposed to duplicating the `CloseCode` enum for Warp users?

**Comment by NickeZ** [comment]
Are you aware that browsers don't accept any other codes than 1000, 3000-4999? A browser will not allow you to distinguish 1002 from 1000.
