### ISSUE TITLE
Location of WebSocket `send()` code

### ISSUE THREAD

**Issue by kellytk** [seanmonstar/warp#499]
Where is the definition of the `send()` used at https://github.com/seanmonstar/warp/blob/master/examples/websockets_chat.rs#L111?  For some reason my IDE isn't providing any information for it.

**Comment by ggerico** [comment]
`send()` is called [from the tokio sync module](https://docs.rs/tokio/0.2.13/tokio/sync/mpsc/struct.UnboundedSender.html#method.send).

```rust
use tokio::sync::{mpsc, Mutex};
// ...
let (tx, rx) = mpsc::unbounded_channel();
// ...
users.lock().await.insert(my_id, tx);
// ...
for (&uid, tx) in users.lock().await.iter_mut() {
        if my_id != uid {
            if let Err(_disconnected) = tx.send(Ok(Message::text(new_msg.clone()))) {
                // The tx is disconnected, our `user_disconnected` code
                // should be happening in another task, nothing more to
                // do here.
            }
        }
    }
}

**Comment by kellytk** [comment]
I'd like to read the code handling the sending of Close messages.  Where can that be found?

**Comment by NickeZ** [comment]
You are responsible for the code that sends the close message. Here you have a short snippet:

```rust
let (mut ws_tx, mut ws_rx) = websocket.split();
ws_tx.send(warp::ws::Message::close_with(4000)).await;
```

**Comment by NickeZ** [comment]
You might be interested in the `close()` function as it is implemented by `tokio-tungstenite`: https://github.com/snapview/tokio-tungstenite/blob/1a2a99a7a3297742238772ef6ffd7a957bcfb98f/src/lib.rs#L245

**Comment by kellytk** [comment]
@NickeZ Where is the code in `send()` that identifies the provided message as a Close and calls tokio-tungstenite's `close()`?

**Comment by NickeZ** [comment]
It's the other way around. The tungstenite `close()` method will send a `Close` message. If you send a `Close` message either with or without `code` you have closed your end of the websocket. Then you must wait for the other end to send their `Close` message.

**Comment by kellytk** [comment]
> Then you must wait for the other end to send their `Close` message.

Could a maliciously developed client ignore the Close message and continue using the WebSocket to send the server messages?  Where is the ability to terminate the connection without relying on the client conforming to the protocol?

**Comment by NickeZ** [comment]
I'm not an expert in websocket, please look at the RFC. But AFAIU you can only close your "outgoing" direction. So a malicious client code absolutely continue to listen for more messages after the close message.

The server sending a close message does not mean that the client has closed its outgoing connection.
