### ISSUE TITLE
Optional raw query filter

### ISSUE THREAD

**Issue by pnehrer** [seanmonstar/warp#506]
Is there a way to capture a raw query string if one was supplied in the request?

E.g., `/path?foo=bar` would return `Some("foo=bar")` while `/path` would return `None`.

Happy to try a PR if interested. Thanks!

**Comment by seanmonstar** [comment]
You can use `warp::query::raw()` and make it into an option:

```rust
warp::query::raw()
    .map(|q: String| Some(q))
    .or_else(|_| None)
    .unify()
```

**Comment by pnehrer** [comment]
Thank you for the quick reply! Problem is, this will only match a request that has a query string. With no query string it fails with `Invalid query string`: https://github.com/seanmonstar/warp/blob/master/src/filters/query.rs#L36

I would like to be able to match requests with and without a query string and extract Some(_) or None, respectively.

**Comment by seanmonstar** [comment]
The `map` and `or_else` combinators I showed in the example should do that for you.

**Comment by pnehrer** [comment]
Ah! Mind blown -- thank you!

**Comment by pnehrer** [comment]
FWIW, this worked:

```
warp::query::raw()
                .map(Some)
                .or(warp::any().map(|| None))
                .unify()
```
