### ISSUE TITLE
Example in documentation is "wrong"

### ISSUE THREAD

**Issue by mneumann** [seanmonstar/warp#508]
All routes clone "hi", but the GET requests are different.

https://github.com/seanmonstar/warp/blob/2587c5939a8775044edc41ad5997aac82ecf59ea/src/filters/path.rs#L109

**Comment by LovecraftianHorror** [comment]
The part you called out is hidden in the documentation and it seems the example is just demonstrating that `or` is used to chain filters, so I see nothing wrong with the current documentation.
