### ISSUE TITLE
WebSocket incoming message type clarification

### ISSUE THREAD

**Issue by kellytk** [seanmonstar/warp#509]
Will any message type (ping, pong, etc.) be potentially received by `rx.next()`?  I read in an issue* that `tungstenite` will automatically reply to ping frames with a pong frame.  Is the consequence that my code will never receive a ping frame to handle?

https://github.com/seanmonstar/warp/blob/4687c03ed9620e1ae8aaa4fd6cbd8e100091e584/src/filters/ws.rs#L334 via https://github.com/seanmonstar/warp/issues/368#issuecomment-572237862

**Comment by apiraino** [comment]
Hi, I'm reading this issue and have followed the issue mentioned. I'm trying to understand if ping/pong frames are correctly managed (either by Warp of the underlying tungstenite library behind).

By looking [at the current documentation](https://docs.rs/warp/0.2.2/warp/filters/ws/struct.Message.html#method.ping) it looks like it is, am I reading it correctly?

thanks

**Comment by jxs** [comment]
> Will any message type (ping, pong, etc.) be potentially received by rx.next()? I read in an issue* that tungstenite will automatically reply to ping frames with a pong frame. Is the consequence that my code will never receive a ping frame to handle?

yeah, even if tungstenite [automatically replies to ping messages](https://github.com/snapview/tungstenite-rs/blob/431b6d9241416ccabd31db53b9ef831d6eaaaf91/src/protocol/mod.rs#L161)
those messages are [still received in the stream](https://github.com/seanmonstar/warp/blob/master/src/filters/ws.rs#L338), you can check in the [tungstenite example](https://github.com/snapview/tungstenite-rs/blob/f7e9cb097e063f4bfe916f43aa71e9e7544f53d1/README.md#tungstenite) that it explicitly discards Ping messages
