### ISSUE TITLE
API available for dropping the underlying TCP connection of a WebSocket

### ISSUE THREAD

**Issue by kellytk** [seanmonstar/warp#511]
A malicious WebSocket client may not conform to the specification's expectation that it respond to a server-initiated close message.  Instead, it may continue to send messages and the spec as I understand it allows for that.  To address malicious traffic, is it possible to immediately drop the underlying TCP connection of a WebSocket?

**Comment by seanmonstar** [comment]
You can drop the websocket whenever you want, which will abruptly drop the TCP connection.

**Comment by kellytk** [comment]
Excellent, which API should be used please?

**Comment by seanmonstar** [comment]
I mean `drop`, nothing special.
