### ISSUE TITLE
async log?

### ISSUE THREAD

**Issue by mjibson** [seanmonstar/warp#512]
I'm trying to add a filters::log::custom that logs all requests to a database. I have something like:

```
	let log_db = db.clone();
	let db_log = warp::log::custom(move |info| {
		let client = log_db.client.lock().await;
		client
			.execute(
				"INSERT INTO log (...) VALUES (...)",
				&[...],
			)
			.await;
	});
	
	let routes = v1_filters::routes(db)
		.with(db_log)
		...
```

The two `.await` calls are causing problems because closures can't be async yet. There's an `async move || ...` thing but it's not on stable yet.

What is the recommended way to add this kind of logging to an async-dependent database connection? Is there another way to do it that doesn't involve the log filter? Can I write my own filter that does this?

**Comment by docapotamus** [comment]
Hi @mjibson. Can you not just replace the closure with a function?

**Comment by bwalter** [comment]
Unless you want to wait for the logging to completed, you could simply spawn a Tokio task:

```
...
let db_log = warp::log::custom(move |info| {
  tokio::spawn(async move {
    // log via DB using await
    ...
  });
});
```

**Comment by mjibson** [comment]
This doesn't appear to work:

```
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
note: first, the lifetime cannot outlive the anonymous lifetime #2 defined on the body at 12:33...
note: ...so that the types are compatible
note: ...so that the type `impl core::future::future::Future` will meet its required lifetime bounds
```

There are perhaps some lifetime annotations I could add but my Rust understanding isn't quite deep enough yet.

**Comment by bwalter** [comment]
It should "generally" work but you need to ensure that every reference which is directly or indirectly passed to task::spawn() has the 'static lifetime (they are the same constraints which apply to the standard thread::spawn() function).

**Comment by mjibson** [comment]
Uh but the thing I need to pass is the info object or something derived from it, which isn't static. Unless there's some way to do that this doesn't seem like it will work.

**Comment by bwalter** [comment]
You can first extract (and clone if needed) the info out of log::Info before calling task::spawn().

**Comment by mjibson** [comment]
Ah ha thanks! I thought I tried cloning Strings already and it didn't work. Apparently it does and I was mistaken.
