### ISSUE TITLE
websocket chat example more explanation please

### ISSUE THREAD

**Issue by ggerico** [seanmonstar/warp#522]
Hello everyone,

When the client side closes the websocket connection, line 79 `user_ws_rx.next().await` returns `Poll::Ready(None)` which turns into an `Err(e)` which causes to break the while loop, and calls finally the `user_disconnected` function , which cleans up the shared data. 
Is that right?

After that we reached the closing curly bracket of the user_connected function at line 88 and the task`tokio::task::spawn(rx.forward(user_ws_tx)` spawned at line 62 is now dropped. 
Is that right?
 
I feel stuck in an async life time loop ;-) 
Tks ~

**Comment by jxs** [comment]
Hi, the example has been updated, is it better explained now?

**Comment by ggerico** [comment]
Thank you for your explanation, I think I just don't understand the basic of tokio and the futures crate, nothing directly related to warp.
