### ISSUE TITLE
HTTP 3 Support

### ISSUE THREAD

**Issue by clintnetwork** [seanmonstar/warp#533]
Hey,

Do we have any news about HTTP3 support (or QUIC)?

Kind regards

**Comment by LucioFranco** [comment]
There is work going into hyper to support h3, once that lands warp will get it for free basically.

**Comment by clintnetwork** [comment]
Oh nice!

**Comment by LoganDark** [comment]
> There is work going into hyper to support h3, once that lands warp will get it for free basically.

There already exist at least two crates that support HTTP/3, it would be nice if warp could support one of them anyway. It doesn't look like h3 is going to be a thing for at least a couple more years.

**Comment by banocean** [comment]
> > There is work going into hyper to support h3, once that lands warp will get it for free basically.
> 
> There already exist at least two crates (quinn and quiche) that support HTTP/3, it would be nice if warp could support one of them anyway. It doesn't look like h3 (as support in hyper) is going to be a thing for at least a couple more years.

Isn't this `hyper` part? Also, both of those crates are QUIC implementation not HTTP/3

**Comment by LoganDark** [comment]
> Isn't this `hyper` part?

Uhh, maybe it is now that it's over three years later, sure.
