### ISSUE TITLE
bind_with_graceful_shutdown kills open websocket connections on graceful shutdown

### ISSUE THREAD

**Issue by psmit** [seanmonstar/warp#545]
My goal is to implement graceful shutdown for my server with both HTTP and WS routes. In my trials however, all (open, long-running) WebSocket connections are killed immediately when the graceful shutdown future is resolved.

- Is this how the code is working, or am I testing this wrong?
- If it is working like this, is it a bug, or is it intentional?
- If intentional, is there an advised way to implement the behavior I seek?

**Comment by jxs** [comment]
Hi, you are probably right. You can implement graceful shutdown for websockets the way [`mini-redis`](https://github.com/tokio-rs/mini-redis/) [implements](https://github.com/tokio-rs/mini-redis/blob/master/src/server.rs#L202): using [`mpsc`](https://docs.rs/tokio/0.2.21/tokio/sync/mpsc/index.html) sharing a `Sender` for each websocket connection and awaiting on a ` Ok(Ready(None))` message
