### ISSUE TITLE
What is the function signature for future filters?

### ISSUE THREAD

**Issue by dakom** [seanmonstar/warp#546]
For example, this does not compile:
(note that `handle_index()` is not `async` but `handle_hello()` is)

```
pub fn get_route_filters() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    path::end()
        .map(handle_index)
        .or(path!("hello" / String).map(handle_hello))
}

async fn handle_hello(name:String) -> String {
    format!("Hello, {}!", name)
}

fn handle_index() -> String {
    format!("ready to rock!!!!")
}
```

**Comment by seanmonstar** [comment]
If you want to chain async steps along, you need to use `Filter::and_then` instead of `map`.

**Comment by dakom** [comment]
aha, thanks - so this `impl Filter` declaration on the return is generally going to be correct, no matter what filters its using?

**Comment by dakom** [comment]
swapping out the `.map()` for `.and_then()` didn't work for me... what am I missing? :)

**Comment by seanmonstar** [comment]
`and_then` requires a future either a `Result`. Check the examples and documentation.

**Comment by dakom** [comment]
Thanks - checking out the examples helped a lot :)

**Comment by seanmonstar** [comment]
Sorry if my comment came across as curt, I was on mobile and it's hard to find the exact links or write code.

**Comment by dakom** [comment]
lol, and the irony here is that I genuinely meant that checking out the examples helped me - wasn't being sarcastic, if that's how I accidentally came across!

all good, thanks for the great lib, docs, and example code :D

**Comment by dakom** [comment]
I'm still having a bit of trouble, if you have a minute...

From what I understand so far - Filters are never async. They are meant to be created immediately, but they can call async functions via `and_then()`. So that means if I want to have a top-level function that gets a request and responds in an async fashion, I actually need to return a Filter that extracts a `Reply`, something like this:
```
pub fn get_auth_token() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    warp::header::<String>("Authorization")
        .or_else(|err| async { Err(no_auth_err()) })
        .and_then(|token: String| async move {
                Ok(
                    warp::reply::json(&AuthTokenResponse{ token })
                )
        })

fn no_auth_err() -> Rejection {
    warp::reject::custom(NoAuth)
}
```

But then when I try and do this in my top level route, I get errors:

```
pub fn get_routes() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone + 'static {
    path::end()
        .map(handle_index)
        .or(path!("get-auth-token").map(get_auth_token))
        .or(path!("profile")
            .and(auth_get_user())
            .and_then(handle_get_profile)
        )
        .or(path!("settings").map(handle_settings))
        .recover(handle_rejection)
        .with(get_cors())
}
```

Of course I haven't pasted _all_ the code there (like get_cors, auth_get_user(), handle_rejection(), etc.) - but I think I'm really missing something fundamental about what Filters _are_ and how to chain them properly

If you happen to see what I'm doing wrong and why I keep getting stuck, I'd really appreciate it.

Another thing is that it tends to happen when I'm refactoring - like the separation of `and()` with `and_then()` in the `profile` handler seems to be fine, but then when I try to merge them into one filter, something is going wrong in my understanding / type sigs

**Comment by dakom** [comment]
I _think_ understand a little better - but got stuck on a simpler isolated type problem. opened an issue here: https://github.com/seanmonstar/warp/issues/554
