### ISSUE TITLE
missing reject docs

### ISSUE THREAD

**Issue by dakom** [seanmonstar/warp#550]
The functions at https://docs.rs/warp/0.2.2/warp/reject (e.g. [custom](https://docs.rs/warp/0.2.2/warp/fn.custom.html) and [not_found](https://docs.rs/warp/0.2.2/warp/fn.not_found.html)) are missing links.

`not_found` is particularly ironic ;)

**Comment by jxs** [comment]
the structs also give 404's, but if built locally with `cargo doc` they work fine. Might be a docs.rs bug?

**Comment by jxs** [comment]
fixed on the release of `0.2.3`
