### ISSUE TITLE
Handle dynamic count of filters

### ISSUE THREAD

**Issue by garyhai** [seanmonstar/warp#552]
I try to write a file server with chain of `or(warp::fs::dir(base_folder_n))`. The shared folders is configured in settings file. I am getting into trouble to handle dynamic count of filters.

I don't know how to make it work as the code below.
```rust
let folders = vec!["./a", "./b", "./c"];
let mut services = failure_filter_as_any();
for folder in folders.iter() {
    services = services.or(warp::fs::dir(folder));
}
```

**Comment by rphmeier** [comment]
This is a fundamental restriction of the Rust type system. The type `X` can't be the same as `Or<X, Y>`. This is basically what Warp does.

There is a way out, though. Use the `boxed()` method to create a trait object. https://docs.rs/warp/0.2.2/warp/trait.Filter.html#method.boxed

I haven't tried your code, but something like this should work.
```rust
let folders = vec!["./a", "./b", "./c"];
let mut services = failure_filter_as_any().boxed();
for folder in folders.iter() {
    services = services.or(warp::fs::dir(folder)).boxed();
}
```

That said, each level of boxing incurs an allocation and a virtual dispatch into the call chain (although LLVM can sometime _devirtualize_, I'm not sure it can in this situation).

Until Rust gets variadic generics, I don't think you could do something like a `multi_or` at the library level.

Maybe there's something to be said for a `dirs_ordered` function that matches all of those directories.

**Comment by garyhai** [comment]
Thanks a lot. Your answer resolved one question in my struggling with warp filters.

```rust
async fn start_web(th: &Thing) -> Result<AbortHandle> {
    let endpoint: SocketAddr = th["bind"].as_str()?.parse()?;
    let conf = &th[Void];
    let prefix: String = conf.get("prefix").try_into().unwrap_or_default();
    let mut root = warp::any().boxed();
    if !prefix.is_empty() {
        root = root.and(warp::path(prefix)).boxed();
    }
    let (web, ah) = abortable(warp::serve(root.and(thing_service(conf))).run(endpoint));
    runtime::spawn(web);
    Ok(ah)
}
```
