### ISSUE TITLE
Support X-Forwarded-For in the logs

### ISSUE THREAD

**Issue by bertptrs** [seanmonstar/warp#553]
The access logs that are automatically generated by `warp::filters::log::log()` and `::custom()` functions have some kind of access to the remote end of the stream, but this doesn't work that well with a reverse proxy in front of it.

Would it be possible to support the `X-Forwarded-For` header as a source of the client IP address? I think it's currently impossible to do this as a library user since (correct me if I'm wrong) it's not possible to build wrapping filters.

**Comment by seanmonstar** [comment]
It should be possible to get that from `info.request_headers()`, right?

**Comment by bertptrs** [comment]
Yes, it should! I hadn't looked for unreleased features yet, but it's there. It's not that high priority for me personally so I'll wait patiently for the next release.

**Comment by flipchan** [comment]
Similar to #454
