### ISSUE TITLE
help understanding why .or works but .map doesn't

### ISSUE THREAD

**Issue by dakom** [seanmonstar/warp#554]
In the following example, why does the plain `.or()` work, but the `.map()` does not?

I have this defined as my routes:

```rust
pub fn get_routes() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone + 'static {
    path::end()
        .map(handle_index)
        .or(path!("get-auth-token").map(get_auth_token))
        //this works fine: .or(get_auth_token())
}
```

the `get_aut_token()` handler is defined like this:

```rust
pub fn get_auth_token() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone { ... }
```

I tried to figure it out from the error message, but I can't quite follow what's going on here:

> pub fn get_routes() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone + 'static {
>    |                                                ^^^^^^^^^^^^^^^^ the trait `warp::reply::Reply` is not implemented for `impl std::clone::Clone+warp::filter::Filter`

thanks!

**Comment by seanmonstar** [comment]
`map` takes the results of a filter and calls a function with them. To combine a filter like you're doing, use `and`.

**Comment by dakom** [comment]
That makes sense!

So in functional programming terms- we can kindof think of Filters as monads? e.g. the only way to get at the inner contents is via map/and_then.. all the other functions are more about changing the "outside" without affecting the inside?

Although.. `and()` _can_ affect what gets passed on to the next function.. (e.g. path parameters)...

I guess what I'm after is trying to build a better intuition.. Filters are a powerful and clever concept, and I'm still not 100% clear on how they are used as "handlers" vs. "request shapers" vs. "routes"

I'm sure it'll become clearer from playing with it and reading the source/docs/etc., but any more tips to grok it would be great. If you don't feel there's more to add right now- no worries, feel free to close this issue :)

Thanks again

**Comment by dakom** [comment]
btw changing it to `.or(path!("get-auth-token").and(get_auth_token()))` does not work... The errors I get are:

```
or(path!("get-auth-token").and(get_auth_token()))
   |          ^^ the trait `warp::generic::Tuple` is not implemented for `impl warp::reply::Reply`

   pub fn get_routes() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone + 'static {
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `warp::generic::Tuple` is not implemented for `impl warp::reply::Reply`
```

**Comment by dakom** [comment]
ok, I got it to work by changing the sig of `get_auth_token` to:

`pub fn get_auth_token() -> impl Filter<Extract = (impl warp::Reply,), Error = warp::Rejection> + Clone`

In other words wrapping `impl warp::Reply` as `(impl warp::Reply,)` - but I'm not totally clear on where this constraint came from...

**Comment by rphmeier** [comment]
The single-item tuple implements `Reply` as seen [here](https://docs.rs/warp/0.2.2/src/warp/reply.rs.html#500-508), so both return types are valid for a function actually returning `(impl Reply,)`. Anyway...

Looks like the requirement comes from this bound on [and](https://docs.rs/warp/0.2.2/warp/trait.Filter.html#method.and)

`<Self::Extract as Tuple>::HList: Combine<<F::Extract as Tuple>::HList>`.

The `F::Extract` must implement the `Tuple` trait, which I guess a single bare item doesn't.
