### ISSUE TITLE
with_map?

### ISSUE THREAD

**Issue by dakom** [seanmonstar/warp#556]
The todo example currently has this:
```
let admin_only = warp::header::exact("authorization", "Bearer admin");

warp::path!("todos" / u64)
    // It is important to put the auth check _after_ the path filters.
    // If we put the auth check before, the request `PUT /todos/invalid-string`
    // would try this filter and reject because the authorization header doesn't match,
    // rather because the param is wrong for that other path.
    .and(admin_only)
```

That makes perfect sense, but what if we have many routes that need to be protected by `admin_only`? Would be nice to not have to repeat that `.and(admin_only)` on each path, but rather wrap all the protected routes in one call.

Can `with()` somehow pass a setup filter's result down to all the filters it wraps, or perhaps some new `with_map()` is needed ?

**Comment by dakom** [comment]
on further thought I'm not sure how that would work, in terms of controlling order...

for example there could be a few global filters that might want to be defined for many paths but only run after the path as matched, such as json body parsing...

**Comment by jxs** [comment]
Hi, you can achieve that with:
```Rust
let admin_only = warp::header::exact("authorization", "Bearer admin");

warp::path!("todos" / u64)
.or(warp::path!("other_route1"/ u64))
.or(warp::path!("other_route2"/ u64))
.or(warp::path!("other_route3"/ u64))
.and(admin_only)
```
