### ISSUE TITLE
compression filter not checking Accept-Encoding header?

### ISSUE THREAD

**Issue by mpalomas** [seanmonstar/warp#558]
Hello,

First of all, I'm very new to Rust and thanks for Warp, as it is relatively easy to use for a newcomer.

Anyway, so I've just activated the gzip compression filter in my toy project, and the response header was indeed Content-Encoding: gzip, perfect.

But then, from my client (Postman), I disabled my user agent and Accept-Encoding header, and the response still came back gzip encoded. I was this time expected a regular, not compressed response, since I did not ask for it.

I'm no expert in HTTP, so either it's my misunderstanding, a documentation issue, or a bug: should Warp check for the Accept-Encoding header, and then call the registered compression filter only if it matches? Or the filter itself checking for this header value, you see what I mean?

**Comment by seanmonstar** [comment]
I believe the existing compression filters will always compress. There is an issue to add `auto()` which would negotiate with the `accept-encoding` header.

**Comment by arpanlaha** [comment]
I see the issue to add `auto` has been inactive for a while, are there plans to revive it?
