### ISSUE TITLE
redirect with non static path

### ISSUE THREAD

**Issue by stevensonmt** [seanmonstar/warp#562]
I cannot work out how to use warp to redirect with a non-static URI. My use case is that upon clicking a link users generate a UUID and this UUID will be passed as a parameter to the redirect URI. The documentation for the redirect function is confusing as it takes an `impl AsLocation` but that trait is hidden somewhere. What is the definition of `AsLocation` and what types implement it?
I expected something like this to work:
```
let redirection = warp::path!("redirecting")
    .map(|| {
        let uuid = rs_uuid::uuid8::uuid8();
        let new_user = warp::path("user" / uuid.to_string());
        warp::redirect(new_user)
```
How is one actually supposed to use the redirect function in warp? All of the previous issues on redirection that I could find refer to structs and methods outside of warp, which seems ... off.

**Comment by seanmonstar** [comment]
You can build an `http::Uri` and pass that as an argument.

**Comment by stevensonmt** [comment]
I had tried that but was getting an error. Turns out the error was using https for the scheme rather than http on my localhost. I thought I had a cert set up for local but I guess I need to address that. Thanks.
