### ISSUE TITLE
Problem to join routes in a loop

### ISSUE THREAD

**Issue by lumijad** [seanmonstar/warp#565]
Hi,
It is possible to join routes in a loop?
Something like this:

`        let route = warp::get()
            .and(warp::path(name.clone()))
            .and(with_state(state))
            .and_then(render);
        routes.or(route);
`

I think it is very easy but I'am a Java burned guy :-)

Thank you a lot
Regards
Rolf

**Comment by seanmonstar** [comment]
Not easily, at the moment. It's because `or` returns a brand new type, and so you can't assign that new value to an old one (the types differ).
