### ISSUE TITLE
Accessing peer certificate when acting as server with client TLS auth enabled

### ISSUE THREAD

**Issue by ajpauwels** [seanmonstar/warp#569]
This is similar/identical to this issue, which is now quite old:
https://github.com/seanmonstar/warp/issues/227

I figured out how to get client TLS authentication enabled, and I can successfully validate a request containing a client cert. However, I now need to be able to access that certificate's details in my route handlers in order to perform authorization. I've used the PR that came out of #227 as a starting off point and am very close to finishing the code changes to be able to do so (using the current, updated codebase), but I've finally gotten stuck.

I can't figure out how to pass the peer certificates from the `ServerSession` into my filter. I can access the `TlsStream` transport in the `into_service!` macro, but that gets called when the request initially comes in, therefore the stream state at that point is handshaking which does not give access to an underlying server session or peer certificates. Once the handshake is complete, I can see `call_with_addr` called on the service but, crucially, the context of this call happens in a closure that's only given access to an `http::Request` struct which itself has no access to the underlying `TlsStream` or `ServerSession`.

I initially thought I could create a custom peer certificates type and then store this inside the request as an extension, but I can't find a place where I can join both a `ServerSession` and the `Request`. I may just not be skilled enough at futures to see how to wait until the `TlsStream` is out of handshaking state before creating the service, so I could then pass in the resulting peer certificates.

**Comment by jxs** [comment]
Hi, yeah this is a known issue, it's waiting on https://github.com/hyperium/hyper/issues/2175

**Comment by ajpauwels** [comment]
I see, so this is likely a change that would span both hyper and warp?

**Comment by MikeCamel** [comment]
"I figured out how to get client TLS authentication enabled" ... is this documented anywhere?  I'm interested in playing with whatever's available until this is resolved (no recent movement on https://github.com/hyperium/hyper/issues/2175).

**Comment by obelisk** [comment]
@MikeCamel 
There is an example here: https://github.com/hyperium/tonic/tree/master/examples/src/tls_client_auth

**Comment by Geobert** [comment]
> 
> 
> @MikeCamel
> There is an example here: https://github.com/hyperium/tonic/tree/master/examples/src/tls_client_auth

This example doesn't use `warp`, does it? Or am I missing something?

**Comment by Geobert** [comment]
Any progress on this? Things like https://www.rfc-editor.org/rfc/rfc8705.html requires it :-/

**Comment by jxs** [comment]
going to close this in favor of #227
