### ISSUE TITLE
warp::path! macro doesn't accept qualified types with ::

### ISSUE THREAD

**Issue by joshtriplett** [seanmonstar/warp#572]
Writing `warp::path!("foo" / git2::Oid)` produces an error ```no rules expected the token `start` ```. Putting a `use git2::Oid` above that, and then writing `warp::path!("foo" / Oid)`, produces no error.

`warp::path!` should accept qualified type names.

**Comment by jhpratt** [comment]
Allowing `stringify!(foo)` in the same position would be great. I presume this has the same root cause.
