### ISSUE TITLE
How to apply Service- or Filter-wide headers ?

### ISSUE THREAD

**Issue by meteorfox** [seanmonstar/warp#573]
Currently, I have set of filters set up this way

```rust
let api = filters::api();
let server_header = warp::reply::with::default_header("Server", "foo v0.1.0");
let routes = api.with(&server_header);
```

Whenever requests are successful, I get the "Server" header in the responses, but the header is not included with rejection responses.

Is there a sort a Filter-wide headers that every response includes the set headers regardless of success or rejection ?

**Comment by jxs** [comment]
see #518
