### ISSUE TITLE
Limit HTTP version

### ISSUE THREAD

**Issue by aaneto** [seanmonstar/warp#575]
How would one limit the HTTP version on the server? I couldn't find a way in the documentation.

This might not be reasonable to be inside warp but it is a blocker on my use case. I can get into more details if needed, but basically HTTP/2 on browsers will give me a poor performance on requests with large bodies.

**Comment by seanmonstar** [comment]
You can convert a `Filter` chain into a `Service`, which you can then use with hyper's server builder, and configure `http1_only` there.

**Comment by aaneto** [comment]
After that TLS configuration would be manual I guess. A decent-sized workaround but I guess this is not really a common use case.

I'm closing this since it looks like this is possible with the current API.

**Comment by clintnetwork** [comment]
Maybe you can make an example in `examples` about how to force http/2 or use both etc.

**Comment by hemantku** [comment]
I have a working example for this, would be happy to add it back here
