### ISSUE TITLE
More generic broadcast function

### ISSUE THREAD

**Issue by undefinedbuddy** [seanmonstar/warp#577]
Based off the [websocket chat](https://github.com/seanmonstar/warp/blob/master/examples/websockets_chat.rs) example, I was able to broadcast data from the server to all connected clients. Would it be more reasonable to highlight how to achieve similar results with a more generic example? As in:

```rust
use warp::ws::{Message, WebSocket};

type Users = Arc<Mutex<HashMap<usize, mpsc::UnboundedSender<Result<Message, warp::Error>>>>>;

pub fn broadcast(ws: WebSocket, users: Users, msg: String);
```

I encountered some weird runtime issues in the process and I'd gladly appreciate assistance.

**Comment by seanmonstar** [comment]
I'm sorry, I don't understand your question, could you explain more?
