### ISSUE TITLE
Fix comments in websockets_chat example

### ISSUE THREAD

**Issue by lights0123** [seanmonstar/warp#578]
https://github.com/seanmonstar/warp/blob/a6fcf76d43e0b3a11f445aacf638094e7dcd008b/examples/websockets_chat.rs#L105-L117

This has a few problems:
* "We use `retain` instead of a for loop so that we can reap any user that appears to have disconnected." is the exact opposite of what actually happens in code and the comment just 3 lines later.
* As a result, `iter_mut` is unnecessary
  * We could then probably replace the `Mutex` in that demo with `RwLock` because you don't need exclusive access to send messages

**Comment by jxs** [comment]
Hi, thanks! wanna submit a PR addressing this?
