### ISSUE TITLE
header() not working on Windows

### ISSUE THREAD

**Issue by intramuros** [seanmonstar/warp#579]
Hi,

When I use `warp::header::<T>("some_header")` (i.e. with `T=SocketAddr` and "some_header"="host"), it constantly gives me a `Missing request header` error. 
However, inspecting headers with `warp::header::headers_cloned()` shows that that the target header is there. On top of that, `warp::header::optional(..)`  is also able to extract the target header.

My OS is Windows.

**Comment by seanmonstar** [comment]
Is the host address in the form of a socket address, or a domain?

Do you have a code example that I can test that shows it failing?

**Comment by intramuros** [comment]
Oh, sorry, this is my error. I was operating on the assumption that `localhost` will resolve into a `SocketAddr`.
