### ISSUE TITLE
Inefficiency of compression filters on large Bytes or String responses

### ISSUE THREAD

**Issue by rye** [seanmonstar/warp#590]
Another title for this issue could be "how should one compress large `Bytes` or `String` objects?"  (I'd love to write up an example and documentation to help future users understand how this works.)

Given the minimal working example

```rust
#[tokio::main]
async fn main() {
    use warp::Filter;

    warp::serve(
        warp::any()
            .map(|| include_str!("random-1M.dat").to_string())
    )
    .run("0.0.0.0:3000".parse::<std::net::SocketAddr>().unwrap())
    .await;
}
```

a typical request only takes a few milliseconds to prepare before content is sent back to the client (as measured by Chrome DevTools):

![no compression, fast response](https://user-images.githubusercontent.com/1566689/83178381-0bda4e80-a0e6-11ea-9a8b-d92f8eada95b.png)

However, with `gzip` compression enabled,

```rust
#[tokio::main]
async fn main() {
    use warp::Filter;

    warp::serve(
        warp::any()
            .map(|| include_str!("random-1M.dat").to_string())
            .with(warp::compression::gzip())
    )
    .run("0.0.0.0:3000".parse::<std::net::SocketAddr>().unwrap())
    .await;
}
```

a typical request takes a lot longer to get a response, spending quite a bit of time waiting for the server before that data gets sent back:

![with compression, long wait before content transfer starts](https://user-images.githubusercontent.com/1566689/83178665-7a1f1100-a0e6-11ea-999d-3d646763c8e2.png)

I think this is largely because the compression filter is immediately trying to compress the entire response body, which takes time on large bodies.

Is there a more idiomatic way to send back a very large `String` object with compression without such a large overhead, e.g. by splitting it into a `Stream` of chunks?  (Splitting on newlines would be one scheme, but for minified JSON as an example this would not work.)

If a more idiomatic way exists, I think it should be added to the `compression` example and documented, as I'm confident I won't be the last one to run into this.  (I'd be happy to do that!  I just need to know what way works.)

**Comment by jxs** [comment]
> I think this is largely because the compression filter is immediately trying to compress the entire response body, which takes time on large bodies.

Hi, hmm it shouldn't the [response is being streamed](https://github.com/seanmonstar/warp/blob/master/src/filters/compression.rs#L59) i'll try to reproduce that later and see what i can find

**Comment by seanmonstar** [comment]
Yea it compresses whole streaming, but in the example case, the entire body is available as a single chunk.

Actually, in this example, I'd suggest you could compress it at start up instead of per request...
