### ISSUE TITLE
How to compose warp log?

### ISSUE THREAD

**Issue by softshipper** [seanmonstar/warp#591]
Hi all
I am pretty new in Rust and trying to build a web application with https://docs.rs/warp/0.2.3/warp/index.html.  

I have tried:

    #[tokio::main]
    async fn main() {
        // GET /hello/warp => 200 OK with body "Hello, warp!"
    
        let cors = warp::cors()
            .allow_origin("http://localhost:8090")
            .allow_methods(vec!["GET", "POST", "DELETE"]);
    
        let log = warp::log("dashbaord-svc");
    
        let hello = warp::path!("hello" / String)
            .with(cors)
            .with(log)
            .map(|name| format!("Hello, {}!", name));
    
    
        warp::serve(hello)
            .run(([127, 0, 0, 1], 9999))
            .await;
    }

and the compiler complains: 

    error[E0277]: `warp::filters::log::internal::Logged` doesn't implement `std::fmt::Display`
      --> src/main.rs:16:43
       |
    16 |         .map(|name| format!("Hello, {}!", name));
       |                                           ^^^^ `warp::filters::log::internal::Logged` cannot be formatted with the default formatter
       |
       = help: the trait `std::fmt::Display` is not implemented for `warp::filters::log::internal::Logged`
       = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
       = note: required by `std::fmt::Display::fmt`
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)  

What am I doing wrong? 

Thanks

**Comment by rye** [comment]
I believe you need to `map` and then `wrap`, as in:

```rust
let hello = warp::path!("hello" / String)
    .map(|name| format!("Hello, {}!", name))
    .with(cors)
    .with(log);
```

The error message you're getting indicates that the value of `name` in your closure is not what you may be expecting (the value of the param) but instead a value of type `Logged`, which is produced by the `.with(log)` line.  (The `.with` method "wraps" a filter.)

**Comment by softshipper** [comment]
Thanks a lot.

**Comment by softshipper** [comment]
@rye I have change the code to: 

```
#[tokio::main]
async fn main() {
    // GET /hello/warp => 200 OK with body "Hello, warp!"

    let cors = warp::cors()
        .allow_origin("http://localhost:8090")
        .allow_methods(vec!["GET", "POST", "DELETE"]);

    let log = warp::log("dashbaord-svc");

    let hello = warp::path!("hello" / String)
        .map(|name| format!("Hello, {}!", name))
        .with(cors)
        .with(log);


    warp::serve(hello)
        .run(([127, 0, 0, 1], 9999))
        .await;
}
```  
And when I run it, it does not show any log output:

![Screenshot from 2020-05-31 22-19-36](https://user-images.githubusercontent.com/56756949/83361890-166a4180-a38d-11ea-8bcd-870ed6f9465b.png)

What am I missing?

**Comment by seanmonstar** [comment]
The `log` crate emits logs to an installed logger, which by default there isn't any. You can choose a logger to output your logs. `env_logger` is a simple one, but more complex ones exist such as log4rs, fern, etc.

**Comment by softshipper** [comment]
@seanmonstar I am pretty new in Rust. Could you please do an example?

**Comment by jxs** [comment]
@softshipper https://docs.rs/env_logger/0.7.1/env_logger/#example
