### ISSUE TITLE
Let's Encrypt example

### ISSUE THREAD

**Issue by Timmmm** [seanmonstar/warp#592]
It would be great if you could add an example showing how to integrate with Let's Encrypt (maybe via `acme-lib`). It's pretty much a requirement in modern web development.

Even better would be built in support so you can just do something like

    warp::serve_letsencrypt(routes, "foo.com").run(([0, 0, 0, 0], 443)).await;

and forget about it.

**Comment by Timmmm** [comment]
I did a bit of Googling and found [lets-encrypt-warp](https://github.com/droundy/lets-encrypt-warp) which does exactly what I want (though I haven't tried it yet). It would be great if Warp had this capability natively. I'll close this but it might be worth adding a link to that crate at least.

**Comment by PraxTube** [comment]
For anyone wondering how to actually set the keycs and run the server with lets encrypt, here is how you can do it.

```rust
    warp::serve(request)
        .tls()
        .cert_path("/etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem")
        .key_path("/etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem")
        .run(([0, 0, 0, 0], 3434))
        .await
```

Note two things:

1. You can `cp` both files and have them somewhere else.
2. You need `sudo` privileges as these files a read protected, if you run your warp server with something like `systemd` this won't really be a problem, but when testing you might encounter some issues.
