### ISSUE TITLE
try_bind should return a Future (or its docs are inconsistent)

### ISSUE THREAD

**Issue by abreis** [seanmonstar/warp#599]
I was going through `server.rs` and noticed that `Server::try_bind` says:

> (...) returning a `Future` that can be executed on any runtime.

but it actually ends in `.await;` and returns nothing. 

I dug around a bit and it did return a Future in the original PR in #250 (which is consistent with the behavior of `bind()`, but #265 changed that behavior. I can't tell if it that change was intentional or a lapse, so I'm only reporting the inconsistency.

**Comment by abreis** [comment]
Same for `TlsServer::bind` (which actually makes it inconsistent with `Server::bind`).

**Comment by ivan** [comment]
Don't all `async` functions return a `Future`?

**Comment by abreis** [comment]
Nevermind, I missed the fact that `Server::bind` is a plain `fn` but the others are `async fn`s.
