### ISSUE TITLE
Warp is also the name of a popular Haskell Web server

### ISSUE THREAD

**Issue by FranklinChen** [seanmonstar/warp#6]
I don't know if this is a genuine problem, but I thought I'd share that my first thought on learning about this exciting new project was, wait, "warp" is already the name of a popular Haskell Web server: https://hackage.haskell.org/package/warp

I know, name collisions are hard to avoid these days.

**Comment by seanmonstar** [comment]
Oh noes! I admittedly have never heard of that. I liked the name "warp" as a play on the name "hyper"... :shrug:

**Comment by aeleos** [comment]
There is also warp-server, a node express middleware package: https://www.npmjs.com/package/warp-server Personally I like the name.

**Comment by joshtriplett** [comment]
Even as a former developer of Haskell-based web apps, I don't think this is a particularly concerning issue. As noted in this issue, there are already multiple projects named "warp". The name fits well with "hyper", it's short and memorable, and I don't think people are likely to get confused between a web server for Haskell and a web framework for Rust.

**Comment by lpil** [comment]
As a extra item of data, when I read the headline of the announcement my first thought was whether it was affiliated in any way with the Haskell web server. Given both are high performance statically typed languages I think it's more likely to cause confused than with Python or Javascript.

**Comment by tshepang** [comment]
Regarding search entries, would "warp-rs" actually be better than "warp rust"?

**Comment by kellytk** [comment]
As long as they both satisfy my requirement they're equivalent to me.  `warp-rs` is only a suggestion should an alternate be opted for.

**Comment by richardanaya** [comment]
You aren’t going to please everyone on an internet full of millions of people. Name collisions are just going to be inevitable. I like Warp. “Warp Rust” google search brings me exactly where I need to go, other languages and hobbies can do the same.
