### ISSUE TITLE
Can I Use Warp With Other Executors?

### ISSUE THREAD

**Issue by zicklag** [seanmonstar/warp#601]
Is there a way to use Warp with an executor such as [`smol`](https://github.com/stjepang/smol) and avoid including Tokio? There is an [example](https://github.com/stjepang/smol/blob/master/examples/hyper-server.rs) of how to hook up `hyper` to use `smol`; is there any way that I could do something like that to run Warp on top of `smol`?

**Comment by seanmonstar** [comment]
It's probably possible, but I don't have the time to provide support or guidance on how to do, sorry.
