### ISSUE TITLE
is there any recommended way to generate REST documentation from code?

### ISSUE THREAD

**Issue by horacimacias** [seanmonstar/warp#605]
I'm trying to find a way to hopefully auto-generate REST documentation (e.g. postman collection) from code, to avoid code and documentation getting out of sync due to documentation not being updated whenever code does.

Is there any way, or does anybody have any suggestion on how to achieve this, hopefully with minimal or no manual intervention?

**Comment by horacimacias** [comment]
random thought: 

something like a special mode for running warp (e.g. env variable WARP_GENERATE_DOCS) so that whenever `warp::serve` is invoked while on this mode, the application just exits after dumping documentation on screen/file, given warp should already know most if not all the routes/paths?

**Comment by HiruNya** [comment]
Would this be a copy of #89 ?

**Comment by horacimacias** [comment]
ah yes, looks like that is already covered there. Sorry, I didn't see that earlier
