### ISSUE TITLE
Way to disable logging for particular routes

### ISSUE THREAD

**Issue by m3rcuriel** [seanmonstar/warp#610]
If I have a route which is going to return or take in PII, I would like to be able to disable logging for that route such that not even a `RUST_LOG=trace ./binary` will not log that data.

Is there any way to do that or should I just be careful to not enable logging in production?

**Comment by jxs** [comment]
Hi, you can [disable warp logging by module](https://docs.rs/env_logger/0.7.1/env_logger/#example) see "You can also set the log level on a per module basis:"
