### ISSUE TITLE
Hard cap on body upload size?

### ISSUE THREAD

**Issue by AblatedSprocket** [seanmonstar/warp#612]
I didn't see anything in the documentation about this, so I figured I'd ask for clarification. I want to upload PDFs and images to an endpoint but I can't seem to get around the 2MB limit on body upload size. I can reduce the payload to an arbitrary byte count below 2MB, though.

In case it's helpful, here's my route:

`warp::path("upload").and(warp::body::content_length_limit(1024 * 1024 * 40).and(warp::multipart::form()).and_then(upload_file))`

**Comment by seanmonstar** [comment]
The `form()` filter has an upload limit, you can adjust it with [`form().max_length(n)`](https://docs.rs/warp/0.2.*/warp/filters/multipart/struct.FormOptions.html#method.max_length)

**Comment by ayngling** [comment]
I had the same issue, was happy to find this. Mentioning this in an example could be helpful.
