### ISSUE TITLE
Outdated documentation on websocket Message

### ISSUE THREAD

**Issue by euclio** [seanmonstar/warp#620]
[`warp::filters::ws::Message`](https://docs.rs/warp/0.2.3/warp/filters/ws/struct.Message.html) claims that it only represents `Text` or `Binary`, but the message can also be `Close`.

I thought this meant that `Close` from clients was handled internally, but this is not the case.

**Comment by jxs** [comment]
Hi, yeah that line can be removed, want to submit a PR doing it?

**Comment by euclio** [comment]
Sure, just opened one.
