### ISSUE TITLE
[Question] Interrupting an `or` filter chain

### ISSUE THREAD

**Issue by Geobert** [seanmonstar/warp#622]
Hi there!

I have this default filter:
```
let get_default = warp::any()
        .map(warp::reply)
        .map(|reply| warp::reply::with_status(reply, StatusCode::NOT_FOUND));
```

so any non expected request returns 404 instead of 500 (especially favicon.ico requests).

It's set up like:

```
let get_routes = warp::get().and(get_filter1.or(get_filter2).or(get_assets).or(get_default));
```

but then, if `get_filter1` reply an error (401 in my case), warp jumps to `get_default` and the client receive 404 instead of my 401.

How to interrupt the or chain?

Or how to define get_default differently to do that?

**Comment by seanmonstar** [comment]
It looks like your "default" filter could instead be written using `Filter::recover`, so you can inspect what rejections occurred and send a custom response.

**Comment by Geobert** [comment]
> 
> 
> It looks like your "default" filter could instead be written using `Filter::recover`, so you can inspect what rejections occurred and send a custom response.

Like always, thanks for your answer!

I'll try that approach and post my solution here for posterity :)

**Comment by Geobert** [comment]
I already have a `recover`:

```rust
let routes = get_routes.or(post_routes).recover(customize_error);
```

and I noticed that any undefined request return `MethodNotAllowed` rejection so I added in `customize_error`:
```rust
// other error customization code
} else if let Some(_) = err.find::<warp::reject::MethodNotAllowed>() {
        code = StatusCode::NOT_FOUND;
        message = "NOT_FOUND".to_string();
    } else {
        code = StatusCode::INTERNAL_SERVER_ERROR;
        message = "UNHANDLED_REJECTION".to_string();
}
```

**Comment by songday** [comment]
Hi, I encountered this as well.
I defined many REST endpoints, `5 GET methods and 2 POST methods`

once I request one of POST methods, I found `Rejection` in `recover` has
```
&err = Rejection(
    [
        MethodNotAllowed,
        MethodNotAllowed,
        MethodNotAllowed,
        MethodNotAllowed,
        MethodNotAllowed,
    ],
)
```

these 5 `MethodNotAllowed` came from those 5 GET methods
this cause `if let Some(_) = err.find::<warp::reject::MethodNotAllowed>()` will be matched and I can't get `the real error`

why did this happen?
