### ISSUE TITLE
Make it easy (user-friendly!) to specify the type of a Warp server.

### ISSUE THREAD

**Issue by Nimelrian** [seanmonstar/warp#625]
Most of the examples I have seen create and run the warp server in a single function.

A user may want to separate the creation and the use of the server.

```rust
pub struct Webserver {
    server: warp::Server<???>,
}

impl Webserver {
    pub fn new() -> Webserver {
        let routes = warp::path!("hello").map(|| {
            "Hello there!"
        });
        let server = warp::serve(routes);

        Webserver { server }
    }

    pub async fn run(&self, address: impl Into<SocketAddr> + 'static) -> () {
        self.server.run(address)
    }
}


#[tokio::main]
pub async fn main() {
    Webserver::new().run(([0, 0, 0, 0], 8080)).await;
}
```

The type definition of `warp::Server` makes this incredibly difficult though, especially due to the fact that a lot of important types are hidden (See #607).
Is there any way _right now_ to specify the type in a user-friendly way? Is this something that will be possible in the near future? Ideally, I just want to specify the type as warp::Server and be done with it.

**Comment by jxs** [comment]
it's easier if you just isolate server running:
```Rust
use warp::{Filter, Reply};
use std::net::SocketAddr;

pub async fn run_server<F>(address: impl Into<SocketAddr> + 'static, routes: F)
 where
     F: Filter + Clone + Send + Sync + 'static,
     F::Extract: Reply,
{
    warp::serve(routes).run(address).await;
}
```
