### ISSUE TITLE
issue with moving cloned pool

### ISSUE THREAD

**Issue by zwhitchcox** [seanmonstar/warp#626]
So, I've been wrestling with this for over a day now and have [posted on reddit](https://www.reddit.com/r/rust/comments/hfulp7/rust_question_lifetime_of_a_closurebody/) about it, but I figure maybe I should just ask here.

Basically, I have the code from [this example](https://github.com/kaj/warp-diesel-ructe-sample/blob/master/src/session.rs#L123), and I'm trying to adapt it to use warp 0.2.4:

```rs
type PooledPg = PooledConnection<ConnectionManager<PgConnection>>;
type PgPool = Pool<ConnectionManager<PgConnection>>;

pub fn create_session_filter(db_url: &str) -> BoxedFilter<(Session,)> {
    let pool = pg_pool(db_url);
    warp::any()
        .and(cookie::optional("NORMAL_AUTH"))
        .and_then(move |key: Option<String>| async move {
            let pool = pool.clone();
            let key = key.as_ref().map(|s| &**s);
            match pool.get() {
                Ok(conn) => Ok(Session::from_key(conn, key)),
                Err(e) => {
                    error!("Failed to get a db connection");
                    Err(warp::reject::not_found())
                }
            }
        })
        .boxed()
}

fn pg_pool(database_url: &str) -> PgPool {
    let manager = ConnectionManager::<PgConnection>::new(database_url);
    Pool::new(manager).expect("Postgres connection pool could not be created")
}
```

but I get the error: 

```
expected a closure that implements the `Fn` trait, but this closure only implements `FnOnce`

this closure implements `FnOnce`, not `Fn`rustc(E0525)
session.rs(131, 10): the requirement to implement `Fn` derives from here
session.rs(131, 19): this closure implements `FnOnce`, not `Fn`
session.rs(131, 57): closure is `FnOnce` because it moves the variable `pool` out of its environment
```

I don't understand how this is moving `pool` out of its environment, because I'm using `clone`, which I thought created a copy and prevented the `move`. Is there a Warp Recommended Way® to do this?

As a side note, I looked at another [up-to-date example](https://github.com/zupzup/warp-postgres-example/blob/master/src/main.rs#L20), and they seem to be doing the same thing, so I don't understand why mine isn't working, and theirs does.

**Comment by jxs** [comment]
you'd probably want an async closure (see https://github.com/rust-lang/rust/issues/62290#issuecomment-626397542) but they are still feature gated, does it work by moving it first to the closure?
eg:
```Rust
pub fn create_session_filter(db_url: &str) -> BoxedFilter<(Session,)> {
    let pool = pg_pool(db_url);
    warp::any()
        .and(cookie::optional("NORMAL_AUTH"))
        .and_then(move |key: Option<String>| {
            let pool = pool.clone();
            async move {
                let key = key.as_ref().map(|s| &**s);
                match pool.get() {
                    Ok(conn) => Ok(Session::from_key(conn, key)),
                    Err(e) => {
                        error!("Failed to get a db connection");
                        Err(warp::reject::not_found())
                    }
                }
            })
        .boxed()
}

```

**Comment by zwhitchcox** [comment]
Ok, I don't know how you figured that out so fast, but thank you. It still doesn't really make sense to me, because I'm still new to rust, but I think I understand sort of.

Thanks again man, you do great work!
