### ISSUE TITLE
[Help Wanted]: Conditionally setting a header

### ISSUE THREAD

**Issue by benfjohnson** [seanmonstar/warp#627]
I've been working on building a game server via web sockets, and everything's gone really smoothly so far (the examples provided in this repo are incredibly helpful!). I'm now having a really hard time however conditionally setting a cookie if it doesn't already exist in an HTTP auth route. Here's my relevant code:

```
fn authenticate() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    warp::path("auth")
        .and(warp::cookie::optional("atid"))
        .map(| cookie: Option<String> | {
            match cookie {
                Some(_) => Response::builder().status(StatusCode::OK),
                None => {
                    let new_cookie = format!("atid={}", Uuid::new_v4());
                    Response::builder()
                        .status(StatusCode::CREATED)
                        .header(
                            header::SET_COOKIE,
                            new_cookie,
                        )
                },
            }
        })
}
```

Despite a few different examples I've seen suggesting to use a Response::builder, that doesn't seem to implement the warp::Reply trait. I've also tried removing the response builder, also without any luck:

```
fn authenticate() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    warp::path("auth")
        .and(warp::cookie::optional("atid"))
        .map(| cookie: Option<String> | {
            if let Some(_) = cookie {
                // cookie already exists, return an empty
                return warp::reply()
            }

            let cookie = format!("atid={}", Uuid::new_v4());
            warp::reply::with::header(header::SET_COOKIE, cookie)
        })
}
```

I've tried a bunch of variations of this, but I'd ideally like to respond with a 201 CREATED and set the cookie if it doesn't exist, otherwise return an empty 200. Anything obvious I'm missing?

Thanks!

**Comment by benfjohnson** [comment]
Update: I did end up finally solving this by using the `body` method on my builder objects, e.g. `Response::builder().status(StatusCode::OK).body("{}")`. I'd previously used an empty tuple as the argument to body (following online examples, which the compiler hadn't liked. Going to leave this open however as I'm curious if there's a better way of accomplishing the above. :slightly_smiling_face:

**Comment by jxs** [comment]
Hi, yeah `Reply` is impl'ed to `Response<T>` where [` Body: From<T>`](https://docs.rs/warp/0.2.2/warp/reply/trait.Reply.html#impl-Reply-for-Response%3CT%3E). You can check [here](https://docs.rs/hyper/0.13.2/hyper/struct.Body.html#implementations) which types `Body` impl's `From`
