### ISSUE TITLE
Attach authorization header to redirect response?

### ISSUE THREAD

**Issue by AblatedSprocket** [seanmonstar/warp#629]
I'm trying to add oauth2 to my server. After a user signs in, the oauth provider redirects to a callback on my site for taking the auth code and fetching a token. Ideally, I want to attach that token to my own 301 redirect pointing to the home page of my site. Here's the method that I have wrapped a filter around:

```
async fn validate(code_response: AuthCodeResponse, pkce_verifier: PkceCodeVerifier, csrf_token: CsrfToken, client: BasicClient) -> Result<impl Reply, Rejection> {
    let token: String;
    // Retrieve and validate token using code_response and other parameters.
    
    let response = Response::builder()
        .status(301)
        .header("authorization", format!("Bearer {}", token)))
        .header("Location", "/")
        .body("");
    Ok(response)
}
```

When this method executes, it redirects to the home page but there is no authorization header. I saw the documentation about the filter for adding header maps to responses. Is that what I have to use or can I make this work somehow?

**Comment by jxs** [comment]
Hi, what's probably happening is that the redirection response has the authorization header, but when you then `get` the homepage the response no longer has the authorization header
