### ISSUE TITLE
concurrent requests in warp

### ISSUE THREAD

**Issue by zwhitchcox** [seanmonstar/warp#630]
I'm following the [/kaj/warp-diesel-ructe-sample](https://github.com/kaj/warp-diesel-ructe-sample/blob/master/src/main.rs), and there is a request handler for [signing up that hashes the password](https://github.com/kaj/warp-diesel-ructe-sample/blob/master/src/main.rs#L124).

Unfortunately, this blocks the entire website from fulfilling any other requests while that password is hashing.

Do I need to spawn another thread somehow to run the hashing? Or is it recommended to just use multiple instances of warp servers?

**Comment by asonix** [comment]
try using block_in_place: https://docs.rs/tokio/0.2.21/tokio/task/fn.block_in_place.html
or spawn_blocking: https://docs.rs/tokio/0.2.21/tokio/task/fn.spawn_blocking.html

**Comment by zwhitchcox** [comment]
Thanks!! That worked..

For anyone else, I used this code:

```rs
        .and_then(|form: NormalSignUpForm| {
            let password = form.password.clone();
            let hash = task::block_in_place(move || {
                bcrypt::hash(&password, bcrypt::DEFAULT_COST)
                .map_err(|e| format!("Hash failed: {}", e)).expect("couldn't hash password")
            });
            Ok((form, hash))
        })
```

and editing `Cargo.toml` with

```toml
tokio = { version = "0.2", features = ["macros", "blocking", "rt-threaded"] }
```

And just keywording here stuff I searched for: multithreading warp rust concurrent requests async blocking
