### ISSUE TITLE
warp::header::<String> allows sending invalid chars

### ISSUE THREAD

**Issue by andrewbanchich** [seanmonstar/warp#634]
I just spent some time debugging why `reqwest` was sending a request to a `warp` server, but the server wasn't receiving them. `reqwest` was configured to add a header which was a `String`, and `warp` was using a `warp::header::("MyHeaderName")` filter with a handler that accepted a `String` argument. Almost all of the time it worked, but on a few instances it just never received anything, and there were no errors.

It turned out that the client had added a `String` which had some special Spanish chars in it, which needed to be URL encoded.

Is there a way to prevent this kind of misuse using Rust's type system (e.g. `filters::header<T: FromUrlEncodedStr ...`)?

**Comment by jxs** [comment]
Hi, see #242
