### ISSUE TITLE
How to use a non-static that doesn't implement Clone or Copy?

### ISSUE THREAD

**Issue by jkaye2012** [seanmonstar/warp#635]
I'd like to write a route that uses [google_signin::Client](https://docs.rs/google-signin/0.3.0/google_signin/struct.Client.html). This structure doesn't impl Clone or Copy. My plan was to write a function that takes a reference to the client and returns a route. It looks like this isn't going to work out because Warp filters seem to want static lifetimes. The code that I currently have looks like this:

```rust
pub fn auth_google<'a>(
    client: &'a Client,
) -> impl warp::Filter<Extract = (WithStatus<Json>,), Error = warp::Rejection> + 'a + Copy {
    warp::path!("auth" / "google" / String)
        .and(warp::post())
        .map(
            move |id_token: String| match authenticate_google_user(client, &id_token) {
                Ok(user) => warp::reply::with_status(warp::reply::json(&user), StatusCode::OK),
                Err(_) => {
                    warp::reply::with_status(warp::reply::json(&"Bad"), StatusCode::NOT_FOUND)
                }
            },
        )
}
```

This function compiles alone without issue; however, when I attempt to use it with a Warp server:

```rust
    let google_client = create_google_client();
    let auth = auth_google(&google_client);

    warp::serve(auth)
        .run(([0, 0, 0, 0], 3030))
```

The build tells me that the borrow does not live long enough. I've done some digging and haven't found much written about a better way to do this, but I assume I'm just approaching this in the wrong way and that there's some other way to go about this. Does anyone have any solutions or suggestions? I'm happy to restructure this code in a more idiomatic way as well if that's part of the problem here. Ideally I'd like to avoid other third-party crates or global statics, if at all possible.

Thanks,
Jordan

**Comment by seanmonstar** [comment]
Can you put the client in an `Arc`, so it can be cloned?

**Comment by jkaye2012** [comment]
It looks like that works well, thank you! This is what I have now:

```rust
pub fn auth_google<'a>(
    client: Arc<Client>,
) -> impl warp::Filter<Extract = (WithStatus<Json>,), Error = warp::Rejection> + 'a + Clone {
    warp::path!("auth" / "google" / String)
        .and(warp::post())
        .map(
            move |id_token: String| match authenticate_google_user(&client, &id_token) {
                Ok(user) => warp::reply::with_status(warp::reply::json(&user), StatusCode::OK),
                Err(_) => {
                    warp::reply::with_status(warp::reply::json(&"Bad"), StatusCode::NOT_FOUND)
                }
            },
        )
}
```

Just a quick question while I'm talking to someone with more Rust experience - I have read a bit on Arc, Rc, Box, etc. after having this brief conversation. I understood previously that these were "pointer types" that allocate on the heap, allowing different passing semantics and such (similar to how you would create a pointer/reference to pass a type with no move or copy constructor in C++). Is there any way in a situation like this to not pass the actual Arc into the function (and instead, for example, create the Arc and pass a raw reference instead)? I'm thinking that it may not be possible due to how borrows work in the Rust type system - essentially by passing the Arc, we're explicitly saying "this is not a borrow, we need to "dynamically" extend the lifetime of the instance to encompass the lifetime of the function as well.

I was really just wondering if my line of thinking is correct here or if I have something subtly wrong? This will help grow my knowledge of the language. Thanks again!
