### ISSUE TITLE
How to handle errors in handlers

### ISSUE THREAD

**Issue by nicholasbishop** [seanmonstar/warp#636]
I'm trying to wrap my head around how to handle errors in handlers without too much boilerplate.

Ideally I would like to be able to write handlers in terms of the successful response type and an unsuccessful error type, with some way to convert from the error type to a `Reply`. For example, something like this:

```rust
use warp::{reply::Response, Filter, Reply};

#[derive(Debug, thiserror::Error)]
enum MyError {
    #[error("error 1")]
    Error1,
}

impl Reply for MyError {
    fn into_response(self) -> Response {
        match self {
            MyError::Error1 => todo!(),
        }
    }
}

fn my_handler() -> Result<&'static str, MyError> {
    Ok("hello world")
}

#[tokio::main]
async fn main() {
    let routes = warp::any().map(my_handler);
    warp::serve(routes).run(([127, 0, 0, 1], 3030)).await;
}
```

But that doesn't compile. I assume that the generic `Func` accepted by `map()` doesn't know to look for `Result<T, E>` where `E` implements `Reply`. I briefly looked at how `Func` is implemented but it is beyond me :)

I think error handling is supposed to be covered by the [rejections.rs](https://github.com/seanmonstar/warp/blob/master/examples/rejections.rs) example, but it's pretty complicated and doesn't look like it would work with `?` error propagation. Also it starts with this comment: "Rejections represent cases where a filter should not continue processing the request, but a different filter *could* process it." Maybe this is just describing the generic use of Rejections, but usually with error handling I'm interested in the terminal case, e.g. my handler fails to talk to the database so it should immediately fail with a 500 error. It's not clear to me whether the rejections.rs example is supposed to speak to that?

I found https://blog.logrocket.com/create-an-async-crud-web-service-in-rust-with-warp/, which does show some `?` error propagation, but it still requires using `map_err` everywhere as well as a fairly verbose function that extracts the custom error type from a `Rejection` to convert it to a `Reply`.

I also found a similar StackOverflow question, but it hasn't gotten any answers: https://stackoverflow.com/questions/61013311/warp-rs-warprejection-and-error-handling-using

**Comment by jxs** [comment]
> But that doesn't compile. I assume that the generic Func accepted by map() doesn't know to look for Result<T, E> where E implements Reply.

yeah you are right, for that you need [`and_then`](https://docs.rs/warp/0.2/warp/trait.Filter.html#method.and_then)
> think error handling is supposed to be covered by the rejections.rs example, but it's pretty complicated and doesn't look like it would work with ? error propagation. 

to help with that you can impl:
```Rust
impl From<YourError> for warp::reject::Rejection {
    fn from(error: Error) -> warp::reject::Rejection {
        warp::reject::custom(error)
    }
}
```
there's also https://github.com/seanmonstar/warp/pull/396

**Comment by nicholasbishop** [comment]
> yeah you are right, for that you need and_then

Oh! Thanks, the documentation had me thinking that the difference between `map` and `and_then` was that `map` was for non-async functions and `and_then` was for async functions, but I guess there's more to it.

I'll go ahead and close this, thank you for the suggestions and links.
