### ISSUE TITLE
Unseal Wrap trait

### ISSUE THREAD

**Issue by L-as** [seanmonstar/warp#638]
I don't understand why the Wrap trait has to be sealed.

**Comment by seanmonstar** [comment]
It was sealed in case the design of the trait needed to evolve. For now, since it doesn't seem like things need to really change, we can probably unseal it.

**Comment by L-as** [comment]
Thanks! I also see a lot of other potentially useful but private code in the crate, like `filter_fn`. Are these other things always going to be private, or are they potentially going to be made public at some point?

**Comment by jxs** [comment]
see https://github.com/seanmonstar/warp/issues/607#issuecomment-650448029

**Comment by aujxn** [comment]
@jxs Should this be closed after #693 and #842 merge?

**Comment by jxs** [comment]
yup, makes sense thanks!
