### ISSUE TITLE
How to access/provide/config custom Hyper instance ?

### ISSUE THREAD

**Issue by singggum3b** [seanmonstar/warp#639]
Hi all.
I dig around the source and its seem to me that's there is no way to configure/access or provide a factory for custom Hyper instance ? Did i miss some thing ?

**Comment by seanmonstar** [comment]
Warp doesn't expose much config for the underlying hyper server. If you'd like to configure it yourself, you can use [`warp::service`](https://docs.rs/warp/0.2.3/warp/fn.service.html) (the linked docs include an example of doing exactly that).
