### ISSUE TITLE
Reject with other status code?

### ISSUE THREAD

**Issue by osmarks** [seanmonstar/warp#64]
I'd like to be able to reject requests with status codes currently not available, like 401 Unauthorized; is this possible?

**Comment by algermissen** [comment]
You might want to read my https://github.com/seanmonstar/warp/issues/62

In my understanding (having a little Akka background), rejections are not meant for error responses. Yes, rejections work with status codes and lead to responses, but in the case of 401 for example, we do not want to reject, but respond with a 401 response. IOW, we do not want a filter down the chain to recover the rejection. It is the protocol to return 401.

**Comment by seanmonstar** [comment]
It's just as @algermissen described, especially with the changes coming in #115. Any customizing of rejections should be done via `Filter::recover`, and returning a new `Reply`.
