### ISSUE TITLE
hot upgrade & hot restart

### ISSUE THREAD

**Issue by hongliang5316** [seanmonstar/warp#644]
Is there an example to demonstrate http `hot upgrade` and `hot restart` like https://github.com/facebookarchive/grace  In production environment ?

**Comment by jxs** [comment]
Hi, there's an example of [`bind_with_graceful_shutdown`](https://docs.rs/warp/0.2.3/warp/struct.Server.html#example)

**Comment by hongliang5316** [comment]
> Hi, there's an example of [`bind_with_graceful_shutdown`](https://docs.rs/warp/0.2.3/warp/struct.Server.html#example)

@jxs 
Hello, lgtm:)
