### ISSUE TITLE
Change SSE module to be more like WS

### ISSUE THREAD

**Issue by seanmonstar** [seanmonstar/warp#645]
The `sse` module uses `trait SseEvent` and helper functions that return `impl SseEvent`, and while clever, these cause confusion (see #296) and make it difficult to match types up (see #643). This issue describes how we should change `sse` to be more like `ws`, which just uses plain structs (`ws::Messasge`).

- Create a `struct Event`.
- This should probably have private fields for `name`, `id`, `data`, and `retry`. Some should probably all be optional? Some research there will help us to know which can be optional.

**Comment by aknuds1** [comment]
Is this issue still relevant? I just see there's currently no trait SseEvent in the filters::sse module.

**Comment by seanmonstar** [comment]
This was done in #663.

**Comment by aknuds1** [comment]
Cool :)
