### ISSUE TITLE
Clarify use of futures in filter chains

### ISSUE THREAD

**Issue by algermissen** [seanmonstar/warp#65]
I am working on case, where one can look up an item from a database. The get_item(id) function returns a future because the lookup is async, of course.

I had some substantial trouble figuring out how to work with the future inside the and_then() combinator, mostly due to the lack of impls of Rejection for common error (and other types).

This is where I ended up:

```
let get_item = path!("item" / i32 ).and_then(|id| {
        repository::get_item(id).map(|item:String| {
            http::Response::builder().status(http::StatusCode::OK)
                .body(format!("This is item {}", item)).unwrap()
        }).map_err(|_| warp::reject())
    });
```
Note the use of `map_err(|_| warp::reject())` to have an error-type that the filter chain can work with.

So, even if I return HTTP responses for success and error cases (and explicitly not a rejection), I need to convert to Rejection so that the types match.

Two solutions would have helped me (I think):
- Make warp::never::Never public, so that I can err_map to that
- provide CombineRejection impls for () as is done for Never so that I can err_map to ()

Am I making sense? Did I miss something? Or is it just due to missing examples?

I am also curious whether you plan to add another combinator like and_then but which allows me to supply an explicit reactor to run the supplied future on. (eg see https://docs.rs/futures/0.2.1/futures/trait.FutureExt.html#method.with_executor )

**Comment by seanmonstar** [comment]
As part of #97, a new example was added to explicitly show using a `Future` inside `Filter::and_then`.

Probably a remaining piece here is to update the docs of `Filter::and_then` to clarify that any future returned needs to have its error mapped to a `Rejection`.
