### ISSUE TITLE
Should MissingConnectionUpgrade be public?

### ISSUE THREAD

**Issue by wmain** [seanmonstar/warp#653]
Hi there! I'm working with `warp` as an introduction to building web services with Rust and am building an application that uses Warp's fantastic websocket support. 

In order to handle a custom error I'm appending a `recover` handler to my chain of filters, much like in the rejections example, and am handling my custom error there. If a user hits the `ws` endpoint without the proper headers, however, they'll get thrown into the fall-through "Unhandled rejection" case even though Warp is aware that this is a `MissingConnectionUpgrade` `Rejection`. Is there a better way to handle this or should `MissingConnectionUpgrade` be public?

**Comment by jxs** [comment]
Hi, yeah it seems it should be public as other `Known` rejections are public, want to submit a PR making it public?

**Comment by wmain** [comment]
Will do, thanks!
