### ISSUE TITLE
Debug routes

### ISSUE THREAD

**Issue by MSleepyPanda** [seanmonstar/warp#66]
Is there a way to debug routes? I'm 99% sure my route is correct, yet it gets rejected with 204 No Content.

I'm missing the following to effectively debug the routes:
 - A way to log all requests with
   - status:
     - "/route/to/data" - 200 Ok
     - "/route/does/not/exist" -  204 No Content
   - and optionally debug output:
     - "/route/does"... rejected, no matching path element "does" found
 - A debug view, perhaps tree style, which shows all possible paths

Is there something along those lines available?

**Comment by algermissen** [comment]
Have you looked at the log filter? It does partially what you need:
https://github.com/seanmonstar/warp/blob/25e6c4e09c898c103c0da0a6ddecf8625bfa762e/examples/todos.rs#L98

**Comment by MSleepyPanda** [comment]
Haven't seen that one, thanks

**Comment by seanmonstar** [comment]
If you enable logging (not even using the `warp::log` filter, just setting up a logger like pretty_env_logger and setting `RUST_LOG=warp`), you can see trace logs of filters trying to apply themselves.

I do think it'd be quite useful to be able to implement `fmt::Debug` for the filters, so you can print out a tree of what exists...

**Comment by MSleepyPanda** [comment]
I wasn't aware that warp uses log underneath, i found out when checking the source of `warp::log`. The output is really useful!

If something like a cookbook is planned, a section about debugging paths etc. would be _really_ helpful :)

I might want to take a shot at the debug view: A list of possible paths with `{:?}` and a tree with the pretty printed debug view `{:#?}`
