### ISSUE TITLE
Is there a function similar to url_for in flask for templates?

### ISSUE THREAD

**Issue by evitalis** [seanmonstar/warp#660]
I looked through the docs and might just be missing it, but is there an equivalent to [url_for](https://flask.palletsprojects.com/en/1.1.x/api/#flask.url_for) in flask? It essentially allows you use the name of a function to generate a URL saving a full path being hardcoded into the template.

Copying this here per https://github.com/Keats/tera/issues/533

**Comment by seanmonstar** [comment]
Sorry, no, that functionality doesn't exist in warp, and likely can't due the way `Filter`s work.
