### ISSUE TITLE
Async Filters: how?

### ISSUE THREAD

**Issue by apiraino** [seanmonstar/warp#664]
I'm trying to write an async filter that creates a Future that uses a DB connections pool. I can't compose the filter to make this work. The errors I receive are a bit confusing, I'm trying to reduce my code to create a minimal sample to illustrate the problem.

```
pub fn endpoint(
    db: DbPool,
) -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    warp::path!("product" / u32)
        .and(warp::get())
        .and(with_db(db))
        .and_then(check_auth(db))
        .and_then(get_product)
}

// retrieve auth token, validate user
pub async fn check_auth(
    db: DbPool,
) -> impl Filter<Extract = (UserProfile,), Error = Rejection> + Clone {
    warp::header::<String>("Authorization").and_then::<String>(move |header: String| async move {
        let db_client = db.get_conn().await?;
        let user_profile = auth::get(&db_client, value.to_string()).await?;
        Ok(user_profile)
    })
}

pub async fn get_product(
    user_profile: UserProfile,
    db: DbPool,
) -> Result<Box<dyn warp::Reply>, Infallible> {...}
```

`check_auth` is supposed to run a get a DB conn and run a query.

If it helps, some of the errors I receive:

```
   |
67 | ) -> impl Filter<Extract = (Auth,), Error = Rejection> {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an `Fn<(std::string::String,)>` closure, found `std::string::String`
   |
```

```
38 |  .and_then(check_auth(db))
   |            ^^^^^^^^^^^^^^^^^^^^^ the trait `std::clone::Clone` is not implemented for `impl core::future::future::Future`
```

```
38 |   .and_then(check_auth(db))
   |             ^^^^^^^^^^^^^^^^^^^^^ expected an `Fn<(u32, std::string::String, db::DbPool)>` closure, found `impl core::future::future::Future`
   |
```

I've checked other similar issue in this repo, example [this](https://github.com/seanmonstar/warp/issues/546#issuecomment-620639994), [this](https://github.com/seanmonstar/warp/issues/594) [or this](https://github.com/seanmonstar/warp/issues/521#issuecomment-609439945). They're quite close but I can't extract the useful bits for my case.

I hope I can come back to my issue and improve the question.

thanks for a suggestion

**Comment by jxs** [comment]
Hi, you can't a function with a return type of `Impl Filter` to an [`and_then`](https://docs.rs/warp/0.2.4/warp/trait.Filter.html#method.and_then) handler. To insert your own filters on a filter chain you have to use [`and`](https://docs.rs/warp/0.2.4/warp/trait.Filter.html#method.and)

**Comment by apiraino** [comment]
thanks for the reply.

Ok my first mistake, based on the answers to [this](https://github.com/seanmonstar/warp/issues/521) issue I thought I had to use `and_then`  to return a TryFuture.

now the chain looks like this
```
    warp::path!("product" / u32)
        .and(warp::get())
        .and(with_db(db))
        // fix here
        .and(check_auth(db))
        .and_then(get_product)
}
```
now the error on `check_auth` changed to 
```
38 | .and(check_auth(db, false))
   |          ^^^^^^^^^^^^^^^^^^^^^ the trait `warp::filter::FilterBase` is not implemented for `impl core::future::future::Future`
```

which I guess indicates that I need to do something to decalre that function? Does the `check_auth` function signature appear to be correct at a visual inspection?

I'll try focusing with more precise questions:

- What does this error actually mean (sorry screenshot because text breaks alignment), how do I pass additional parameters to the closure? I read that `warp::headers` can only have one parameter. 
![2020-07-21_14:44:04](https://user-images.githubusercontent.com/6098822/88056361-b314b880-cb60-11ea-80a8-52fafd480d00.png)
- what does the error "the trait `std::clone::Clone` is not implemented for `impl core::future::future::Future" actually mean in this context (see my prev. comment)? What do I need to clone? I tried cloning the db pool but it doesnt work.

**Comment by jxs** [comment]
> now the error on `check_auth` changed to 
```
38 | .and(check_auth(db, false))
   |          ^^^^^^^^^^^^^^^^^^^^^ the trait `warp::filter::FilterBase` is not implemented for `impl core::future::future::Future`
```

that error may be happening because `check_auth` has an `impl Future` return type, `and` requires the input type to be `impl Filter`

> What does this error actually mean (sorry screenshot because text breaks alignment), how do I pass additional parameters to the closure? I read that warp::headers can only have one parameter.

you can pass aditional params via filters, check the [todos](https://github.com/seanmonstar/warp/blob/master/examples/todos.rs#L55) example

we have moved the questions to the [discord chat](https://discord.gg/RFsPjyt), if you have further questions can you ask there so it's easier to address?
thanks
