### ISSUE TITLE
Relax `'static` requirement of `bind`'s `addr: impl Into<SocketAddr>` argument

### ISSUE THREAD

**Issue by JamesHinshelwood** [seanmonstar/warp#666]
I might be misunderstanding, but I'm struggling to work out why a `'static` lifetime is required for `bind` and `bind_ephemeral`'s `addr` argument. I've removed it and warp still compiles fine with all the tests passing.

My particular use case is that I'm configuring the server's port externally (so it can be changed without recompilation), so my address doesn't have a `'static` lifetime. I could use `Box::leak` to work around this if there's a good reason to keep the `'static` lifetime.

**Comment by seanmonstar** [comment]
I'm pretty sure I added `'static` bounds because without it the compiler complained. It might be that the compiler has gotten better at realizing the type doesn't extend that far? If removing them means it still works, I'm happy to!

**Comment by JamesHinshelwood** [comment]
@seanmonstar Thanks for the reply. If you don't mind I'll prepare a PR which removes the `'static` bound. I might also take a look at other places that require `'static` and see if they can be relaxed too.

**Comment by tiby312** [comment]
It would be nice if serve() didnt have static bound as well!

**Comment by james-bigpay** [comment]
@tiby312 In my PR I've removed the `'static` bound from the `F` parameter of `serve()`. Is this what you meant? 

https://github.com/seanmonstar/warp/pull/667/files#diff-4ce93534efc34e923ce01e975eb7ed80L23-L27
