### ISSUE TITLE
Parse structured syntax name suffixes in `content-type` for `filters::body::json`

### ISSUE THREAD

**Issue by genbattle** [seanmonstar/warp#668]
I've been trying to use `warp::filters::body::json` to handle input for an API that is using the [JSON:API format](https://jsonapi.org/format/).

Unfortunately `filters::body::json` expects a media type of `application/json` and doesn't handle other media types that specify a [`+json` Structured Syntax Name Suffix](https://tools.ietf.org/html/rfc6839#page-4). It would be great if it could handle this suffix and allow media types such as `application/vnd.api+json`.

**Comment by genbattle** [comment]
Looking at the code it seems like this is mainly hamstrung by the `mime` crate, which also doesn't really support Structured Syntax Name Suffixes. It might be possible to hack it into `is_content_type`, but that seems like a sizable change.

For now it seems like the easiest way forward for me is to replicate the `json` filter with my own `content-type` enforcement. Feel free to close this issue if adding support for structured name suffixes is unlikely to happen anytime soon.

**Comment by seanmonstar** [comment]
I'd prefer to open up the body deserializer filters to allow specifying preferred content types, and even content negotiation. There's an issue about content negotiation, but I haven't fleshed it out well at all...

**Comment by jxs** [comment]
the issue is https://github.com/seanmonstar/warp/issues/4

**Comment by genbattle** [comment]
I'm happy for this issue to be closed in favor of #4

**Comment by jxs** [comment]
@genbattle can you comment there then? 
thanks
