### ISSUE TITLE
Is there a way to group routes?

### ISSUE THREAD

**Issue by hah** [seanmonstar/warp#672]
_sorry I hit enter before typing the description_

Since  typing out the routes one by one onto a variable can get messy, I wonder if there is a similar approach possible with Warp like this:
https://gin-gonic.com/docs/examples/grouping-routes/

thanks a lot

**Comment by jxs** [comment]
Hi, yeah it's possible:
```Rust
    let v1 = warp::path("v1").and(
        path!("login").and_then(login_endpoint)
            .or(path!("submit").and_then(submit_endpoint))
            .or(path!("read").and_then(read_endpoint)),
    ); 
```
