### ISSUE TITLE
Feature request: `and_then()` that does not consume Extract

### ISSUE THREAD

**Issue by jakajancar** [seanmonstar/warp#673]
This would allow the pattern:

```
extract_something_expensive()
    .and_then(is_foo).and(foo_handler)
    .or_else(is_bar).and(bar_handler)
```

**Comment by jxs** [comment]
Hi, you can achieve that with [`untuple_one`](https://docs.rs/warp/0.2.4/warp/trait.Filter.html#method.untuple_one)

**Comment by jakajancar** [comment]
Hmm, I’m not sure. I understand untuple_ one, but how does that allow two and_then’s to use the same extracted value?

**Comment by jxs** [comment]
`untuple_one` allows one to remove the extracted previous extracted value. If you want for two `and_then`'s to use the same extracted value you can do:
```Rust
extract_something_expensive()
    .and_then(is_foo)
    .and_then(is_bar)
```
where `is_foo` passes the extracted value, or you can pass the extracted value via Rejection on `is_foo` and receive it on `is_bar` using `or_else`:

```Rust
extract_something_expensive()
    .and_then(is_foo)
    .or_else(is_bar)
    .and_then(bar_handler)
```
see https://github.com/seanmonstar/warp/issues/586#issuecomment-636538763 for another example on using `or_else`

**Comment by jakajancar** [comment]
Thanks @jxs!
