### ISSUE TITLE
Unable to pass arrays or maps as query string parameters

### ISSUE THREAD

**Issue by xorxsan** [seanmonstar/warp#677]
**Version**
warp v0.2.4

**Platform**
Windows 64 bit

**Description**
Unable to pass arrays or maps as query string parameters

I tried this code:
```rust
use warp::Filter;

#[derive(serde_derive::Deserialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct ArrayMapRequest {
    pub an_array: Vec<i32>,
    pub a_map: std::collections::HashMap<String, String>,
}

async fn test_query_string(
    request: ArrayMapRequest ,
) -> Result<impl warp::Reply, std::convert::Infallible> {
    println!("{:#?}", request);
    Ok(warp::reply::reply())
}

#[tokio::main]
async fn main() {
    let test_query_string= warp::path!("test_query_string")
        .and(warp::get())
        .and(warp::query::<ArrayMapRequest >())
        .and_then(test_query_string);

    warp::serve(test_query_string)
        .run(([0, 0, 0, 0], 3030))
        .await;
}
```

I expected to see this happen: 
`curl "http://localhost:3030/test_query_string?an_array[0]=1&an_array[1]=2&a_map[foo]=bar&a_map[faa]=baz" -g -v`
warp returns 200 and it prints something like:
```
ArrayMapRequest {
   an_array: [0, 1],
   a_map: {
    "foo": "bar",
    "faa": "baz",
  }
}
```
Instead, this happened: 
warp returns 400 Bad request with following content: 
```
< HTTP/1.1 400 Bad Request
< content-type: text/plain; charset=utf-8
< content-length: 20
< date: Tue, 28 Jul 2020 21:29:32 GMT
<
Invalid query string* Connection #0 to host localhost left intact
```
I've seen that Warp uses `serde_urlencode`. What about `serde_qs`? I think that library is able to parse this kind of query strings.

**Comment by jxs** [comment]
Hi, In order to switch to serde_qs or similar, we'd probably need to include a description of the pros and cons.
to overcome this issue you can switch to a `POST` request, or grab the raw query string, and parse it yourself with `serde_qs` using `warp::query::raw()`. Alternatively i think you can also impl `Deserializer` for your type

**Comment by Clee681** [comment]
I was hoping to accept a list in query parameters as well. Either `ids=[1,2,3]` or `ids=1,2,3`. It sounds like switching to `serde_qs` is unlikely in the near future. Is there a convention / recommendation for handling vectors? I'm still new to Rust so I'm not sure what implementing `Deserializer` would look like.

**Comment by xorxsan** [comment]
Hi @Clee681,

   I've slightly updated the test program of my first post:
```
use warp::Filter;

#[derive(serde_derive::Deserialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct ArrayMapRequest {
  pub an_array: Vec<i32>,
  pub a_map: std::collections::HashMap<String, String>,
}

async fn test_query_string(request: String) -> Result<impl warp::Reply, std::convert::Infallible> {
  let this_request = serde_qs::from_str::<ArrayMapRequest>(&request);
  println!("{:#?}", this_request);
  Ok(warp::reply::reply())
}

#[tokio::main]
async fn main() {
  let test_query_string = warp::path!("test_query_string")
    .and(warp::get())
    .and(warp::query::raw())
    .and_then(test_query_string);

  warp::serve(test_query_string)
    .run(([0, 0, 0, 0], 3030))
    .await;
}
```
This way you do not need to implement `Deserialize` yourself. Here I'm passing the raw query string with `.and(warp::query::raw())` and then parsing it using `serde_qs`.

The curl request looks like the following:
`curl "http://localhost:3030/test_query_string?anArray[0]=1&anArray[1]=2&aMap[foo]=bar&aMap[faa]=baz" -g -v`

Hope it helps.

**Comment by jxs** [comment]
there's also been an update comment by @kaj showing another way,
see https://github.com/seanmonstar/warp/issues/733#issuecomment-722359432

**Comment by Clee681** [comment]
Awesome, thanks @jxs @xorxsan. I came up with my own solution and posted it in https://github.com/seanmonstar/warp/issues/732#issuecomment-744146370. It was a lighter-weight solution to installing `serde_qs`, and it let me still use a custom struct for any other params. Let me know what you think! Maybe this could be a utility function exposed by warp?
