### ISSUE TITLE
Any example of how to upload file using warp?

### ISSUE THREAD

**Issue by karims** [seanmonstar/warp#681]
I have tried discord, but no luck.

Is there an example of how to upload a file using warp? A simple one atleast?

**Comment by sternix** [comment]
Hi, i found a test for multipart form,
https://github.com/seanmonstar/warp/blob/master/tests/multipart.rs

may be it gives a idea,

**Comment by karims** [comment]
I saw it. Its just too cryptic to understand anything. Not sure which is the file param and where it will store the uploaded file. Can only make out that it reads some key values.

**Comment by karims** [comment]
Also, throws the following erros:

```
vec.put(data);
    |                             ^^^ method not found in `std::vec::Vec<_>`

```

and
```
               value.map_ok(move |vec| (name, vec))
    |                           ^^^^^^ method not found in `futures_util::stream::try_stream::try_fold::TryFold<impl futures_core::stream::Stream, impl core::future::future::Future, std::vec::Vec<_>, [closure@src/main.rs:48:68: 51:22]>`

```

**Comment by sternix** [comment]
For the error, add 
-----8<----------
bytes = "0.5"
futures = "0.3"
-----8<----------
to the Cargo.toml

and use 
use bytes::BufMut; // this adds put method 
use futures::{TryFutureExt, TryStreamExt}; // for stream ops,
