### ISSUE TITLE
Expose raw Request object with rejections

### ISSUE THREAD

**Issue by jsdw** [seanmonstar/warp#684]
When an error occurs, I want to be able to respond to the user with something appropriate.

In the general case I'd like to look at the `Accepts` header and work out from that whether to provide the error back in the form of JSON or plain text or html.

In the specific case of serving static files, I'd also like to look at the request path so that I can use it alongside the `Accepts` header to figure out whether or to serve a root `index.html` file or return a 404 (to play nicely with the browser history API when doing client side routing. Logic is along the lines of; do they accept text/html, and does the path not end with an extension). 

If when catching errors using `recover`, I had access to the underlying `Request` made by the user, I'd be able to achieve both of these things quite nicely.

**Comment by jxs** [comment]
> In the general case I'd like to look at the Accepts header and work out from that whether to provide the error back in the form of JSON or plain text or html.

that can be done by returning different `Rejection`'s according to the Accepts header. 

regarding the specific usecase for the `fs` filter, see https://github.com/seanmonstar/warp/issues/209#issuecomment-491006819
