### ISSUE TITLE
Add filter to obtain raw `http::Request` object

### ISSUE THREAD

**Issue by jsdw** [seanmonstar/warp#685]
Warp filters provide an elegant way to pluck and match on properties of an incoming `Request` to then use in a handler. However, it's difficult to write code that abstracts away the underlying warp implementation when one can only rely on filters to pull out the bits and pieces that are needed from a request. It's also difficult writing code that can be shared across warp and other frameworks. Therefore, what I'd like is to be able to get at the underlying Request object, so that warp-agnostic code can be plugged in to warp with the minimum of effort. I believe this solves both issues.

# My use case to motivate this feature

In my case, I am using warp to serve a JSON based API alongside some static content and so on. There are several invariants I want to be enforced across my API routes, and common behaviour across them. So, I wrote a layer on top of `warp` to provide/enforce these. In my case, this looks something like the following (but the specifics aren't important):

```rust
let (all_routes, method_infos) = api_routes!{state =>
    {
        name: extract_data,
        description: "Provide an SPSS or CSV file and this route will hand back data extracted from it",
        handler: |args: api::FormDataArgs| routes::extract_data(args.data)
    },
    {
        name: extract_data_at_url,
        description: "Provide a URL to some SPSS or CSV file and this route will hand back data extracted from it",
        handler: |args: api::JsonArgs<_>| routes::extract_data_at_url(args.body)
    },
    {
        name: get_group_and_variable_ids,
        description: "Get the list of group and variable IDs",
        handler: |args: api::GetArgs| routes::get_group_and_variable_ids(args.state,args.user)
    },
    // ...
}
```

This returns the relevant warp handlers `.or`d together, as well as providing documentation/type info for each route. It does so by using traits and some magic around the handler type to decide for each route which warp filters I need to split out in the case of the route needing JSON, FormData, or no body at all. This is pretty complex owing to the type based nature of composing warp filters, but also ties me to `warp` and prevents this layer from being used with other http servers.

What I _really_ want, is to be able to delegate part of the problem to warp (eg matching on "/api" to find my API routes), but otherwise write my API handler code such that it doesn't care at all about `warp` and can just emit a function from `Request` to `Result<Response>` that I can then trivially hook into warp. This might end up looking a bit like:

```rust
let (route_handler_from_req_to_res, method_infos) = api_routes!{state =>
    {
        name: extract_data,
        description: "Provide an SPSS or CSV file and this route will hand back data extracted from it",
        handler: |args: api::FormDataArgs| routes::extract_data(args.data)
    },
    // ...
}

let api_routes = warp::path("/api")
  .and(warp::filters::request)
  .and_then(|req: Request| {
    match route_handler_from_req_to_res(req).await {
      // route matched; hand back response:
      Ok(Some(res)) => Ok(res),
      // no errors but route not found; let warp find the next match for us:
      Ok(None) => Err(warp::reject::not_found()),
      // some error; convert into a warp rejection to return:
      Err(e) => Err(warp::reject::custom(HttpErrorWrapper(e)))
    }
  });
``` 

This makes my API layer portable across different frameworks (provided that I can get at a request object and emit something derived from a response). It also means that my API layer does not need to care about things like "how to check whether a user is authenticated or not" (this can be delegated to individual handlers). At present, it **must** care about these things, as I'd need to add a filter to extract such details up front if they are required.

# Other motivation: composition

Functions from `Request` to `Response` can be composed in more contexts than warp filters, but also can form the building blocks of warp filters. Consider the case of authenticating a user:

```rust
// Current: We must write a filter for reusable "user auth":
warp::path("/foo)
    .and(authenticate_user_filter())
    .and_then(|user| { 
        /** work with the user and serve something */
    })

// Proposed: User auth could be a warp agnostic function (and
// might already exist in a codebase independent of warp): 
async fn authenticate_user(req: &Request) -> Result<User,Error>;

// This could be turned into a warp filter easily enough if we like:
fn authenticate_user_filter () -> impl Filter<Extract=(User,),Error=warp::Rejection> {
    warp::filters::request().and_then(|req| async {
        authenticate_user(&req)
            .await
            .map_err(|e| earp::reject::custom(e))
    })
}

// We could use the filter, or hook into the "raw" version if
// we need more control over how it's handled:
warp::path("/foo)
    .and(authenticate_user_filter())
    .and_then(|user| { 
        /** work with the user and serve something */
    })
warp::path("/foo)
    .and(warp::filters::request())
    .and_then(|req| async { 
        if let Ok(user) = authenticate_user().await {
            // I can decide how to handle the user existing or not here,
            // rather than the filter deciding. I can also compose it
            // with other agnostic functions here to layer code on top
            // of warp that can be used within it.
        }
    })
```

# Summary

I think that exposing a raw `http::Request` type object (or something that can be converted into it) would allow warp to interoperate more smoothly with non-warp code, and promote the creation of more generic code that isn't tied to warp. This warp agnostic code can be composed more easily than warp filters, but can be trivially turned into filters when valuable, too.

Thanks for taking the time to read this, and I'd love to know what you think :)

**Comment by jsdw** [comment]
(FYI if this sounds acceptable, I'd be happy to figure out how to add it and submit a PR for it)

**Comment by jxs** [comment]
Hi, yeah this has already been discussed in https://github.com/seanmonstar/warp/issues/139, see https://github.com/seanmonstar/warp/issues/139#issuecomment-454908070

**Comment by jsdw** [comment]
Perfect, thank you for pointing me towards that!

**Comment by danielSanchezQ** [comment]
Hi guys. 
I'm working on this: https://crates.io/crates/warp-reverse-proxy, just in case it is helpful for anyone.  It exposes the filter I'm using internally to extract the request data. It is not perfect but I'll be delivering features soon.
