### ISSUE TITLE
`warp::query::raw` rejects if query is empty

### ISSUE THREAD

**Issue by jsdw** [seanmonstar/warp#686]
(seen on Warp 0.2.4)

This may not be a bug, but it was unexpected to me so I thought I'd raise it here incase others run into similar!

`warp::query::raw()` returns a `String` corresponding to the query part of the request path. If there is no query part, I had expected this to return an empty string, but instead it rejects. Thus, there is no obvious way that I can see of extracting whatever query string happens to be present, if any.

I'd suggest either allowing this to never fail (return an empty string if no query), or adding a `raw_optional` to correspond to other optional variants of filters.

What do you guys think?

**Comment by jxs** [comment]
you can extract applying an `or_else` filter, see https://github.com/seanmonstar/warp/issues/586#issuecomment-636538763

**Comment by jsdw** [comment]
Ah, excellent! I was not aware that that was possible; clearly I should dig through the docs more! Thanks for taking the time to reply.

I do wonder what the convention is for providing optional variants of filters or not, given that we can make anything optional. I guess we are just aiming to make the common case easier.
