### ISSUE TITLE
exact_ignore_case example uses exact

### ISSUE THREAD

**Issue by larswirzenius** [seanmonstar/warp#688]
**Version**
Commit: a8551cf0edc4a306f4c7ae5a24345f921d283cb9

**Platform**
Any

**Description**
In the example docstring for warp::filters::header::exact_ignore_case the example is:

~~~rust
let keep_alive = warp::header::exact("connection", "keep-alive");
~~~

The example should probably use exact_ignore_case.

**Comment by jxs** [comment]
thanks! would you like to address it by submitting a PR?
