### ISSUE TITLE
Redundant INFO log when starting server

### ISSUE THREAD

**Issue by kotx** [seanmonstar/warp#730]
**Is your feature request related to a problem? Please describe.**
I have the default log level set to INFO in my application. Unfortunately warp likes to log two log messages at startup that effectively mean the same thing. This isn't very important, but it gets a bit annoying.
```
[2020-10-23T04:04:16Z INFO warp::server]: Server::run; addr=127.0.0.1:7878
[2020-10-23T04:04:16Z INFO warp::server]: listening on http://127.0.0.1:7878
```

**Describe the solution you'd like**
Remove this first line:
```
[2020-10-23T04:04:16Z INFO warp::server]: Server::run; addr=127.0.0.1:7878
```
An alternative would be to change the log level of that message to DEBUG.

**Describe alternatives you've considered**
I could just roll with these log messages, or disable logging for INFO level messages from warp. (I don't know how to do the second one though.)

**Additional context**
Not much. N/A.

**Comment by kotx** [comment]
This isn't exactly a feature or a bug.

**Comment by jxs** [comment]
Hi, yeah that's right, https://github.com/seanmonstar/warp/blob/master/src/server.rs#L134 seems redundant, would you like to submit a PR addressing this?

**Comment by kotx** [comment]
Sorry about the mess, borked the first commit so I made another. Opened PR in #735.
