### ISSUE TITLE
Does Warp have a plan that support tokio 0.3 and bytes 0.6?

### ISSUE THREAD

**Issue by songday** [seanmonstar/warp#750]
**Is your feature request related to a problem? Please describe.**
`bytes 0.6` has some breaking changes

**Describe the solution you'd like**
downgrade bytes to 0.5 and tokio to 0.2

**Describe alternatives you've considered**
not yet :(

**Additional context**
Currently, I upgraded tokio from 0.2 to 0.3, and it depends bytes 0.6, so I upgrade bytes to 0.6 as well
but found many imcompatible places, such as: `Part.data()`, returns `bytes/buf/buf_impl/Buf` which does not exist in bytes 0.6

**Comment by jxs** [comment]
Hi, yes see https://github.com/seanmonstar/warp/issues/725
