### ISSUE TITLE
typo?  "intend" vs "instead"

### ISSUE THREAD

**Issue by stuartcrobinson** [seanmonstar/warp#754]
https://github.com/seanmonstar/warp/blob/master/src/filters/cors.rs#L195

i'm wondering if you meant:

> you didn't ***intend*** to access 

instead of 

> you didn't ***instead*** to access 

```
...
    /// This can allow websites you didn't instead to access this resource,
    /// it is usually better to set an explicit list.
    pub fn allow_any_origin(mut self) -> Self {
...
```

**Comment by seanmonstar** [comment]
Yes, that should say "intend", woops. Want to file a PR fixing it?

**Comment by stuartcrobinson** [comment]
👍  coming right up
