### ISSUE TITLE
warp::body::json is more than 100 times slower than fs::read_to_string + serde_json::from_str

### ISSUE THREAD

**Issue by Lesiuk** [seanmonstar/warp#757]
**Version**
0.2.5

**Platform**
Windows 10

**Description**
I noticed that sending 100 MB json file using curl to my endpoint is really slow (client + server at localhost).

Benchmarks I did:
fs::read_to_string + serde_json::from_str: 331 ms
warp::body::json: 39254 ms

**Comment by Lesiuk** [comment]
It looks like this bug https://github.com/serde-rs/json/issues/160 is still not fixed and parsing from_reader is much slower than parsing from_slice or from_str.

**Comment by Lesiuk** [comment]
Why are we using from_reader there if we are agregating whole json anyway?

**Comment by seanmonstar** [comment]
It's aggregating the body buffers, not flattening into a single buffer, to try to save on copies. If `from_reader` is significantly slower, it's probably faster if we flattened first...

**Comment by Lesiuk** [comment]
Command I was testing with
```curl --data-binary "@events.json" -H "Content-Type: application/json" -X POST http://localhost:3030/endpoint```

Json
https://drive.google.com/file/d/1-zeaCDudHSVdOgAXlyzpC6KOZMC7b_C2/view?usp=sharing

Filter
```    
let receive_processed_data = warp::post()
        .and(warp::path!("endpoint"))
        .and(warp::body::json::<EventDataRq>())
        .and_then(handlers::receive_processed_data);
``

**Comment by Lesiuk** [comment]
It looks like Rocket had similar issue some time ago.
https://github.com/messense/Rocket/commit/0e24373193d59bd9e6cc95b2727654d8652c96ef

**Comment by Lesiuk** [comment]
I changed implementation of Decode for Json to use from_slice and It finished in under 1s.

```
impl Decode for Json {
    const MIME: (mime::Name<'static>, mime::Name<'static>) = (mime::APPLICATION, mime::JSON);
    const WITH_NO_CONTENT_TYPE: bool = true;

    fn decode<B: Buf, T: DeserializeOwned>(buf: B) -> Result<T, BoxError> {
        let mut bytes = Vec::new();
        buf.reader().read_to_end(&mut bytes)?;
        serde_json::from_slice(&bytes).map_err(Into::into)
    }
}
```

**Comment by seanmonstar** [comment]
You could do `buf.to_bytes()` there, and change from an `aggregate()` filter internally to `bytes()`.
