### ISSUE TITLE
Why do the header and cookie filters require a &'static str

### ISSUE THREAD

**Issue by gzp79** [seanmonstar/warp#763]
I was trying to make the name of the cookie a config parameter, but as the `wrap::filters::cookie::optional` requires the name to be `'static str`. It cannot be configured.
ex: 
```
let cookie_name = config.auth_cookie_name.clone();
let state = warp::filters::cookie::optional(&cookie_name).map({
   let config = config.clone();
   move |cookie| database::Database::new(config.clone(), cookie)
});
```

**Comment by gdesmott** [comment]
I'm also suffering this problem when using `warp::header::exact()`.

**Comment by gzp79** [comment]
closing it as I'm not using warp any more and there was no update on the ticket for years
