### ISSUE TITLE
Example with root route and and other routes mounted to root route

### ISSUE THREAD

**Issue by mkastner** [seanmonstar/warp#767]
**Is your feature request related to a problem? Please describe.**
I can't find any documentation or example where the routes actually start with a root route. The examples I can find always start at some none root route.

**Describe the solution you'd like**
I'd like an example.

**Describe alternatives you've considered**
There are no alternatives

**Additional context**
n/a

**Comment by jxs** [comment]
Hi, there's an example for [`warp::path::end()`](https://docs.rs/warp/0.2.5/warp/filters/path/fn.end.html#example)

**Comment by seanmonstar** [comment]
"Mounting" in warp is nothing special, it's the way everything works. You can just `warp::path("prefix").and(routes)`. The doc page for [`warp::path`](https://docs.rs/warp/0.2.*/warp/filters/path/index.html) has an example of eventually "mounting" all the routes under `/math`.

**Comment by mkastner** [comment]
I apologize for my unclearly formulated request. To me, most likely only to me, the problem with the "/math" example is in fact, that it does not start at root and that I was not able to create a full "routing system". I've asked a similar question on stackoverflow and got an answer which put me – maybe I am the only one, who doesn't get it from what is explained in the "/math" example – on the right track:

https://stackoverflow.com/questions/65490367/how-do-i-mount-paths-in-with-rust-warp

That's the kind of example I was looking for, because it starts from scratch i.e. root and builds a routing system. At the time of writing my request here, I hadn't found out about [warp::path::end()](https://docs.rs/warp/0.2.5/warp/filters/path/fn.end.html#example) and that it serves as root. I had simply missed it in the documentation.

**Comment by hamza1311** [comment]
You aren't the only one. I also had difficulty figuring it out. I think routing example should include a route at root (`/`). If someone doesn't beat me to it, I'm willing to give that a shot in a couple of days.
