### ISSUE TITLE
Support Pong message in websocket Message

### ISSUE THREAD

**Issue by glebpom** [seanmonstar/warp#776]
**Is your feature request related to a problem? Please describe.**
Not sending valid pongs leads to channel termination by reverse-proxy (Nginx)

**Describe the solution you'd like**
Add `pong` function to `Message` struct. Currently, all other types of websocket messages are implemented

**Describe alternatives you've considered**
Auto-pongs

**Comment by jxs** [comment]
Hi, `tungstenite` automatically replies to ping messages see https://github.com/seanmonstar/warp/issues/509#issuecomment-618039971
