### ISSUE TITLE
Allow construction of websocket pong messages

### ISSUE THREAD

**Issue by henkkuli** [seanmonstar/warp#782]
**Is your feature request related to a problem? Please describe.**
I am writing websocket server and I'm mocking the `warp::filters::ws::WebSocket` with a custom type implementing `Sink<Message>` and `Stream<Item=Result<Message, Error>>`. To be able to test the timeout behavior of the code I need to manually respond to Ping messages with a Pong message. Currently the API doesn't provide a way to construct a Pong message.

**Describe the solution you'd like**
I'd like to be able to construct a [`Message`](https://docs.rs/warp/0.2.5/warp/filters/ws/struct.Message.html) representing a pong message. The API could be very similar to the existing `ping` function. For example the following (untested) code could be used:
```rust
/// Construct a new Pong `Message`.
///
/// Note that this is rarely needed as Ping messages are automatically responded with the corresponding Pong message by
/// the underlying socket. This is mainly provided for some unconventional use cases, like writing mock implementations
/// for tests
pub fn pong<V: Into<Vec<u8>>>(v: V) -> Message {
    Message {
        inner: protocol::Message::Pong(v.into()),
    }
}
```

**Describe alternatives you've considered**
An alternative could be to provide a `From` implementation for `tungstenite::protocol::Message`.

**Comment by henkkuli** [comment]
Would it help if I created a PR with the proposed code? Or should I wait for a comment from the maintainer?

**Comment by jxs** [comment]
Hi, yeah you can go ahead and submit a PR :)
