### ISSUE TITLE
in example routing.rs sum and times are *moved* under math

### ISSUE THREAD

**Issue by rseymour** [seanmonstar/warp#79]
Me a noob: /sum/1/2 doesn't work, let's get off rust nightly and see if that's the issue, let's rebuild the app in debug and non debug

You the author: "math routes should be mounted to a different path" 

Me: that implies a copy not a move otherwise why would the example imply the original two routes work...

Turns out they don't which is fine but I was about 1 click away to just abandoning everything until I tried it.  I would suggest showing 'can be moved to a new route' separate from 'here are the 2 examples folks will try to see the neat pattern matching'

**Comment by seanmonstar** [comment]
Thanks for pointing this out. I'd like to remove any frustrations people run into, so it's good to know! I've adjusted the routing example to include the origin `sum` and `times` routes, while adding to their output that they have been moved.
