### ISSUE TITLE
HTTP/1.1 defaults to the use of "persistent connections"

### ISSUE THREAD

**Issue by silvioprog** [seanmonstar/warp#790]
Hi.

According to [RFC7230#Section-6.3](https://tools.ietf.org/html/rfc7230#section-6.3), in HTTP 1.1, all connections are considered persistent unless declared otherwise (e.g. by sending a header `Connection: close`).

Could you enable it by default in warp?

Thank you!

Refs.:

- https://tools.ietf.org/html/rfc7230#section-6.3
- https://en.wikipedia.org/wiki/HTTP_persistent_connection#HTTP_1.1

cheers

**Comment by seanmonstar** [comment]
Warp uses hyper for HTTP/1, and it does treat connections as persistent by default, as expected.

Are you running into a situation that is not reusing a connection?

**Comment by silvioprog** [comment]
I can't get the `keep-alive` header in the warp response, so I'm not sure if the connection is persisted. 😕

For example, supposing we are running the "hello" example, when performing this:

```curl -v http://localhost:3030```

it returns only the following headers (notice the `keep-alive` isn't present):

```
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
content-length: 13
date: Wed, 27 Jan 2021 04:11:49 GMT
```

however, when we perform this same request in other servers (e.g nginx/Apache), they return the `keep-alive` header in all requests.

I'm facing a problem in warp routing, it is slow if compared to other libs routing (I can send a small example and steps to reproduce it), so trying to debug the problem, I accidentally noticed the keep-alive missing. But I'm still not sure if the problem is related to the routing layer or the keep-alive. 😕

**Comment by seanmonstar** [comment]
HTTP/1.1 made keep-alive the default, so that header is not required. With 1.1, the only thing that matters is `connection: close`.

I'm going to close this since persistent connections are enabled, but certainly file an issue with a small example if you find a bug!

**Comment by silvioprog** [comment]
> I'm going to close this since persistent connections are enabled, but certainly file an issue with a small example if you find a bug!

No problem bro. I'm going to open a new issue showing the problem related to the routing. It is hard to debug, so I'm not sure which layer is responsible to make the routing slow.
