### ISSUE TITLE
Allow access to the full request path

### ISSUE THREAD

**Issue by renato-zannon** [seanmonstar/warp#80]
I was trying to build a HMAC authorization filter, but couldn't figure out how to write it in a way that is generic over all routes. I ended up building something like this:
```rust
warp::get2()
    .and(warp::path("foo"))
    .and(warp::param())
    .and(warp::header::headers_cloned())
    .and_then(|param, headers| {
      verify_signature(http::Method::GET, format!("/foo/{}", param), headers).map(|_| param))
    })
    .and_then(my_normal_handler)
```
Which feels suboptimal, especially for applications that have many routes.
(I'm aware of `warp::method()`, but that doesn't help much when I have to duplicate the path anyway)

It seems like `warp::log()` has access to that information internally. Would you be open to exposing `route.full_path()` as a public filter somehow?

Thanks!

**Comment by seanmonstar** [comment]
Something like this seems fine! The docs should make it clear that it probably shouldn't be used for matching... And a name is needed. `full`? `raw`? Anything else?

**Comment by renato-zannon** [comment]
`warp::path::full()` sounds good to me! I'll cook up a PR :)

**Comment by renato-zannon** [comment]
> I am curious how you implemented returnning 401 Authenticate (+ dynamic realm information in the challencge?) in your hmac filter

@algermissen I didn't (at least not yet) :) This is a private API, so I can get away with just returning `warp::reject()` for non-authenticated requests for now (ideally would be a 401).
