### ISSUE TITLE
Add a path() filter that does not consume

### ISSUE THREAD

**Issue by richardbrodie** [seanmonstar/warp#82]
I'm trying to add a static-asset route that works with Parcel, which doesn't give much control over the paths pointing to the assets. I'm stuck with all my assets being located at `/` such as `/index.html`, `/src.33108049.css`, and `/src.9f4de76d.js`. Rather than use `warp::fs::dir("./ui/dist")` and just rely on the filter failing if a requested file doesn't exist, I wanted to be more precise.

Per #19 I've created a `struct AssetFile(String)` type that I can use with `warp::path::param::<AssetFile>()` to filter matching filenames, but I'm stuck with how to use the result.

`.and(warp::fs::file(blah_blah))` obviously ignores the param, using `warp::tail()` internally, while `.map(|asset: AssetFile| warp::fs::file(asset.to_path())` returns the error `the trait 'warp::reply::sealed::ReplySealed' is not implemented for 'impl warp::filter::FilterClone'`. 

With so much of the internals of warp private, there's not much scope to implement missing traits. I thought about just implementing the `tokio_fs` stuff in a seperate function that returns `impl warp::Reply` but that seems silly since `warp::fs` already does it.

There are three options I can see, but I suspect a large part of this problem is down to my own inexperience:

1) Add a new filter that allows to match a path or param, without modifying the route - it will pass on to the next filter if successful, but when that filter uses `tail()` it will still have access to the segment that the previous filter matched on.
2) Allow `warp::fs::file` to be used in `.map` and `.and_then` 
3) Keep warp lean and just stick with something like `.map(|asset: AssetFile| my_serve_asset_fn(asset))`
4) I've missed something obvious and am happy to be schooled

In the cases of 1 and 2, I'd be happy to try making a PR if desired.

**Comment by richardbrodie** [comment]
I've thought about this some more and the specific issue that I think I'd like to address is that there ought to be a more precise way to specify files using `warp::fs::file` and `warp::fs::dir`. It would make my particular problem easier, but more generally I can definitely see cases where you might want to use `dir()` but not blindly allow **all** files from that location to be served. Similarly, I think it would be very useful to be able to be a little more flexible about what file is served by `file()`.

I've solved my problem for now with
```rust
let assets = warp::get2()
    .and(warp::path::param::<AssetFile>())
    .and_then(|a: AssetFile| serve_static(a));
```

For just this issue I'm leaning more towards allowing `dir()` to be whitelisted somehow. I propose a new filter that matches a segment of the path but doesn't consume it. For example, for a directory containing `some_asset.css`, `some_asset.js`, and `some_file_I_dont_want_to_serve.txt` I could do something like this:

```rust
let assets = warp::get2()
    .and(warp::path("static"))
    .and(warp::path::whitelist(|s: impl FromStr| {
        something_that_returns_ok_or_err_based_on_s
     }))
    .and(warp::fs::dir(my_asset_directory));
```

**Comment by seanmonstar** [comment]
- There currently exists `warp::path::full()` to be able to inspect the full path at any point, but it may be more annoying to inspect a certain segment after matching a couple...
- In Akka HTTP, there's `pathPrefixTest`, which seems to do exactly as you describe: you can match multiple segments, and if successful, the "matched path" isn't altered. It'd be a little more difficult in warp since there isn't this dynamic `PathMatcher` that can match multiple segments at once...

**Comment by richardbrodie** [comment]
Yeah, it looks like `pathPrefixTest` and `PathMatcher` are pretty much exactly what I was imagining, but a lot more powerful.
