### ISSUE TITLE
Tests with spaces in query string

### ISSUE THREAD

**Issue by NoSuchThingAsRandom** [seanmonstar/warp#823]
Using the test framework to simulate requests like:
```warp::test::request().path("/api?somekey=someparam")```
Works fine.

But if you insert a space like:
```warp::test::request().path("/api?somekey=some param")```
It crashes with "test request path invalid" at https://github.com/seanmonstar/warp/blob/b6d1fc0719604ef1010aec00544408e6af1289a5/src/test.rs#L200
Because it attempts to directly parse the given path as a URI. But spaces in URI should be percent encoded, so it is rejected.

And, if you do percent encode it:
```warp::test::request().path("/api?somekey=some param")```
It parses fine, but instead of sending a space to the request handler, it actually sends a ```%20```
So the handler performs incorrectly.

However, if you make a web request with that same path: ```"https://someurl.com/api?somekey=some param```, it parses fine, and sends the space to the handler.

So tests cannot be written to match web requests (with a space in query parameters).

**Comment by Anthuang** [comment]
If you use the `filter` function defined for `request`, like here https://github.com/seanmonstar/warp/blob/c52638be787fc01374c5263d75ea74e63283238a/tests/query.rs#L7-L16, it'll parse the `%20` and pass a space to the handler.
