### ISSUE TITLE
Any interest in a Prometheus metrics method?

### ISSUE THREAD

**Issue by calvinbrown085** [seanmonstar/warp#828]
Currently there is a middleware that exposes information via Log, you can shim this in with the middle ware and Prometheus easily, but it’d be nice to have its own module.

Method or feature flag giving Prometheus metrics

If this isn’t the right place, I’m also open to writing my own crate for this.

Thanks!!

**Comment by apiraino** [comment]
Hi @calvinbrown085 that would an interesting addition.

Simply out of personal curiosity, do you already have a high-level idea on how to plug it to Warp and how would this addition be related to the prometheus crate (i.e. would a Warp module use that directly?). Would that be an opt-in feature? (for example I think `tracing` is a hard dependency of Warp, whether you use it or not)

**Comment by calvinbrown085** [comment]
@apiraino I've already built some of the functionality with `warp::log::custom`, but it's somewhat of a bit of code, but my original thought was something like 
`.with(warp::metrics::prometheus()` that you could wrap routes in. 
I would think it could be an opt-in feature since not all users of Warp care about prometheus.

**Comment by BratSinot** [comment]
@calvinbrown085 Hello. In your experiments, did you do metrics related to connections?

**Comment by calvinbrown085** [comment]
@BratSinot Can you elaborate on what you mean by `connections`? Do you mean like active connections to the web server? Or something else?

**Comment by BratSinot** [comment]
@calvinbrown085 Yes, I mean alive HTTP and WebSocket connections.

**Comment by calvinbrown085** [comment]
@BratSinot I didn't do any metrics related to connections, but that could be part of it.

**Comment by BratSinot** [comment]
@calvinbrown085 
I wish I could use it now without modification warp itself =(
Thanks anyway.

**Comment by calvinbrown085** [comment]
@BratSinot Yeah, but maybe if there is enough interest in the issue it could be integrated 😄

**Comment by calvinbrown085** [comment]
I did just publish this crate https://github.com/calvinbrown085/warp-prometheus

**Comment by calvinbrown085** [comment]
I'm going to close this issue. As there is a crate available now.
