### ISSUE TITLE
Documentation for and_then and or_else

### ISSUE THREAD

**Issue by EvanCarroll** [seanmonstar/warp#844]
It would be great if there was some documentation or examples on these. Currently there is almost nothing. We don't have a single example of how we call an `pub async fn` in warp route/filter. It would be great to put some more of this stuff out there.

**Comment by jxs** [comment]
Hi, did you see the [`todos`](https://github.com/seanmonstar/warp/blob/master/examples/todos.rs) example? Has multiple combinations of `async fn`'s on `and_then` handlers, more examples such as the [`rejections`](https://github.com/seanmonstar/warp/blob/master/examples/rejections.rs) or the [`futures`](https://github.com/seanmonstar/warp/blob/master/examples/futures.rs) also show `and_then` with `async fn` usage.

**Comment by jxs** [comment]
nice thanks for the interest . 
There's also https://github.com/seanmonstar/warp/issues/333 with the idea of a warp book, feel free to read and comment there. I am going to close this one to keep the conversation in one place

**Comment by cmcqueen** [comment]
I would like to see this reopened and addressed in other places besides a possible future warp book.

I specifically went looking for an explanation and example usage of [`.or_else()` in the documentation](https://docs.rs/warp/latest/warp/trait.Filter.html#method.or_else). But the documentation is terse, and has no example for this function.

I don't know how other people learn best, but I often find one practical example of usage is worth a thousand words.

**Comment by EvanCarroll** [comment]
I've since moved to using Axum.
