### ISSUE TITLE
CORS error while returning an Error

### ISSUE THREAD

**Issue by octave99** [seanmonstar/warp#845]
I have this [repository with  a sample warp application](https://github.com/octave99/corserr) on latest versions. 

Code has two APIs, one returning Ok/200 and second returns BadRequest/400 response.

API returning Ok/200, named "/yes", works fine with expected response. While API returning BadRequest/400, named "/no", throws back CORS error in the browser console, but works fine from curl or REST Client Browser Extension. 

Function _handle_rejection_ is correctly being called with correct status code and message, but its not reflecting in the browser nor warp  log. Warp log displays 500 error code, while code should be 400, as reflecting in _handle_rejection_. 

Issue is observed in both firefox and chrome.

Repository source has index.htm file in the root with instructions to simulate the issue. Thank you,

**Comment by octave99** [comment]
Solution has been updated to the repository which was merely change in the order of filters, like so:

```rust
let routes = routes()
    .recover(handle_rejection)
    .with(warp::log("cors test"))
    .with(cors());
```

I am not sure, if I missed the documentation, but may be solution might help someone else. Thank you.

**Comment by Niedzwiedzw** [comment]
wow nice catch
