### ISSUE TITLE
[Question] How to get path after prefix /hello/*

### ISSUE THREAD

**Issue by richardanaya** [seanmonstar/warp#85]
Hey there :) 

Loving warp so far, trying to figure out how to do this?

let hello = path!("hello" / String).map(|name| format!("{}", name))

http://127.0.0.1:3030/hello/richard/test => "richard/test"
http://127.0.0.1:3030/hello/richard/test/any/depth => "richard/test/any/depth"

**Comment by seanmonstar** [comment]
To match the "tail", you can use `warp::path::tail()`. So, it'd be like `warp::path("hello").and(warp::path::tail())`.

**Comment by richardanaya** [comment]
Thank you!
