### ISSUE TITLE
Can not aceess custom file

### ISSUE THREAD

**Issue by incker** [seanmonstar/warp#850]
I want to select file `path + tail + ".gz"`

My shorten code:

    let route  = warp::any()
        .map(move || path.clone())
        .and(warp::path::tail())
        .and_then(|path, tail| warp::fs::file("index.html").filter());

I receive an error:

    65 |         .and_then(|path, tail| warp::fs::file("index.html").filter());
       |                                                             ^^^^^^ method cannot be called on `impl warp::filter::FilterClone` due to unsatisfied trait bounds

And this code:

    let route3 = warp::any()
        .map(move || path.clone())
        .and(warp::path::tail())
        .and_then(|path, tail| async { warp::fs::file("index.html") });

Gives such error:

    65 |         .and_then(|path, tail| async {warp::fs::file("index.html")});
       |          ^^^^^^^^ expected opaque type, found enum `Result`

How can I call `warp::fs::file(path).` with custom path, based on tail but ends on tail + ".gz"?
Thank you

**Comment by jxs** [comment]
Hi, yeah at the moment it's a shortcoming of the `file` filter, it has been raised on #526 as well, see also https://github.com/seanmonstar/warp/issues/171#issuecomment-463332404 for more info.
Thanks
