### ISSUE TITLE
Non-constant time comparison of secret header values can enable timing attacks

### ISSUE THREAD

**Issue by codahale** [seanmonstar/warp#859]
**Version**
`master`

**Platform**
all

**Description**
Currently, `warp::filters::header::exact` uses [a simple `==` comparison on header values to filter](https://github.com/seanmonstar/warp/blob/master/src/filters/header.rs#L148). For non-secret values (e.g., `dnt=1`), that’s totally fine. For secret values (e.g., [bearer tokens in headers](https://github.com/seanmonstar/warp/blob/master/examples/todos.rs#L86)), an attacker can measure the time the server takes to reject various values and [determine the secret value byte by byte](https://codahale.com/a-lesson-in-timing-attacks/).

Comparing secret values to client-provided values should be done with constant-time comparison routines, such as those in [subtle](https://doc.dalek.rs/subtle/trait.ConstantTimeEq.html).

**Comment by seanmonstar** [comment]
Thanks for the write-up. I'm aware of timing attacks. I don't believe this is an issue with warp itself. Anyone comparing genuine user secrets hopefully don't have the secrets in plaintext, but are using a strong hash function (like bcrypt or similar), which many may provide a safer compare function as well.

**Comment by codahale** [comment]
Password hashing isn’t typically used for bearer tokens, but bearer tokens are still instances of secret information.

If the intent is that `exact` not be used for comparing client-provided values to secret information, it may be wise to change the linked example to reflect that. As it stands, it compares client-provided bearer tokens to a static value in an insecure manner with a comment immediately above it saying that the given usage is “to show how authentication filters are used“.
