### ISSUE TITLE
Accept missing query string for optional argument

### ISSUE THREAD

**Issue by kaj** [seanmonstar/warp#86]
Hi!  I have a handler that should accept an optional query parameter, so both `http://myhost/path/?arg=foo` and `http://myhost/path/` should be handled by the same method.

For that I use a route that looks like this (get() is really use warp::get2 as get, to be prepared for coming versions).

```rust
        .or(get().and(path("path")).and(index()).and(query()).map(myhandler))
```

```rust
fn myhandler(param: ArgQ) -> Response<Vec<u8>> { ... }

#[derive(Debug, Deserialize)]
struct ArgQ {
    arg: Option<String>,
}
```

This works fine as long as there is a query string in the request, i.e. `/path?arg=foo` gives me an ArgQ where arg is `Some("foo")` and `/path?somethingelse=whatever` or even just `/path?` gives med arg = `None`.  But `/path` (without a question mark) gives me a bad request without even entering my handler.  Is this a bug?  Or should I somehow mark `query()` to be optional?

**Comment by kaj** [comment]
I tried deriving an implementation of `Default` for `ArgQ`, but it didn't help.

**Comment by seanmonstar** [comment]
You use `map` in the index case to create a default before then mapping to the main handler.

**Comment by kaj** [comment]
I'm not sure I understand what you mean ...  I got it to work with double routes, like this:

```rust
        .or(get().and(path("path")).and(index()).and(query()).map(myhandler))
        .or(get().and(path("path")).and(index()).map(|| myhandler(Default::default())))
```

(In my real code, this gets more complicated, since I also have a filter that checks for an authorization cookie and adds an optional user argument to the handler.)

After some further experimentation, I managed to create a function `optq` to use instead of `query`.  This works fine, but seems a little more complicated than what I think should be necessary:

```rust
        .or(get().and(path("path")).and(index()).and(optq()).map(myhandler))

...
fn optq<T: 'static+Default+Send+DeserializeOwned>() -> BoxedFilter<(T,)> {
    any()
        .and(query().or(any().map(|| T::default())))
        .unify()
        .boxed()
}
```

I still think that it would be easier if the `query()` filter simply treated no query-string as the same thing as an empty query-string.

**Comment by kdar** [comment]
Just to add based on @kaj's answer, this is for optional raw queries:
```rust
fn raw_query() -> impl Filter<Extract = (String,), Error = warp::Rejection> + Copy {
  warp::any().and(
    warp::filters::query::raw()
      .or(warp::any().map(|| String::default()))
      .unify(),
  )
}
```
