### ISSUE TITLE
warp::filters::fs sporadically only reads the first 8,092 bytes of files on *nix

### ISSUE THREAD

**Issue by joell** [seanmonstar/warp#862]
I am observing inconsistent behavior in which `warp::filters::fs` filters for serving files are serving only the first 8,092 bytes on a Linux system with a BTRFS filesystem.  I say "inconsistent", because with files newly written to the filesystem, warp is serving the entire file correctly, but once enough time has lapsed (and presumably something in the underlying FS changes in how those files' data is accessed, despite no OS-level modifications to the files in that time period) warp only serves the first 8KiB.

Summarized another way: I can write a new file to disk and serve its full content with `warp::filters::fs::dir`, go to bed, come back in the morning, send the same HTTP request for the same file, and I will only get 8,092 bytes from warp this second time.  I can confirm that the file's content was not modified in any way in the intervening time.  (I took hashes of the file before and after to verify this.)

I've dug into the code and found what might be part of the reason for this, but I'm not all the way to an answer.  Check out this section of the `warp::filters::fs::file_stream` function:

https://github.com/seanmonstar/warp/blob/46734106f6a2d523c0dd6b5c6a8415350acb5b72/src/filters/fs.rs#L432-L443

The `file_stream` function calls `tokio_util::io::poll_read_buf` to read file data into a pre-allocated buffer.  Afterward, it is presumed that if the result was `Ok(0)` then end-of-file was reached.  This seems reasonable since the docs for [`tokio::io::AsyncRead::poll_read`](https://docs.rs/tokio/1.6.1/tokio/io/trait.AsyncRead.html#tymethod.poll_read) state that "if no data was read ... it implies EOF has been reached."

But the caveat is that `poll_read_buf` has slightly different semantics (which are not mentioned in its documentation).  If you consult its [source code](https://docs.rs/tokio-util/0.6.7/src/tokio_util/lib.rs.html#111), you will see that it returns `Ok(0)` if the mutable buffer has no capacity remaining to write into.

So there's an extra logic branch in which `n == 0` might not mean an EOF, but I'm still puzzled on how `file_stream`'s code might trigger that particular branch.  All I can presume is that my BTRFS filesystem must be providing file data chunks in a different size and/or timing when the file is "older" than when it is fresh, and that's somehow triggering a different state in the code here.

(I can also confirm that other utilities like `cat` can read the files in question in their entirety, so I'm fairly certain it's not actually a true early EOF.)

Any insight or effort you can provide into resolving this would be greatly appreciated.

**Comment by seanmonstar** [comment]
What version of Tokio is in your lock file? There was a new release, and then a patch afterwards ([v1.6.1](https://github.com/tokio-rs/tokio/releases/tag/tokio-1.6.1), that's related to a bug in some kernels. Does upgrading to latest Tokio fix it?

**Comment by joell** [comment]
That was exactly my issue.  I still had Tokio 1.6.0 and I'm running Linux 5.10.  Upgrading to 1.6.1 resolved the problem.

Sorry to waste your time on a problem that had nothing to do with warp.  (And thanks for all you work on warp, too!  It's a great web framework!)
