### ISSUE TITLE
filter directly used in and without being combined using or does not compile

### ISSUE THREAD

**Issue by Bengreen** [seanmonstar/warp#888]
**Version**
warp v0.3.1
**Platform**
OSX

**Description**
I followed the todo example which I have got working nicely. I then started to reduce it down a little to suit a minimal example I was aiming to try out but find that it is not possible to add a filter object inside an and on its own and have to apply a duplicate .or function to make it work.

    mod filters {
        use warp::Filter;
        use super::handlers;

        pub fn sample(
            basepath: &'static str,
        ) -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
            warp::path(basepath)
            .and(
                sample_1()
                    .or(sample_1()) // Do not know why this is required and a single item does not work
            )
        }

        pub fn sample_1() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
            warp::get()
                .and(warp::path!("sample1"))
                .and_then(handlers::sample_h)
        }
    }
    mod handlers {
        use std::convert::Infallible;

        pub async fn sample_h() -> Result<impl warp::Reply, Infallible> {
            println!("Sample:");
            Ok("Sample")
        }
    }

The code above will compile happily BUT if I remove the second `.or(sample_1())` then it fails with the error

    error[E0277]: the trait bound `impl Reply: warp::generic::Tuple` is not satisfied
    --> src/sampleservice.rs:11:10
    |
    11 |         .and(
    |          ^^^ the trait `warp::generic::Tuple` is not implemented for `impl Reply`

    error[E0277]: the trait bound `impl Reply: warp::generic::Tuple` is not satisfied
    --> src/sampleservice.rs:9:10
    |
    9 |     ) -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `warp::generic::Tuple` is not implemented for `impl Reply`
    |
    = note: required because of the requirements on the impl of `warp::filter::FilterBase` for `warp::filter::and::And<Exact<warp::path::internal::Opaque<&str>>, impl warp::Filter+Clone>`

[short summary of the bug]
a filter included in an and statement without a .or does not give correct return type.

Code in context is provided here: https://github.com/Bengreen/rusty-microservice/blob/master/src/sampleservice.rs#L11-L13

OR 
Do I need to apply a special function if only a single filter is provided.

**Comment by jxs** [comment]
Hi, you need to change the return signature on https://github.com/Bengreen/rusty-microservice/blob/master/src/sampleservice.rs#L17 to:
```Rust
    pub fn sample_1() -> impl Filter<Extract = (impl warp::Reply,), Error = warp::Rejection> + Clone {
``` 
see [here](https://docs.rs/warp/0.3.1/warp/trait.Filter.html#extracting-tuples) for more info

**Comment by Bengreen** [comment]
Thanks for the pointers @jxs . Would it make sense to update the todo example to reflect this return type?
