### ISSUE TITLE
Compression based on "Accept-Encoding"

### ISSUE THREAD

**Issue by incker** [seanmonstar/warp#893]
Hello, I can gzip content using

`.with(warp::compression::gzip())`

But how can I gzip or not based on incoming "Accept-Encoding" headers?

Forward thank you

**Comment by kaj** [comment]
This is previously discussed in PR #513 and Issue #768 .  As none of those are closed yet, this issue should probably count as a duplicate.

**Comment by incker** [comment]
I see. need wait this [PR](https://github.com/seanmonstar/warp/pull/513)
Close as duplicate
