### ISSUE TITLE
document returning for websockets

### ISSUE THREAD

**Issue by rubycut** [seanmonstar/warp#897]
Hi, I checked returning.rs in the examples folder. It works fine, I am able to separate filter to function for testing.

However, one of my filter is Websocket based. I am not sure if it is possible to combine those two example, having websockets from websockets_chat.rs example and having them returned in the function as in returning.rs.

**Comment by jxs** [comment]
Hi, you mean [here](https://github.com/seanmonstar/warp/blob/master/examples/websockets_chat.rs#L38-L41)?
You can do:
```Rust
 // GET / -> index html
 let index = warp::path::end().map(|| warp::reply::html(INDEX_HTML));

 let routes = index.or(chat(users));


fn chat(
    users: impl Filter<
            Extract = (
                Arc<RwLock<HashMap<usize, mpsc::UnboundedSender<Result<Message, warp::Error>>>>>,
            ),
            Error = std::convert::Infallible,
        > + Clone
        + Send,
) -> impl Filter<Extract = (impl warp::Reply,), Error = Rejection> + Clone + Send {
    warp::path("chat")
        // The `ws()` filter will prepare Websocket handshake...
        .and(warp::ws())
        .and(users)
        .map(|ws: warp::ws::Ws, users| {
            // This will call our function if the handshake succeeds.
            ws.on_upgrade(move |socket| user_connected(socket, users))
        })
}
```

**Comment by jxs** [comment]
going to close this one, feel free to open again if you still have questions
