### ISSUE TITLE
GET request parameter is empty returned 400 `Invalid query string`

### ISSUE THREAD

**Issue by BogdanovAleksei** [seanmonstar/warp#905]
**Version**
└── warp v0.3.1
└── warp v0.3.1 (*)
├── warp v0.3.1 (*)
└── warp v0.3.1 (*)

**Platform**
Darwin LMRCRUM6M 19.6.0 Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64 x86_64

Linux docker-desktop 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description**

If the GET query parameter is empty, the serialization of warp::query<> to a parameter of type None does not pass

I tried this code:

``` rust
#[derive(Serialize, Deserialize, Debug)]
enum GetArgType {
    All,
    My,
    Deleted,
    Shared,
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct GetArgs {
    text: Option<String>,
    page_token: Option<String>,
    per_page: Option<i32>,
    r#type: Option<GetArgType>,
}

impl Default for GetArgs {
    fn default() -> Self {
        GetArgs {
            text: None,
            page_token: None,
            per_page: Option::Some(20),
            r#type: Option::None,
        }
    }
}

pub fn get_route() {
 warp::get()
        .and(warp::path!("v1" / "route"))
        .and(warp::query::<GetArgs>())
        .and_then(get_meetings_history)
}
```

request:
``` bash
curl --request GET  -v  --url 'http://127.0.0.1:8080/v1/route?type=&perPage=20' 

Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /v1/route?type=&perPage=20 HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< content-type: text/plain; charset=utf-8
< content-length: 20
< date: Fri, 01 Oct 2021 12:04:17 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
Invalid query string* Closing connection 0
 ```

I expected to see this happen: 
A structure with the type = None parameter and further process it

Instead, this happened: 
An error `Invalid query string` with a status of 400 was returned

**Comment by alexlee85** [comment]
same to me.
I think we should change query string library from serde_urlencoded to serde_qs.
serde_urlencoded library long time no update。

**Comment by jxs** [comment]
Hi, and thanks for explaining @alexlee85!, going to to close this one then
