### ISSUE TITLE
Returning a "102 PROCESSING" fails

### ISSUE THREAD

**Issue by SuperCuber** [seanmonstar/warp#908]
**Version**
warp = 0.3.1

**Description**
When you return a `102 PROCESSING` response, it seems to return an empty 500 response instead.
Code:
```rust
#[tokio::main]
async fn main() {
    warp::serve(warp::any().map(return_processing))
        .run(([127, 0, 0, 1], 8000))
        .await;
}

fn return_processing() -> impl warp::Reply {
    warp::reply::with_status("test", StatusCode::PROCESSING)
}

```
Expected behavior: browser sees a 102 response with body "test"
Actual behavior: browser sees a 500 response with an empty body

**Comment by jxs** [comment]
Hi, and thanks for your interest!
That is hyper behavior and is expected, see [here](https://github.com/hyperium/hyper/blob/master/src/proto/h1/role.rs#L302-L322) for more information.
