### ISSUE TITLE
Passing custom structs around

### ISSUE THREAD

**Issue by simon-whitehead** [seanmonstar/warp#91]
I'm trying to clean up some routing code by moving it into various modules.

One of the things I'm trying to do is wrap a heap of data about the request in a custom struct and pass that down the chain.

When I try this:

```
...
    warp::get2()
        .and(warp::any())
        .and(filters::web::request)
        .map(|request| Test { request: request })
        .and_then(|t: Test| t.render())
...

pub fn request() -> BoxedFilter<(impl Reply,)> {
    warp::header::<String>("User-Agent")
        .map(|user_agent| RequestDetails {
                user_agent: user_agent,
        }).boxed()
}
```

I get:

>  the trait `warp::reply::sealed::ReplySealed` is not implemented for `RequestDetails`

If I change the return type to `BoxedFilter<(RequestDetails, )>`, I get:

> the trait `warp::filter::FilterBase` is not implemented for `fn() -> warp::filters::BoxedFilter<(RequestDetails,)> {filters::web::request}`

No matter what I do, I can't seem to nicely wrap things in my own structs and pass them down the chain.  I feel like there is a fundamental misunderstanding of how this is meant to work for me here ... what am I doing wrong? How should I be structuring something like this?

**Comment by seanmonstar** [comment]
You're almost there! Don't worry, it's not a fundamental misunderstanding. You're just passing a `fn` to the `and` combinator, but it doesn't take functions, rather another filter. Just change it to `.and(filters::web::request())`.

**Comment by simon-whitehead** [comment]
Thank you! I thought it wanted a function because the examples used closures to unwrap things (and even other examples I've Google'd used closures to pass things around). My brain was so fried by the end I couldn't understand what it wanted.

This works great! Thanks so much!

![image](https://user-images.githubusercontent.com/2499070/45522499-ba513980-b806-11e8-8bc9-fb5adfe662ba.png)
