### ISSUE TITLE
Endpoint returns NOT_FOUND despite handler function finishing succesfully

### ISSUE THREAD

**Issue by Niedzwiedzw** [seanmonstar/warp#921]
**Version**
✦3 ❯ cargo tree | grep warp
└── warp v0.3.2

**Platform**
Linux niedzwiedz-pc 5.11.22-2-MANJARO #1 SMP PREEMPT Fri May 21 17:45:54 UTC 2021 x86_64 GNU/Linux

[short summary of the bug]

I tried this code:
```rust
async fn email_confirmation_handler(
    uuid: String,
    queue: MailConfirmationQueue,
) -> Result<impl warp::reply::Reply, Infallible> {
    or_error!(dbg!(email_confirmation_task(uuid,queue).await));
    Ok(warp::reply::with_status(
        warp::reply::json(&vec!["OK"]),
        dbg!(warp::hyper::StatusCode::OK), // this prints OK...
    ))
}
use warp::Filter;
pub fn email_confirmation_link(
    queue: MailConfirmationQueue,
) -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    warp::path("email-confirmation-link")
        .and(warp::path::param::<String>())
        .and(warp::get())
        .and(warp::any().map(move || Arc::clone(&queue)))
        .and_then(email_confirmation_handler)
}
```
and despite the logs showing that the handler has succesfully finished, I'm getting 404 NOT_FOUND anyway

**Comment by Stargateur** [comment]
without a mcve it's impossible to repro. try to give the full code including the main to reproduce this bug.

**Comment by Niedzwiedzw** [comment]
I was unable to reproduce but it did help me find the problem in my project, thank you for your advice @Stargateur . The problem was with filters setup, I had accidentally merged 2 of them rather than or()'ing them properly. In case anyone from the future stumbles upon that double check that. As for the issue it's a false alarm and can be closed.
