### ISSUE TITLE
Format issue when pasting certain content

### ISSUE THREAD

**Issue by Rhainland** [seanmonstar/warp#922]
**Platform**
Darwin macbook-pro-2.lan 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

**Description**
When copying text from websites, text editor or other locations, sometimes the text does not maintain its formatting when pasting into files opened through warp. 

The image added, shows the current json copied from a text editor, entered in a file created using Nano, the result of the paste is shown both using Warp, and iTerm 2. As can be seen in the image, text formatting in Warp is non-existent in this case, while iTerm2 maintains the format of the copy pasted text.

<img width="663" alt="Screenshot 2021-11-29 at 23 01 54" src="https://user-images.githubusercontent.com/7574288/143949862-4080aa22-cfaf-4913-b258-7547498dd48b.png">

The text;

{
"bus": "greyhound",
"car": "prius"
}

Steps to replicate:

1. Open warp terminal
2. Nano somefile
3. Copy the text above and paste it into the file opened by nano, in warp terminal
4. Result will look like the nano window in the warp terminal, in my image.

Do the same in iTerm2, result will look like the iTerm2 window in my image(correctly formatted)

I have additional examples where this format issue happens with just line by line text(no json) where empty spaces are added between each line etc.

**Comment by seanmonstar** [comment]
Hey there! I'm not sure this is the right project for this bug... This a project about an HTTP server framework. My guess based in your description is you're looking for one that is a terminal or similar?

**Comment by Rhainland** [comment]
Im so sorry, this bug was submitted in the wrong project - It was intended for the warp terminal, im embarrassed now :(

**Comment by seanmonstar** [comment]
No problem at all, it's an easy mistake (I didn't realize there was a terminal called warp, but same-named mix-ups happen all the time.)
