### ISSUE TITLE
Websocket chat example leaking memory?

### ISSUE THREAD

**Issue by mmalmi** [seanmonstar/warp#926]
I tried using a [minimally modified version](https://github.com/mmalmi/warp-websocket-example/blob/e53a3efc65ec139038637135bc20f0e687d03e86/src/main.rs) of the websocket example to simply broadcast received [gun-js](https://github.com/amark/gun) messages to all connected users.

However, memory usage keeps growing as users connect. Memory is never freed even if user_disconnected is called, and eventually it crashes if there's a lot of traffic. Tested on Heroku (Ubuntu) as well as macOS and Ubuntu VPS.

Any ideas? Warp v0.3.2

**Comment by jxs** [comment]
Hi! I see you checked https://github.com/snapview/tokio-tungstenite/issues/195#issuecomment-925355813 already. Have you also checked https://github.com/hyperium/hyper/issues/1790?

**Comment by mmalmi** [comment]
@jxs Thanks for pointing out the Hyper issue, seems like the same problem.
