### ISSUE TITLE
Possibility to disable shortcuts

### ISSUE THREAD

**Issue by wesleylether** [seanmonstar/warp#946]
## CMD + 0 resets the font to default settings of warp.

Maybe it is handy to have the ability to disable shortcuts within warp.
(Okay, I can set the shortcut to an incredible difficult shortcut to use.)

But I think it may be handy to disable some options in the shortcuts you do not want to use

**Comment by seanmonstar** [comment]
I think you want a different project. This warp is a web server framework in the Rust language. I've heard there is also a terminal emulator with the same name, I don't know its URL though.

**Comment by wesleylether** [comment]
Ahh damn! Sorry wrong repository 😓
