### ISSUE TITLE
Full screen toggle command is missing

### ISSUE THREAD

**Issue by selva-at-simpl** [seanmonstar/warp#955]
**Is your feature request related to a problem? Please describe.**
Full-screen toggle feature is missing. At times I want to make the current terminal to a full-screen view so that I can debug faster.

**Describe the solution you'd like**
A command and a keymap to toggle the full-screen view from any terminal view.

**Additional context**
I use full-screen toggle in iTerm2, please refer for more details.

**Comment by apiraino** [comment]
@selva-at-simpl seems like you're looking for another Warp project

**Comment by selva-at-simpl** [comment]
Oops, should have looked at README. Thanks for pointing out @apiraino!!
