### ISSUE TITLE
I want to be able to customize the window size

### ISSUE THREAD

**Issue by wChenone** [seanmonstar/warp#961]
**Is your feature request related to a problem? Please describe.**

I want to be able to customize the window size

**Comment by wChenone** [comment]
I really don't like that every startup is a big window. I hope I can set the window size every time I start.

**Comment by kaj** [comment]
Are you talking TCP windows here, or any kind of desktop windows?  If you are talking on visibile windows on a screen, you are probably talking about some other project.  This is a library for making web services.

**Comment by wChenone** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/37658262/164965793-455dfc15-0ec4-4b4b-8e32-337d5a4f2fab.png">
desktop windows     What I screenshot is iterm, and I can set the window size that I want every time I start.

**Comment by Asjas** [comment]
@wchenone Are you referring to Warp Terminal? http://warp.dev

**Comment by wChenone** [comment]
yes，  warp  Every time you start this window will be very large, can not be customized so that the startup can be smaller, I like it a little smaller

**Comment by Asjas** [comment]
As stated by @kaj, you are in the wrong repository. 🙂

This `warp` repository is a Rust library for creating Web Services.

https://github.com/warpdotdev/warp

**Comment by wChenone** [comment]
sorry， I see
