### ISSUE TITLE
Support for sequence as a keybinding

### ISSUE THREAD

**Issue by kuklyy** [seanmonstar/warp#965]
**Is your feature request related to a problem? Please describe.**
I'm trying to use your software instead of iTerm, but there is one key feature that is missing. I really want to use a sequence of e.g. `ctrl` + `ctrl` to summon the terminal window.

**Describe the solution you'd like**
When I double press `ctrl` (or any other key) the terminal window should appear on the screen.

**Comment by Asjas** [comment]
You opened your issue in the wrong repo, this warp project is a Rust HTTP library @kuklyy

**Comment by kuklyy** [comment]
OPS
