### ISSUE TITLE
Cannot use ssh from fish-shell

### ISSUE THREAD

**Issue by arafune** [seanmonstar/warp#970]
Darwin arafuneryuuichinoMac-mini-5.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64 i386 Darwin

**Description**
Do not use ssh from fish-shell.

I tried this code:

ssh [IP address of the ssh server]
The error message is :

fish: Unsupported use of '='. In fish, please use 'set hook $(printf "{\"hook\": \"SSH\", \"value\": {\"socket_path\": \"~/.ssh/22388\", \"user\": \"%s\", \"machine\": \"%s\", \"remote_shell\": \"%s\"}}" $(whoami) $(hostname) ${SHELL##*/} | command od -An -v -tx1 | command tr -d " \n")'.
Connection to [IP address of the ssh server] closed.

As this command works well from the other terminal, this problem is due to the warp shell.

**Comment by Asjas** [comment]
@arafune you opened this issue in the wrong repo, this is a Rust HTTP server library
