### ISSUE TITLE
PS1 when using python's virtualenv is broken

### ISSUE THREAD

**Issue by adityanatraj** [seanmonstar/warp#971]
**Version**
- v0.2022.05.16.09.01.stable_01

**Platform**
MacOS 12.4

**Description**

After entering and exiting a python [virtual environment](https://docs.python.org/3/library/venv.html#:~:text=A%20virtual%20environment%20is%20a,part%20of%20your%20operating%20system), the PS1 of the terminal is broken for the rest of the session.

steps to reproduce:
- create any virtualenvironment `python -m venv env`
- note your current, wonderful PS1
- activate the python environment with `source env/bin/activate`
- see the usual and expected "(env)" be in the PS1
- deactivate the python environment with `deactivate`
- note that your old, wonderful PS1 is no longer there and the "(env)" remains though you're not in the environment

expectation:
- the addition of "(env)" to the normal, user-configured PS1 when in the environment
- the normal, user-configured PS1 when outside the environment

**Comment by seanmonstar** [comment]
This repo is for a server framework, not the terminal.
