### ISSUE TITLE
Exclude from Dock and cmd + Tab application switcher

### ISSUE THREAD

**Issue by xiaoyu-tamu** [seanmonstar/warp#972]
**Is your feature request related to a problem? Please describe.**

I use hotkey window most time, and hope warp can exclude itself from cmd + Tab application switcher.

**Additional context**

item2 support this feature 

<img width="781" alt="image" src="https://user-images.githubusercontent.com/33362998/170787159-5a8cfb07-6eec-4e93-a18e-a2f00707a135.png">

**Comment by seanmonstar** [comment]
This repo is for a web framework, not the terminal.
