### ISSUE TITLE
Filter for URL anchors?

### ISSUE THREAD

**Issue by hjfitz** [seanmonstar/warp#977]
**Is your feature request related to a problem? Please describe.**

There’s no way to view anchor tags: I don’t think there’s any way of performing an implicit oauth flow with a token. 

**Describe the solution you'd like**

A filter where I can read anchors in the url, eg: #accessToken=

**Describe alternatives you've considered**

other frameworks

**Additional context**

I could have missed this in the docs. There’s definitely a filter for query parameters but literally nothing for the full path requested.

**Comment by kaj** [comment]
Anchors in the url (i.e. anything after a `#` character) is _not sent to the server_, so nothing warp can do will make it possible to access it serverside.  Luckily, all oauth flows that I've handled have used query paramters to the token.  A token passed by anchor can only be used client-side, in javascript (or wasm).

**Comment by hjfitz** [comment]
Thanks, looks like I need to read back up on my basics
