### ISSUE TITLE
cors header allow all ?

### ISSUE THREAD

**Issue by kimtony** [seanmonstar/warp#978]
**Version**
List the versions of all `warp` crates you are using. The easiest way to get
this information is using `cargo-tree`.

`cargo install cargo-tree`
(see install here: https://github.com/sfackler/cargo-tree)

Then:

`cargo tree | grep warp`
warp v0.3.2

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

**Description**
Enter your issue details here.
One way to structure the description:

![image](https://user-images.githubusercontent.com/34413109/173780712-8de0e4be-5088-4e42-91c3-a8133007d45e.png)

I tried this code:

![image](https://user-images.githubusercontent.com/34413109/173780526-9249bddf-9df7-42a2-87c7-681af25b2a31.png)

I expected to see this happen: [explanation]

Instead, this happened: [explanation]

**Comment by Rackme** [comment]
https://stackoverflow.com/questions/69542810/has-been-blocked-by-cors-policy-the-request-client-is-not-a-secure-context-and

It seems to be a Private Network Access restriction, not a bug
