### ISSUE TITLE
Support for compdef

### ISSUE THREAD

**Issue by ericwooley** [seanmonstar/warp#979]
**Is your feature request related to a problem? Please describe.**
Many commands support auto complete. EG if you make your own cli with [yargs](https://yargs.js.org/docs/#api-reference-showcompletionscript), a completion script is automatically generated for you. It looks something like this: 

https://app.warp.dev/block/z7a8d3USpyUZ6boe3odWaF

```bash
#compdef sb
###-begin-sb-completions-###
#
# yargs command completion script
#
# Installation: sb completion >> ~/.zshrc
#    or sb completion >> ~/.zprofile on OSX.
#
_sb_yargs_completions()
{
  local reply
  local si=$IFS
  IFS=$'
' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" sb --get-yargs-completions "${words[@]}"))
  IFS=$si
  _describe 'values' reply
}
compdef _sb_yargs_completions sb
###-end-sb-completions-###
```
Pressing tab with the command partially in your prompt comes up with something like: 
![image](https://user-images.githubusercontent.com/1930227/174326259-84ec58c6-a9c1-4069-a4a1-ec470340aef2.png)

**Describe the solution you'd like**

I have been looking for how to get this setup in warp, but have yet to find any reference to where you can add such a definition. I suspect that it's a large lift that is not yet supported. Pressing tab brings up a list of files, instead of a list of available commands recommended by my cli.

**Describe alternatives you've considered**

Workflows maybe? But that is very manual, and I don't want to do that. Unless I am missing some way to tie in auto completes.

**Additional context**
This is just a minor gripe to an otherwise great project, keep up the good work!

**Comment by seanmonstar** [comment]
This repo is for a web server framework, not the terminal app.
