### ISSUE TITLE
search bar should be extendable automatically

### ISSUE THREAD

**Issue by guy1699** [seanmonstar/warp#982]
See how the text is covered and cannot be read. also moving the cursor across the search pattern does not reveal the hidden part.
Plus, when going out of focus and back in focus to the search bar, it does not highlight the text which makes new paste text to be appended instead of replacing the current text.

<img width="659" alt="Screen Shot 2022-07-10 at 08 29 46" src="https://user-images.githubusercontent.com/15769295/178132602-0baaec9a-c8cc-4436-87d5-e464b25c8f23.png">

**Comment by kaj** [comment]
This repo is a web server framework.  This issue is probably about https://github.com/warpdotdev/Warp ?

**Comment by guy1699** [comment]
yes, closing this one.
