### ISSUE TITLE
Using Warp, When ssh connect to ubuntu server, I can not cd directory by autocompletion

### ISSUE THREAD

**Issue by zilianghu** [seanmonstar/warp#985]
**Version**
List the versions of all `warp` crates you are using. The easiest way to get
this information is using `cargo-tree`.

`cargo install cargo-tree`
(see install here: https://github.com/sfackler/cargo-tree)

Then:

`cargo tree | grep warp`

warp v0.3.2

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

**Description**
Enter your issue details here.
One way to structure the description:

In local machine, I can using "TAB" key, to change directory, like below:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/19609874/183793887-bc23bba1-5522-4fbb-b0e3-ba151a4b992f.png">

but  ssh connect to ubuntu server,  it shows "starting shell"

<img width="385" alt="image" src="https://user-images.githubusercontent.com/19609874/183794009-0a54b4c0-ce5f-45a5-8af8-a904a35ed94e.png">

if I am in "/" directory, i also can use "TAB" key to change select directory

<img width="399" alt="image" src="https://user-images.githubusercontent.com/19609874/183794238-179f392f-ad2d-44c4-a970-4e4d92d8c20e.png">

But if I am not in "/" directory, press "TAB" key, nothiong happened.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/19609874/183794375-c24689bd-aeb2-49c3-9538-6e2f800d28fa.png">

I wanna anyone met this problem?

**Comment by seanmonstar** [comment]
This repository is for a web server called warp, not the terminal program.
